### ISSUE TITLE
Bottom send message box style seems to be boken!

### ISSUE THREAD

**Issue by sharukhkhanajm** [flyerhq/flutter_chat_ui#116]
Hi
I am trying to use Chat widget in order to create the UI
everything seems to be working, except the bottom send message style
here how it looks on my emulator
![image](https://user-images.githubusercontent.com/47321682/134102025-307d38b7-f60b-4d35-ae94-29fc6c67fcd8.png)
and here is my code

```
SafeArea(
                bottom: false,
                child: Chat(
                  isAttachmentUploading: _isAttachmentUploading,
                  messages: snapshot.data ?? [],
                  onAttachmentPressed: _handleAtachmentPressed,
                  onMessageTap: _handleMessageTap,
                  onPreviewDataFetched: _handlePreviewDataFetched,
                  onSendPressed: _handleSendPressed,
                  user: types.User(
                    id: FirebaseChatCore.instance.firebaseUser?.uid ?? '',
                  ),
                  showUserAvatars: true,
                  showUserNames: true,
                ),
              )
```

Could you please help me figure out this issue?
Thanks for the help in advance :)

**Comment by demchenkoalex** [comment]
Hi @sharukhkhanajm you didn't say what you want to achieve :)

**Comment by sharukhkhanajm** [comment]
Hi @demchenkoalex thanks for the reply
I want to achieve below style given on home page
![image](https://user-images.githubusercontent.com/47321682/134268681-d3e94f74-4610-48a3-8790-f563c458452e.png)
are there any props to be passed down in order to achieve this?
Thanks

**Comment by dariakhimych** [comment]
Hey @sharukhkhanajm It's true, the input field design on the home page looks a bit different from the actual implementation. That's part of my design promotion project, and it wasn't originally planned to be included in the actual Flyer Chat library. The way it is shown in the build is the way it have to work / look like. Sorry for the inconvenience.

**Comment by demchenkoalex** [comment]
To answer specifically, no props are present to make this effect since it was never planned. Feel free to open a PR though.

**Comment by sharukhkhanajm** [comment]
Thanks, @dariakhimych  and @demchenkoalex for clarification 👍 
then in that case I will have to create my own UI for that.
I would definitely try to contribute to this awesome project ASAP, specially the Core one. 💯

**Comment by mattg1995** [comment]
Hi @sharukhkhanajm ,

Is there anyway to style the input to remove the white border around it? It seems to disappear on focus, sorry if this is an old topic I am struggling to find out how.

Thanks
