### ISSUE TITLE
flutter_link_previewer error

### ISSUE THREAD

**Issue by bigmsg** [flyerhq/flutter_chat_ui#12]
I use StreamBuilder widegt

and have error bellow code

maybe at flutter_link_previewer plugin

[✓] Flutter (Channel unknown, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale en-KR)
    • Flutter version 2.0.5 at /Users/bigmsg/fvm/versions/2.0.5
    • Framework revision adc687823a (13 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc2)
    • Android SDK at /Users/bigmsg/Library/Android/sdk
    • Platform android-30, build-tools 31.0.0-rc2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following StateError was thrown by an image listener:
flutter: Bad state: Future already completed
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #1      _getImageSize.<anonymous closure> (package:flutter_link_previewer/src/utils.dart:110:43)
flutter: #2      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:618:25)
flutter: #3      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:954:5)
flutter: #4      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:878:7)
flutter: #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
flutter: #6      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1058:11)
flutter: #7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
flutter: #8      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1056:17)
flutter: #9      SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:977:5)
flutter: #13     _invoke1 (dart:ui/hooks.dart:180:10)
flutter: #14     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:231:5)
flutter: #15     _beginFrame (dart:ui/hooks.dart:108:31)
flutter: (elided 4 frames from dart:async)

**Comment by demchenkoalex** [comment]
Hi @bigmsg we will look into that

**Comment by bigmsg** [comment]
> Hi @bigmsg we will look into that. Can you provide a minimal piece of code that can reproduce this error? We didn't observe this behavior when using chat UI with StreamBuilder from firebase core repo.


Thank you very much 😊



------------ chat page -------------
class ChatRoomPage extends StatefulWidget {
  String currentUserId;
  String otherUserId;
  String? chatRoomId;

  Map<String,dynamic>? gooin;
  Map<String, dynamic>? goojik;


  // ChatRoomPage({Key? key}) : super(key: key);
  ChatRoomPage({Key? key, required this.currentUserId, required this.otherUserId, this.chatRoomId, this.gooin, this.goojik}) : super(key: key);

  @override
  _ChatRoomPageState createState() => _ChatRoomPageState();
}


class _ChatRoomPageState extends State<ChatRoomPage> {

  ChatMessageBloc chatMessageBloc = ChatMessageBloc();

  List<types.Message> _messages = [];
  // List<ChatMessage> _messages = [];
  // final _user = const types.User(id: '06c33e8b-e835-4736-80f4-63f44b66666c');
  var _user;

  Timer? timer;

  @override
  initState() {
    print('------- chatroom initState -------');
    /*chatMessageBloc.initialFetch('mania',
      otherId: widget.otherUserId,
      roomId: widget.chatRoomId ?? '',
      bo_table: widget.gooin != null ? 'gooin' : 'goojik',
      wr_id: widget.gooin != null ? widget.gooin!['wr_id'] : widget.goojik!['wr_id'],
    );*/
    // widget.currentUserId = 'mania';
    // widget.currentUserId = 'bigmsg';
    _user = types.User(
      id: widget.currentUserId,
      firstName: '샵테라피',
      lastName: '별빛사랑',
      avatarUrl: 'https://www.massagemania.co.kr/data/file/gooin/thumb-990344487_apA82q0K_4f2ca17c577fbdb1d3e85c8b0d577f5f0761d414_350x150.jpg',
    );

    if(widget.chatRoomId == null) {
      // 1.other_id로 둘이 나누는 대화방 있는지 조회하기(
      // 2.bo_table, wr_id 건으로 채팅건이 있는지 조회
      getRoom();
    } else {
      chatMessageBloc.setChatRoomId(widget.chatRoomId!);
    }

    print('chatRoomId: ${widget.chatRoomId}');
    print('currentUserId: ${widget.currentUserId}');
    print('otherUserId: ${widget.otherUserId}');
    print('gooin: ${widget.gooin}');
    print('goojik: ${widget.goojik}');


    int wr_id = 0;
    String bo_table = '';
    if(widget.gooin != null || widget.goojik != null) {
      if(widget.gooin != null) {
        bo_table = 'gooin';
        wr_id = widget.gooin!['wr_id'] as int;
      }
      if(widget.goojik != null) {
        bo_table = 'goojik';
        wr_id = widget.goojik!['wr_id'] as int;
      }
    }
    chatMessageBloc.initialFetch(widget.currentUserId,
      otherId: widget.otherUserId,
      roomId: widget.chatRoomId ?? '',
      bo_table: bo_table,
      wr_id: wr_id,
    );

    // 메시지 pulling
    timer = Timer.periodic(Duration(milliseconds: 3000), (_) {
      //8chatMessageBloc.intervalFetch();
    });

    super.initState();
    //_loadMessages();
  }

  @override
  void dispose() {
    if(timer != null) timer!.cancel();
    chatsBloc.fetch(); // new message 읽음으로 표시되게끔 채팅목록 새로고침
    // chatNewMessagecountBloc.get();

    super.dispose();
  }


  /*
    이전에 개설된 방이 있는지 검색

   */
  getRoom() async {
    var res = await request.post(chatGetRoomUrl, body: {'mb_id': widget.currentUserId, 'other_mb_id': widget.otherUserId});
    var js = json.decode(res.data);
    if(js['room_id'] != '') {
      widget.chatRoomId = js['room_id'] as String;
      chatMessageBloc.setChatRoomId(widget.chatRoomId!);
      chatMessageBloc.initialFetch(widget.currentUserId, otherId: widget.otherUserId);
    }
  }


  void _addMessage(types.Message message) async {
    print('------------ _addMessage ------------');

    // print(message.);
    chatMessageBloc.sendMessage(message).then((isSuccess) {
      if(isSuccess) {
        //systemMessage();
      }
      else {
        //toast('해당 채팅방은 삭제되었습니다.');
        Navigator.pop(context);
      }
    });

    // 화면 새로고침
    /*setState(() {
      _messages.insert(0, message);
    });*/
  }

  void _handleAtachmentPressed() {
    print('------------ _handleAtachmentPressed ------------');
    _handleImageSelection();

    /*showModalBottomSheet<void>(
      context: context,
      builder: (BuildContext context) {
        return SizedBox(
          height: 144,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: <Widget>[
              TextButton(
                onPressed: () {
                  Navigator.pop(context);
                  _handleImageSelection();
                },
                child: const Align(
                  alignment: Alignment.centerLeft,
                  child: Text('Photo'),
                ),
              ),
              TextButton(
                onPressed: () {
                  Navigator.pop(context);
                  _handleFileSelection();
                },
                child: const Align(
                  alignment: Alignment.centerLeft,
                  child: Text('File'),
                ),
              ),
              TextButton(
                onPressed: () => Navigator.pop(context),
                child: const Align(
                  alignment: Alignment.centerLeft,
                  child: Text('Cancel'),
                ),
              ),
            ],
          ),
        );
      },
    );*/
  }

  void _handleFilePressed(types.FileMessage message) async {
    print('------------ _handleFilePressed ------------');
    await OpenFile.open(message.uri);
  }

  void _handleFileSelection() async {
    print('------------ _handleFileSelection ------------');
    final result = await FilePicker.platform.pickFiles(
      type: FileType.any,
    );

    if (result != null) {
      final message = types.FileMessage(
        authorId: _user.id,
        fileName: result.files.single.name ?? '',
        id: const Uuid().v4(),
        mimeType: lookupMimeType(result.files.single.path ?? ''),
        size: result.files.single.size ?? 0,
        timestamp: (DateTime.now().millisecondsSinceEpoch / 1000).floor(),
        uri: result.files.single.path ?? '',
      );

      _addMessage(message);
    } else {
      // User canceled the picker
    }
  }

  void _handleImageSelection() async {
    print('------------ _handleImageSelection ------------');
    final result = await ImagePicker().getImage(
      imageQuality: 70,
      maxWidth: 1200,
      maxHeight: 1200,
      source: ImageSource.gallery,
    );

    if (result != null) {
      Map<String, String> params = {'folder': chatFileUploadFolder};
      var res = await request.multipart(otherFileUploadUrl, pickedFile: result, body: params);
      Map<String, dynamic> js = json.decode(res.data);
      if(!js.containsKey('files')) return;

      final bytes = await result.readAsBytes();
      final image = await decodeImageFromList(bytes);
      final imageName = result.path.split('/').last;

      final message = types.ImageMessage(
        id: const Uuid().v4(),
        authorId: _user.id,
        imageName: imageName,
        height: image.height.toDouble(),
        width: image.width.toDouble(),
        size: bytes.length,
        timestamp: (DateTime.now().millisecondsSinceEpoch / 1000).floor(),
        uri: js['files'][0]['url'],
      );

      _addMessage(message);
    } else {
      // User canceled the picker
    }
  }

  void _handlePreviewDataFetched(
      types.TextMessage message,
      types.PreviewData previewData,
      ) {
    print('------------ _handlePreviewDataFetched ------------');
    //print(previewData.description);
    // final index = _messages.indexWhere((element) => element.id == message.id);
    // final currentMessage = _messages[index] as types.TextMessage;
    // final updatedMessage = currentMessage.copyWith(previewData);

    /*WidgetsBinding.instance?.addPostFrameCallback((_) {
      setState(() {
        _messages[index] = updatedMessage;
      });
    });*/
  }

  void _handleSendPressed(types.PartialText message) {
    print('----------- _handleSendPressed ------------');
    final textMessage = types.TextMessage(
      authorId: _user.id,
      id: const Uuid().v4(),
      text: message.text,
      timestamp: (DateTime.now().millisecondsSinceEpoch / 1000).floor(),
    );

    _addMessage(textMessage);
  }

  void _loadMessages() async {



    /*print('----------- _loadMessages ------------');
    final response = await rootBundle.loadString('assets/messages.json');
    final messages = (json.decode(response) as List)
        .map((e) => types.Message.fromJson(e as Map<String, dynamic>))
        .toList();


    setState(() {
      _messages = messages;
    });*/

  }


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('채팅'),
      ),
      body: StreamBuilder(
        stream: chatMessageBloc.stream,
        builder: (context, snapshot) {
          List<types.Message> data = [];
          if(snapshot.hasData && snapshot.data != null) data = snapshot.data as List<types.Message>;

          if(snapshot.hasData && data.length > 0) {
            _messages = data;
          } else {
            _messages = [];
          }
          return Chat(
            messages: _messages,
            onAttachmentPressed: _handleAtachmentPressed,
            onFilePressed: _handleFilePressed,                // 전송버튼
            // onPreviewDataFetched: _handlePreviewDataFetched,
            onSendPressed: _handleSendPressed,
            user: _user,
            theme: const DefaultChatTheme(
              inputBackgroundColor: Colors.orange,
              // backgroundColor: Colors.orange,
              inputBorderRadius: const BorderRadius.vertical(top: Radius.circular(20.0)),
              //attachmentButtonIcon: 'add',    // 안먹힘
              //sendButtonIcon: 'person',
            ),
            isAttachmentUploading: false,
            l10n: const ChatL10nEn(
                inputPlaceholder: '메시지입력',
                emptyChatPlaceholder: '메시지가 비었습니다.'
            ),
          );
        },
      ),
    );
  }
}



--------   rxdart bloc -----------

class ChatMessageBloc {
  final _subject = BehaviorSubject<List<Message>>.seeded([]);
  Stream<List<Message>> get stream => _subject.stream;
  List<Message> _chats = [];
  String get roomId => chatRoomId;

  String chatRoomId = '';    // initialFetch() 이후에 설정됨
  String _currentUserId = '';
  String _otherUserId = '';
  String _brightness = '';
  String _bo_table = '';
  int _wr_id = 0;

  ChatMessageBloc({this.chatRoomId=''});

  setChatRoomId(String roomId) {
    chatRoomId = roomId;
    print('chatRoomId: $chatRoomId');
    //initialFetch();
  }

  uploadImage(File file) async {
    print('----------- 이미지 업로드 시작 ------------');
    //var res = await request.multipart('https://', file: file, body: {});
  }


  Future<bool> sendMessage(Message message) async {
    // 서버업로드 이후
    /*{
      id: eda7e164-3707-4a07-a882-33fb76ad0c0e,
      text: fadsfadsfasd,
      image: null,
      video: null,
      createdAt: 1583303587536,
      user: {
        uid: bigmsg2,
        name: 냠냠냠,
        avatar: https://www.wrappixel.com/ampleadmin/assets/images/users/4.jpg,
        containerColor: null,
        color: null
      },
      quickReplies: null
    }
    */
    print('--------- in sendMessage() -----------');
    print(message.id);
    //print(message.toJson());
    //print(message.text);

    /*
      1. 로컬에 먼저 저장하기
      - interval이 언제 걸릴지 모름
      - send ---> 서버저장 이후에 interval event가 일어야나 하는데.
      - 이전 또는 서버에서 결과값을 받기전에 interval event가 발생할 수 있음
      - 폰에서 생성한 id값을  서버(chat_id)로 post함
      - 서버에서 결과 값 받으면 chat_id값으로
      2. 서버저장이후에 최근에 저장된 값을 수정
     */

    _chats.insert(0, message);
    _subject.add(_chats);


    print('create message: _bo_table: $_bo_table, _wr_id: $_wr_id');
    var js = message.toJson();


    var params = message.toJson();
    print("---- room_id: ${chatRoomId} --------");
    params['room_id']   = chatRoomId;
    //params['mb_id']  = _currentUserId;  // post cookie -> php $member['mb_id'] 값 사용
    params['other_mb_id']  = _otherUserId;
    params['bo_table']  = _bo_table;
    params['wr_id']     = _wr_id;

    print(params);
    var res = await request.post(sendMessageUrl, body: params);

    print('----------  서버 결과값 --------------');
    print(res.data);

    if(res.statusCode == 200) {

    } else {
      print('통신실패');
    }
    print('------------- send 끝 -------------');
    return true;
  }



  /*
    초기 chatRoomId의 모든 메시지 불러오기(max: 100개 or 7일전까지)
   */
  initialFetch(String currentId, {String roomId='', String otherId='', String bo_table='', int wr_id=0}) async {
    // ignore: unrelated_type_equality_checks
    if(Get.isDarkMode) {
      _brightness = 'dark';
    } else {
      _brightness = 'light';
    }

    //print('--------- initialFetch() -----------');
    chatRoomId      = roomId != '' ? roomId : chatRoomId;
    _currentUserId  = currentId;
    _otherUserId    = otherId;
    _bo_table       = bo_table;
    _wr_id          = wr_id;


    print('---------  message initial fetch --------');
    print('initialFetch _bo_table: $_bo_table, _wr_id: $_wr_id');
    print('chatRoomId: ${chatRoomId}');
    var res = await request.post(chatFetchaAllUrl, body: {
      //'brightness': _brightness,
      'chat_room_id'  : chatRoomId,
      'other_mb_id'   : _otherUserId,
      'bo_table'      : _bo_table,
      'wr_id'         : _wr_id,
    });

    print('-------- result data ---------');
    print(res.data);
    //print(res.content());

    var data = json.decode(res.data);

    if(data['chat_room_id'] == null) return Never;

    print('count: ${data['messages'].length}');

    List<Message> messages = (data['messages'] as List)
        .map((e) => types.Message.fromJson(e as Map<String, dynamic>))
        .toList();

    // _chats.add(messages);
    _chats = messages;
    _subject.add(_chats);

    /*for (var i = 0; i < data['messages'].length; i++) {
      var js = data['messages'][i];

      if (js['ch_type'] == 'text') {


      } else if (js['ch_type'] == 'image') {

      } else if (js['ch_type'] == 'template') {

      } else if (js['ch_type'] == 'video') {

      }
    }*/

    //print(js);
    /*if (js['chat_room_id'] != null) {
      chatRoomId = js['chat_room_id'];

      for (var i = 0; i < js['messages'].length; i++) {
        //print(js['messages'][i]['createdAt']);
        var msg = jsonToMessage(js['messages'][i]);
        _chats.add(msg);
      }
      //print(_chats[0].createdAt);
      _messagesSubject.add(_chats);
      //print('end initial fetch');
    } else {
      print('${_otherUserId}와 채팅한 적이 없습니다. ');
    }*/


  }

  Message jsonToMessage(Map<String, dynamic> js) {

    //var colors = getMessageColor(js['user']['uid']);
    /*var msg = Message(
        id: js['id'],
        text: js['text'],
        image: js['image'],
        video: js['video'],
        createdAt: DateTime.parse(js['createdAt']),
    );*/

    final message = types.TextMessage(
      authorId  : js['mb_id'],
      id        : js['id'],
      text      : js['text'],
      timestamp : (DateTime.now().millisecondsSinceEpoch / 1000).floor(),
    );
    //print('chatMessage: ${msg.user.containerColor}');
    return message;
  }


  /*
    일정시간 이후 계속 새 메시지 불러오기
    내가가진 마지막 메시지의 날짜 이후의 메시지를 가져오기
  */
  Future<int> intervalFetch() async {

    if (chatRoomId == null) {
      return 0;
    }

    print('----------- intervalFetch() -------------');
    // print('last: ${_chats.first}');
    if(_chats.isEmpty) return 0;

    DateTime lastDate = DateTime.fromMillisecondsSinceEpoch(_chats.first.timestamp!*1000);
    String lastDateString = DateFormat('yyyy-MM-dd H:m:s').format(lastDate);

    print('last date: ${lastDateString}');
    var res = await request.post(chatFetchUrl, body: {
      'room_id': chatRoomId,
      'last_datetime': lastDateString
    });

    var js = json.decode(res.data);
    int newMessageCount = 0;
    Message message;
    print(' interval conut: ${js.length}');
    if (js.length > 0) {
      print('hello');
      for (var i = 0; i < js.length; i++) {
        message = Message.fromJson(js[i]);
        _chats.insert(0, message);
        newMessageCount++;
      }

      _subject.add(_chats);
    }

    return newMessageCount;
  }


  /*
   * 로컬메세지에 색상 입히기
   */
  Message setMessageColor(Message message) {

    var colors = getMessageColor(_currentUserId);
    //message.user.containerColor = colors['boxColor']!;
    //message.user.color = colors['textColor']!;
    return message;
  }


  Map<String, Color>getMessageColor(String mb_id) {
    Map<String, Color> colors;
    if(!Get.isDarkMode) {
      colors = (mb_id == _currentUserId) ? {
        'boxColor': Colors.cyan,
        'textColor': Colors.black
      } : {
        'boxColor': Colors.white,
        'textColor': Colors.black
      };

    } else {
      colors = (mb_id == _currentUserId) ? {
        'boxColor': Colors.cyan,
        'textColor': Colors.black
      } : {
        'boxColor': Colors.white,
        'textColor': Colors.black
      };
    }

    return colors;
  }
}

**Comment by bigmsg** [comment]
Thank very much 😊

I found it

I have a error at special url.
www.massagemania.co.kr

but I dont know why.

other url is ok!

**Comment by demchenkoalex** [comment]
Hi @bigmsg it was indeed a bug, thanks again for reporting! Should be fixed in [v1.0.2](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.0.2) 🙂

**Comment by bigmsg** [comment]
Thank you very much 😊
I checked it. work well without meta tag "og:image".
 
I affreciate 🙏 for this bug  and Flyer chat. 
 
I want  a Template Message to has a text and button and action.
when next or next next version up, consider it please.🌈
 
 
 
-----Original Message-----

**Comment by demchenkoalex** [comment]
Thanks! We will consider creating a "custom" message type which will be rendered using a provided widget. Added to our board https://click.flyer.chat/board
