### ISSUE TITLE
Web Not Support images

### ISSUE THREAD

**Issue by ncr9108** [flyerhq/flutter_chat_ui#124]
When App Run in web ,
Images Not Showing  and can't send files.
----
might be an cors issue.
Any idea about cors set in firebase ? for web

**Comment by mingxin-yang** [comment]
Can this problem be solved?

**Comment by demchenkoalex** [comment]
it can be but you need your specific server config, Flutter docs describe this pretty well. Library just uses Image.network, where this images comes from it is library user to configure properly.

https://docs.flutter.dev/platform-integration/web/web-images
