### ISSUE TITLE
How to update text message status?

### ISSUE THREAD

**Issue by yenyichau** [flyerhq/flutter_chat_ui#130]
Hi, I would like to update the message status from sent to seen but I can't because it is final.

<img width="644" alt="Screenshot 2021-10-14 at 12 19 39 PM" src="https://user-images.githubusercontent.com/59037547/137251481-82cc247c-6df8-4d35-98c4-11e41285fc1d.png">

**Comment by yenyichau** [comment]
Im using this temporary solution to update the message status by using this step.
1) Get the message index. 
2) Remove the message according the index.
3) Recreate the message with new message status and put back to the index.

**Comment by leeyisoft** [comment]
Here's how I did it. Is there a more efficient way to do it？


eventBus.fire
`          case 'S_RECEIVED':
            MessageRepo repo = MessageRepo();
            String id = data['id'];
            int res = await repo.update({'id': id, 'status': 11});
            MessageModel? msg = await repo.find(id);
            debugPrint(">>>>> on MessageService S_RECEIVED:$res; msg:" +
                msg!.toMap().toString());
            if (res > 0 && msg != null) {
              eventBus.fire([toTypeMessage(msg)]);
            }
            break;
`

eventBus.on<List<types.Message>>().listen((e) async {
`
      _msgStreamSubs = eventBus.on<List<types.Message>>().listen((e) async {
        types.Message msg = e.first;
        int index = -1;
        for (var i = 0; i < messages.length; i++) {
          if (messages[i].id == msg.id) {
            index = i;
            break;
          }
        }
        debugPrint(">>>>> on MessageService chat_view initState:$index; " +
            msg.toJson().toString());
        if (index > -1) {
          messages.setRange(index, index + 1, e);
          setState(() {
            messages;
          });
        }
      });
`

**Comment by demchenkoalex** [comment]
I don't understand this :D are you sure you posted in a correct issue? to update the status you can just call `copyWith` on a message and get a new one, replacing it on the same index in an array.

**Comment by leeyisoft** [comment]
> 

`

> I don't understand this :D are you sure you posted in a correct issue? to update the status you can just call `copyWith` on a message and get a new one, replacing it on the same index in an array.

“My problem is that the callback modifies the message status”
I understand your logic, but I'm not familiar with Dart. Please show me your code

**Comment by demchenkoalex** [comment]
https://github.com/flyerhq/flutter_chat_ui/blob/main/example/lib/main.dart#L148 basically similar to this, but instead of `.copyWith(previewData: previewData` you `copyWith` status
