### ISSUE TITLE
How to sort msgs

### ISSUE THREAD

**Issue by jinfagang** [flyerhq/flutter_chat_ui#142]
![image](https://user-images.githubusercontent.com/21303438/139465236-44841bc2-fe58-40ea-8dfd-ab911ba0d0fd.png)

Now, as you can see, msgs can not sort by time, all msgs I sent goes top, incoming msgs goes right bottom. I don't want it, how to sort?

And how to show msg timestmp?

**Comment by demchenkoalex** [comment]
This is the discussion about time inside the message https://github.com/flyerhq/flutter_chat_ui/discussions/96 and the first question was answered, so closing this.
