### ISSUE TITLE
Possible markdown support?

### ISSUE THREAD

**Issue by demchenkoalex** [flyerhq/flutter_chat_ui#157]
### Discussed in https://github.com/flyerhq/flutter_chat_ui/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **luohao123** November 10, 2021</sup>
Just wonder if there any option to make users enable markdown support.

I noticed that there already have link support, but bold and ordered check list does't support</div>

**Comment by jinfagang** [comment]
Does there any udpates on this feature? 

I think markdown is not so hard, simple replace Text showing with MarkdownText?

After looked inside flyer, I think I am thinking too naive. seems chat bublle widget already support url touching launch function. So, it might not very easy integrate markdown support on it

**Comment by demchenkoalex** [comment]
This feature was extracted from the discussion to get more visibility for the community to implement it

**Comment by jinfagang** [comment]
Sadlly no community want implement it.

**Comment by demchenkoalex** [comment]
Then we wait :) it is all for free, so contributions are welcome, can't make everything on my own :)
