### ISSUE TITLE
Is there a way to change a specific message color?

### ISSUE THREAD

**Issue by samuel-s-marques** [flyerhq/flutter_chat_ui#160]
I want to select a message and change its color to show that it is being selected. Is there a way to do it?

**Comment by demchenkoalex** [comment]
Hey @samuel-s-marques there is no way of "easily" controlling every aspect of the lib, but you can use something like `bubbleBuilder`, copy the code of the bubble from the library and just use your colours. `selected` state can be stored in a `metadata` property which is available on all message types and it is a simple map, that can store everything.
