### ISSUE TITLE
can't I input multiple lines?

### ISSUE THREAD

**Issue by kyoungsongKim** [flyerhq/flutter_chat_ui#166]
hello.
Thank you for good codes for flutter. :)

I have one question.

I can't input multiple lines when chat

If hit the Enter key on my soft keyboard, it will be sent message.
I can't type multiple lines.

so I edited 'input.dart'

```
shortcuts: {
          LogicalKeySet(LogicalKeyboardKey.enter): const NewLineIntent(), // as-is "SendMessageIntent()"
          LogicalKeySet(LogicalKeyboardKey.enter, LogicalKeyboardKey.alt):
              const NewLineIntent(),
          LogicalKeySet(LogicalKeyboardKey.enter, LogicalKeyboardKey.shift):
              const NewLineIntent(),
        },
```
then I can input multi line input by using enter key.

How about your opinion? Can you help me about this issue?

**Comment by demchenkoalex** [comment]
Hello, is this mobile or web?

**Comment by kyoungsongKim** [comment]
this is on mobile. in case of web or emulator, I can input multiline by alt+enter or shift+enter.
It only happens on mobile

**Comment by demchenkoalex** [comment]
I will check that :)

**Comment by demchenkoalex** [comment]
Hey, so I checked both Android and iOS seem to behave properly, not sure what is happening on your side, looks like some androids might intercept those intents and some not?

https://user-images.githubusercontent.com/14123304/145643866-a86f878e-45e1-4d7f-99f5-72c25137f23e.mov

**Comment by kyoungsongKim** [comment]
In emulator, I can input multi line.
In real android machine, I can't input multi line.

https://user-images.githubusercontent.com/749517/146766741-b81f2e08-ba61-4718-829c-21938d91fea3.mp4

**Comment by demchenkoalex** [comment]
I need to add property to disable shortcuts

**Comment by demchenkoalex** [comment]
Removed shortcuts for mobile platforms (iOS and Android) in [v1.5.4](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.5.4).
