### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by Alisofin** [flyerhq/flutter_chat_ui#168]
# General

## What bug do you experience? 🐞
Provide a clear and concise description of what the bug is.

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Step 1. ...
Step 2. ... etc.

## What behavior is expected? 💡

<br />

# Extras

## Screenshots or videos 📸
If applicable, add screenshots or videos to help explain your problem.

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
// Your snippet here...
```

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: ...
flutter-chat-ui: ...

`flutter doctor -v` output 👇

```sh
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): ...

OS version (e.g. iOS 14.5, Android 11): ...

<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by Alisofin** [comment]
Hello, I have implemented your widget inside a page with other UI elements (image, TextField, ...). The space for Chat is approximatively half of the screen but when I tap the input area, I get a bottom overflow by 21 pixels and I don't have any possibility to hide the keyboard. Could you please help ?

**Comment by demchenkoalex** [comment]
Hey @Alisofin this is your setup, you need to find the solution yourself :)

1. It will be hard to replicate on my side
2. Maybe consider changing the layout? Don't see any reason having chat on half of the screen.
3. Try to change library code to see what exactly causing the problem and I can accept a PR if it will not hurt normal full screen usage.

Thanks.

**Comment by Alisofin** [comment]
Yes fair enough. But could you please confirm that there is no limitation on chat ui about using a part of the screen only ?
Cheers.

**Comment by Alisofin** [comment]
I have solved the problem by adding a SingleChildScrollView and wrapping the chat UI inside a container with a defined height.
Cheers.
