### ISSUE TITLE
Delivered and read icon on wrong user

### ISSUE THREAD

**Issue by jackiepapers** [flyerhq/flutter_chat_ui#17]
Hi, I'm wondering why the `deliveredIcon` and `readIcon` is on the other user's message. They already know the message has been delivered and read. Shouldn't those icons be on the author's message so they can see if their message was delivered and/or read?

Or maybe I'm doing something wrong but everything else is working perfectly.

**Comment by demchenkoalex** [comment]
Hi @jackiepapers. This is what we have in the example, looks correct, or am I missing something?

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-05-02 at 00 52 18](https://user-images.githubusercontent.com/14123304/116796914-b15d2580-aae0-11eb-990c-c23adc0cb0fd.png)

**Comment by jackiepapers** [comment]
Hi Alex,

It seems to me it should be the other way around. The person who sends the message should see the deliveredIcon and readIcon, so they know if their message was delivered and read.

The person receiving the message knows they have received it and they know when they have read it.

Does this make sense or am I crazy?

**Comment by demchenkoalex** [comment]
> It seems to me it should be the other way around. The person who sends the message should see the deliveredIcon and readIcon, so they know if their message was delivered and read.

That's correct, and that person is on the right side with a bluish message. So when you send something it appears on the right side and it should have statuses like sending/delivered/seen as you correctly stated. That's exactly what you can see on the screen above.

**Comment by jackiepapers** [comment]
Ahh… I’m doing something wrong then cuz my sent messages are appearing on the left.

I’ll go through the code again and try to see where I went wrong.

Thank! 

And great package btw.

**Comment by demchenkoalex** [comment]
Yes, they should be on the right. Thanks!
