### ISSUE TITLE
[BUG] When scrolling list message, it gets stuck sometimes

### ISSUE THREAD

**Issue by ralphvmo** [flyerhq/flutter_chat_ui#170]
# General

## What bug do you experience? 🐞
Provide a clear and concise description of what the bug is.

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Step 1. ...
Step 2. ... etc.

## What behavior is expected? 💡

<br />

# Extras

## Screenshots or videos 📸
If applicable, add screenshots or videos to help explain your problem.

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
// Your snippet here...
```

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: ...
flutter-chat-ui: ...

`flutter doctor -v` output 👇

```sh
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): ...

OS version (e.g. iOS 14.5, Android 11): ...

<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
There is no information whatsoever, please use the template.
