### ISSUE TITLE
How to display the first message on the screen top?

### ISSUE THREAD

**Issue by cfanboy** [flyerhq/flutter_chat_ui#177]
I found if only one message, shows on the bottom of the screen, is there any property that can modify the messages to show sequences?
Thanks
![Screen Shot 2021-12-14 at 5 14 22 PM](https://user-images.githubusercontent.com/1084020/145968752-4e7c5713-0c18-410b-9b0a-cb18b8915c19.png)

**Comment by demchenkoalex** [comment]
Hey @cfanboy this will never be implemented cause of tons of specific code that requires a reversed order, as usual in the chat apps.
