### ISSUE TITLE
Avatar should be shown first on multiple messages from the same user

### ISSUE THREAD

**Issue by itaishalom** [flyerhq/flutter_chat_ui#182]
Hi, it is more common to display the avatar close to the first message of the user (if he sends multiple messages)
and not to the last as displayed today.
What do you think?

**Comment by demchenkoalex** [comment]
Hey, sorry for the late response. Our thinking was that usually with the avatar name is enabled, and name is showed close to the top and avatar is on the bottom. So reading both ways you know the author. Don't think we will be changing that.

**Comment by itaishalom** [comment]
Do you think that i could do something easily and maybe pr you?
Is it an easy change?

**Comment by demchenkoalex** [comment]
Sure, you can make it an option, like a boolean or something :)

**Comment by itaishalom** [comment]
From your perspective, is it a difficult change?

**Comment by demchenkoalex** [comment]
Not sure, I would need to take a look

**Comment by itaishalom** [comment]
Thanks

**Comment by demchenkoalex** [comment]
Ok, so it is somewhere in the https://github.com/flyerhq/flutter_chat_ui/blob/f73eccb40b77c55297995c14a83bf71563a0920b/lib/src/util.dart#L89, specifically where we calculate all chat looks

```dart
if (showUserNames) {
      final previousMessage = isFirst ? null : messages[i + 1];

      final isFirstInGroup = notMyMessage &&
          ((message.author.id != previousMessage?.author.id) ||
              (messageHasCreatedAt &&
                  previousMessage?.createdAt != null &&
                  message.createdAt! - previousMessage!.createdAt! >
                      groupMessagesThreshold));

      if (isFirstInGroup) {
        shouldShowName = false;
        if (message.type == types.MessageType.text) {
          showName = true;
        } else {
          shouldShowName = true;
        }
      }

      if (message.type == types.MessageType.text && shouldShowName) {
        showName = true;
        shouldShowName = false;
      }
    }

    if (messageHasCreatedAt && nextMessageHasCreatedAt) {
      nextMessageDateThreshold =
          nextMessage!.createdAt! - message.createdAt! >= dateHeaderThreshold;

      nextMessageDifferentDay =
          DateTime.fromMillisecondsSinceEpoch(message.createdAt!).day !=
              DateTime.fromMillisecondsSinceEpoch(nextMessage.createdAt!).day;

      nextMessageInGroup = nextMessageSameAuthor &&
          nextMessage.createdAt! - message.createdAt! <= groupMessagesThreshold;
    }
```

and tbh I barely remember that code and don't want to touch it. Basically we look at the messages from oldest to newest and calculate when we need to show what items. And avatars were designed to be showed at the last message (in our code - when `nextMessageInGroup` is false). To do the first in the group we would need to look opposite way and it is too messy already.

I think we took at look at Messenger and Telegram and they both show avatars at the last message, so it is fine for us.

**Comment by itaishalom** [comment]
Thanks! I'll take a look at it

**Comment by demchenkoalex** [comment]
Will close this for now, since we don't plan to implement it, however PR can be opened if needed.

**Comment by KingUgochukwu** [comment]
@itaishalom Hi! I am curious if you were able to create the PR for this feature?

**Comment by itaishalom** [comment]
No, just convinced our ui ux designer to give up on it
