### ISSUE TITLE
[Link Previewer] Link Previewer Animation displays repeatedly

### ISSUE THREAD

**Issue by ralphvmo** [flyerhq/flutter_chat_ui#183]
I use StreamBuilder to get the message realtime
Whenever having message, it will display immediately.
I know that have coming message, it will handle to get preview data of link and calls set state
That's why it cause this problem
How can I solve this?
This is video that shows my issue: https://drive.google.com/file/d/1uis54jHKd5AeudHj8eBN-mLG9lXcs_V5/view?usp=sharing

**Comment by demchenkoalex** [comment]
Hey! Did you implement `onPreviewDataFetched` (see the example)? Without it properly implemented it will result in what you have right now. The purpose of that method is to update your local messages with the preview data and in the code if preview data exists, it does not fetch it again (I assume that is what's happening)

**Comment by ralphvmo** [comment]
Already use onPreviewDataFetched but It's realtime and I get data from snapshot of streambuilder. Messages are not local, they are recieved directly from stream whenever messages are coming.

**Comment by ralphvmo** [comment]
I know the root cause of this issue. Cuz, It updates the local message with preview data. But after updating, new messages coming the they replace the old messages that already have preview data. This forms a loop of updating preview data

**Comment by ralphvmo** [comment]
Is there any solution for this ?

**Comment by demchenkoalex** [comment]
It should also be updated on the remote, from where your messages come from. For example in our Firebase repo where we also have a stream of messages (https://github.com/flyerhq/flutter_firebase_chat_core/blob/main/example/lib/chat.dart) we update the message on remote when preview data is fetched, so new messages that come do contain the data and are not reloaded.

```dart
 void _handlePreviewDataFetched(
    types.TextMessage message,
    types.PreviewData previewData,
  ) {
    final updatedMessage = message.copyWith(previewData: previewData);

    FirebaseChatCore.instance.updateMessage(updatedMessage, widget.room.id);
  }
```

**Comment by ralphvmo** [comment]
Thanks for your support
