### ISSUE TITLE
What is the format of assets/messages.json to be loaded up on _loadMessages()?

### ISSUE THREAD

**Issue by rsnpj** [flyerhq/flutter_chat_ui#184]

**Comment by demchenkoalex** [comment]
Hey @rsnpj! You can find all types in this repo https://github.com/flyerhq/flutter_chat_types and the format will be a json that is parseable by our types.

Base message class (all objects in that json can have these fields) https://github.com/flyerhq/flutter_chat_types/blob/main/lib/src/message.dart

In this folder you can find all other message classes and what fields they can have https://github.com/flyerhq/flutter_chat_types/tree/main/lib/src/messages
