### ISSUE TITLE
Theme option to change input container padding

### ISSUE THREAD

**Issue by subtyven** [flyerhq/flutter_chat_ui#187]
Hello,

Is it possible to have an option to change the container padding of the input, which is located at line 160 of input.dart ?

Thanks in advance.

**Comment by subtyven** [comment]
Option for decorating the container would be cool too.

**Comment by demchenkoalex** [comment]
Added in [v1.5.4](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.5.4).

**Comment by subtyven** [comment]
thanks !
