### ISSUE TITLE
how can we change color of message?

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [flyerhq/flutter_chat_ui#192]
Hi, as chat is between two people and their message's color should be different but I am not getting how to change color as they are showing only one color for all messages.

**Comment by demchenkoalex** [comment]
Hey @UmairSaqibBhutta can you please post a screenshot? colors are different on different sides when different people are chatting. One color means it is just one person writing all of that. Can you check that your messages have different authors and you pass one of them as a chat user.
