### ISSUE TITLE
ios15 keyboard push TextField to top on Safari

### ISSUE THREAD

**Issue by jiangyubao** [flyerhq/flutter_chat_ui#201]
flutter build web under flutter 2.8.0 and deploy build/web to remote server and open it on Safari, input text and TextField on top:

![WechatIMG15804](https://user-images.githubusercontent.com/1122460/150619527-ffc79ed2-686c-4875-bf2f-a77e17f3406e.jpeg)

**Comment by demchenkoalex** [comment]
That's because of https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/input.dart#L113 I guess I can disable that on web, cause it should not really care about bottom insets.

**Comment by demchenkoalex** [comment]
Should be fixed in [v1.5.5](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.5.5).

**Comment by jiangyubao** [comment]
This bug can be reproduced by the following step:

1. Checkout and use Flutter 2.10.2 to build:
`
git clone https://github.com/flyerhq/flutter_chat_ui.git
cd flutter_chat_ui/example
flutter create .
flutter pub get
flutter build web --pwa-strategy none --release --no-source-maps --no-pub --web-renderer html 
`
2. Deploy to a remote server(for example, https://xxx.github.io/web), open URL on Safari, tap TextFiled and done (完成) button at keyboard some times and get the following result: 

<img width="446" alt="image" src="https://user-images.githubusercontent.com/1122460/156916794-70536bd0-1b95-4ab3-99a0-de845040fc9d.png">

**Comment by demchenkoalex** [comment]
I have added `final _safeAreaInsets = kIsWeb ? EdgeInsets.zero : ...` to the input, did you try the latest version? Otherwise hard to say why this is happening, there is no SafeArea for web in the app anymore. Unless PWA doesn't say it is web?
