### ISSUE TITLE
Does this lib support group chat?

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [flyerhq/flutter_chat_ui#212]
I just want to ask a question that does this lib support group chat? If supports then I could not find the main screen where all groups show?
Please guide me.

**Comment by demchenkoalex** [comment]
It is a chat screen, you build a groups screen yourself :) when you select a group you show this chat, and yes, it does support multiple users inside, with names and avatars :)

**Comment by UmairSaqibBhutta** [comment]
Thanks
