### ISSUE TITLE
Scroll chat to a particular message

### ISSUE THREAD

**Issue by arpit24sahu** [flyerhq/flutter_chat_ui#213]
## Is your feature request related to a problem?
Trying to implement a functionality to search messages based on a given keyword or phrase. it'll display a list of messages that matches the search criteria. If the user clicks on a particular search result, the chat page should highlight that particular message in chat.

## What solution would you suggest?
An option to scroll or jump to a particular message using a unique message id.

**Comment by Justus-M** [comment]
This would also be useful for the message replies feature which is currently being developed.

In virtually every popular chat app, tapping a message reply takes you to the original message. I think scrolling to a particular message could actually be a part of the message reply feature

**Comment by demchenkoalex** [comment]
I think we had this in the works somewhere in PRs, so this will be looked into. Thank you!
