### ISSUE TITLE
Option to Cache Images and Gifs

### ISSUE THREAD

**Issue by arpit24sahu** [flyerhq/flutter_chat_ui#214]
## Is your feature request related to a problem?
A poor UI experience when there are multiple high quality images in the chat and they take their time to download.

## What solution would you suggest?
Any way we can cache the images with their URL as key, so they are not loaded every time a chat page is opened.

**Comment by demchenkoalex** [comment]
Hey @arpit24sahu just use `imageMessageBuilder` and some package Flutter docs suggest https://docs.flutter.dev/cookbook/images/cached-images. There is no cache mechanism in the Flutter itself (or there is, but they do not describe that, they propose to use a package). I didn't add that package cause not everyone is using it and it has  a lot of dependencies.

**Comment by arpit24sahu** [comment]
Hey Alex. Thank you for the response. The solution you suggested worked for my case.
I have a follow up question.
On tapping the image, the image is coming to Full Screen, which is I suppose a default behavior.
How can I prevent this? I don't want the Image to go Full Screen. 
Setting the  onTap parameter of Chat  didn't help. 
Thank you.

**Comment by demchenkoalex** [comment]
`disableImageGallery` :)
