### ISSUE TITLE
Is it possible to align all messages to the left?

### ISSUE THREAD

**Issue by gradycsjohnson** [flyerhq/flutter_chat_ui#215]
While using chat in web mode short messages are spaced very far from each other. That is, your messages appear on the right, and everyone else's on the left.

![image](https://user-images.githubusercontent.com/6729256/152689661-d08f1d17-d6ae-4b6d-b7a2-3f66a1f64178.png)

I know this is normal behaviour for a chat client, but I was wondering if there was a way to align all messages to the left (or right, if that's somehow easier).

My workaround right now is to just randomize the author ID (so every message appears to be from someone else) but that means I will no longer be able to match a message with its author.

Consolation prize: is there a way to always show the author's name on a message, even if it's your own message? I can open a separate issue/question for this if you'd prefer.

Thanks!

**Comment by demchenkoalex** [comment]
Seems like an easy thing to do. Will keep open in case someone will do a PR.

**Comment by felixgabler** [comment]
One thing you should definitely do is to wrap the `Chat` widget with a size bounding widget such as `SizedBox` or `ConstrainedBox`. Then, you can make sure the chat only grows until a certain point.

However, one thing that I also had to build myself is to allow certain messages (in my case custom messages) to be center aligned. Perhaps it would be valuable to allow overriding the alignment somehow.

**Comment by lucascardo12** [comment]
Hello, I also need to align the bubble to the center in customMessageBuilder

**Comment by felixgabler** [comment]
> Hello, I also need to align the bubble to the center in customMessageBuilder

Actually, I implemented that on my fork of this repository. Perhaps I can make a pull request someday soon. @demchenkoalex what do you think about it?

**Comment by lucascardo12** [comment]
> 
I implemented your fork, which parameter do I need to change to align to the center?

**Comment by felixgabler** [comment]
> > 
> I implemented your fork, which parameter do I need to change to align to the center?
> 

You need to just work on the 'weo' branch and then they should be centered. However, it would be best to fork it yourself since I'll make changes there too. You can also just look at the changes I made and copy them.

**Comment by lucascardo12** [comment]
@felixgabler ok, it worked thank you

**Comment by dhruv1710** [comment]
Should I work on it or is it already done. If not then pls assign me this, am working on first contribution.

**Comment by demchenkoalex** [comment]
should be possible now with `v2`.
