### ISSUE TITLE
Emoji only message horizontal margin is set to zero

### ISSUE THREAD

**Issue by munkius** [flyerhq/flutter_chat_ui#216]
Hi!

Great job on the library. I was wondering why the horizontal margin is set to `0.0` for displaying an emoji-only message, and having `EmojiEnlargementBehavior.multi` enabled (by default). This makes the horizontal space skewed as opposed to giving it the room I'd expect, using the theme's configured `messageInsetsHorizontal`.

#### Current behavior
![image](https://user-images.githubusercontent.com/194593/152786248-944a1317-4bcb-40a2-8f73-f91235e683da.png)

#### Expected behavior
![image](https://user-images.githubusercontent.com/194593/152786097-fbd3061a-f352-4f1e-a6ec-0299e35085ed.png)

#### The line of code where it happens
https://github.com/flyerhq/flutter_chat_ui/blob/d299c5551c2f6e4118a8d2976a8050317e400a8e/lib/src/widgets/text_message.dart#L158

**Comment by munkius** [comment]
Anyone? :)

**Comment by demchenkoalex** [comment]
You can always open a PR if you want to speed things up. I saw it and as soon as I will be done with PRs I will check.

**Comment by munkius** [comment]
Voila!

**Comment by demchenkoalex** [comment]
Will be included in a next release - `1.5.6`. Thank you!

**Comment by munkius** [comment]
You're so welcome! Keep up the good work 💪
