### ISSUE TITLE
Error while switching chatMessages: "Looking up a deactivated widget's ancestor is unsafe."

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#220]
When I switch chatMessages and the chatMessages are replaced, I get this error in the logs.  I have narrowed it down to the Chat() object.  I tried to dig into it, but came up empty, not sure what is causing this.  Any ideas?

The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4153:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4167:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4193:12)
#3      TickerMode.getNotifier (package:flutter/src/widgets/ticker_provider.dart:96:50)
#4      SingleTickerProviderStateMixin._updateTickerModeNotifier (package:flutter/src/widgets/ticker_provider.dart:246:56)
#5      SingleTickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:199:5)
#6      new AnimationController (package:flutter/src/animation/animation_controller.dart:246:21)
#7      _LinkPreviewState._controller (package:flutter_link_previewer/src/widgets/link_preview.dart:96:48)
#8      _LinkPreviewState._controller (package:flutter_link_previewer/src/widgets/link_preview.dart)
#9      _LinkPreviewState.dispose (package:flutter_link_previewer/src/widgets/link_preview.dart:139:5)
#10     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4983:11)

**Comment by demchenkoalex** [comment]
Hey, yes, I am aware of this, and will be looking into it soon

**Comment by demchenkoalex** [comment]
waiting for the photo view to release a new version..

**Comment by fior-di-latte** [comment]
@demchenkoalex  a new version of photo_viewer was released yesterday <3

**Comment by SimonHausdorf** [comment]
can we get that fixed please?

**Comment by demchenkoalex** [comment]
updated in the Flutter 3 version.
