### ISSUE TITLE
ImageMessage Uri Headers

### ISSUE THREAD

**Issue by michaelsoliman1** [flyerhq/flutter_chat_ui#224]
## Is your feature request related to a problem?
cannot get network images that needs authentication because i cannot add headers to the url

## What solution would you suggest?
Adding Url Headers parameter to be added to the uri to download authenticated images

Thanks!

**Comment by demchenkoalex** [comment]
Will gladly accept a PR, thank you!

**Comment by Lawliet18** [comment]
@michaelsoliman1 
You can use imageMessageBuilder in the Chat class 
```
imageMessageBuilder: (
      imageMessage, {
      required int messageWidth,
}) {
   return Image.network(
       imageMessage.uri,
       width: messageWidth.toDouble(),
       headers: {
          HttpHeaders.authorizationHeader: 'token',
       },
  );

**Comment by michaelsoliman1** [comment]
> @michaelsoliman1 You can use imageMessageBuilder in the Chat class
> 
> ```
> imageMessageBuilder: (
>       imageMessage, {
>       required int messageWidth,
> }) {
>    return Image.network(
>        imageMessage.uri,
>        width: messageWidth.toDouble(),
>        headers: {
>           HttpHeaders.authorizationHeader: 'token',
>        },
>   );
> ```

@Lawliet18 This will work, Thanks!

**Comment by demchenkoalex** [comment]
Also added `imageHeaders` to the `Chat` now, but it will pass headers to all `NetworkImage`s. Hopefully that is fine.
