### ISSUE TITLE
How can we show date and time with messages?

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [flyerhq/flutter_chat_ui#228]
Hi! I have noticed that date and time are not showing in the chat. `Message `receiving `createdAt` parameter but not showing any date according to the day difference or any thing else.
If there is any way please give any hint...

**Comment by demchenkoalex** [comment]
You mean near a particular message? We opted in Facebook Messenger way where date & time go to headers, and they will appear every new day as well as if time between 2 messages are more than 15 minutes, so you can get the idea when messages were received. We have a request for this feature somewhere, and someday we will do it, right now - you can't. Tagged your issue in the discussions about this feature, to cleanup when we do it.

**Comment by herman-the-worm** [comment]
@demchenkoalex is there any way to override this behaviour to show timestamps for all messages? (legacy mode)

**Comment by demchenkoalex** [comment]
No I don't think so, currently it is working as Facebook Messenger. Something to be looked at in v2 (create more date displaying modes)
