### ISSUE TITLE
How can we get message text from long press on Message?

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [flyerhq/flutter_chat_ui#229]
I want to add the feature of forward message. I want to show forward dialogue on long press on the message.
But how can I get message text?

**Comment by leeyisoft** [comment]
https://github.com/imboy-pub/imboy-flutter/blob/main/lib/page/chat/chat_view.dart line 590
          onMessageDoubleTap: _onMessageDoubleTap,

**Comment by UmairSaqibBhutta** [comment]
@leeyisoft Thank You so much!
