### ISSUE TITLE
chat background

### ISSUE THREAD

**Issue by DerekDekker** [flyerhq/flutter_chat_ui#235]
Is it possible to add chat background

**Comment by louislamme** [comment]
This can be easily done by wrapping the StreamBuilder with Stack widget.

`Stack(children: [
        Image.asset(
          BackgroundImage,
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          fit: BoxFit.cover,
        ),
StreamBuilder<types.Room> ....
])`

**Comment by demchenkoalex** [comment]
Does this answer your question @DerekDekker? did you try wrapping Chat widget with a Stack?
