### ISSUE TITLE
How to make text not selectable ?

### ISSUE THREAD

**Issue by AdrKacz** [flyerhq/flutter_chat_ui#241]
Hello 👋 

Thank you very much for this framework! I use it with Flutter.

I looked inside the *pub.dev* documentation to find how to make **text** in `MessageText` **not selectable**, but I didn't find anything.

I need that because selecting the text enter in collision with tapping or pressing the message.

If the answer is in the documentation and I didn't succeed to find it, redirect me.

**Comment by demchenkoalex** [comment]
Hi! I have added `isTextMessageTextSelectable` in the new `1.5.6` version (will release it today). Thanks!

**Comment by AdrKacz** [comment]
Super thank you! 🙏
