### ISSUE TITLE
Full Screen Margin Error on Landscape mode

### ISSUE THREAD

**Issue by AdrKacz** [flyerhq/flutter_chat_ui#251]
# General

## What bug do you experience? 🐞
When you turn your phone in landscape mode on new iPhones (with not rectangular screens), there are two uncoloured bands on the left and right sides.

## How can it be reproduced? 🤔
Create a `Chat`, use an *iPhone* (I didn't test it with Android, may have the same issue), and turn it to *landscape* mode.

## What behavior is expected? 💡
The `Chat` should extends to the *width's screen* as it does in *portrait* mode.

<br />

# Extras

### Landscape, *2 bands right and left* (screenshot taken on iPhone 13 mini)

> [May be useful] On the right side, there is the iPhone camera, so I don't see *all* the right band, just the up and down parts.

![IMG_0827](https://user-images.githubusercontent.com/61620013/162911825-0706c094-9ecc-4671-854b-5a845f029957.PNG)

### Portrait, *nothing right and left* (screenshot taken on iPhone 13 mini)
![IMG_0828](https://user-images.githubusercontent.com/61620013/162911834-5f24ca43-d16d-4e52-9856-d1b66cf72d8f.PNG)

## Code snippets 📝

Just a `Chat` widget within `Scaffold` with an `AppBar`. Below the implementation of the `Chat` just in case.

```dart
Chat(
    showUserNames: true,
    showUserAvatars: true,
    isTextMessageTextSelectable: false,
    l10n: const ChatL10nFr(),
    messages: _messages,
    onSendPressed: sendMessage,
    onMessageLongPress: reportMessage,
    user: types.User(
        id: User().id,
        imageUrl:
            "https://avatars.dicebear.com/api/croodles-neutral/${User().id}.png"),
    theme: const DefaultChatTheme(
        inputBackgroundColor: Color(0xfff5f5f7),
        inputTextColor: Color(0xff1f1c38),
        inputTextCursorColor: Color(0xff9e9cab)),
  );
```

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

```sh
$ flutter --version
Flutter 2.10.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c860cba910 (3 weeks ago) • 2022-03-25 00:23:12 -0500
Engine • revision 57d3bac3dd
Tools • Dart 2.16.2 • DevTools 2.9.2
```

flutter-chat-ui: **1.5.6** *(I don't remember the same issue with **1.5.5** but I may be wrong)*

`flutter doctor -v` output 👇

```sh
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3.1 21E258 darwin-x64, locale en-GB)
    • Flutter version 2.10.4 at /Users/adrkacz/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (3 weeks ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/adrkacz/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/adrkacz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.66.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (2 available)
    • iPhone 13 mini (mobile) • 00008110-000C3DE61A78801E • ios            • iOS 15.4.1 19E258
    • Chrome (web)            • chrome                    • web-javascript • Google Chrome 100.0.4896.75

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): iPhone 13 mini (**not** emulated, *not tested on an emulated device*)

OS version (e.g. iOS 14.5, Android 11): **iOS 15.4.1**

<br />

Thank you for your superb framework 🤝

**Comment by demchenkoalex** [comment]
Pushed a fix, will be released in the next version `1.5.8` today. You will need to remove `SafeArea` wrapper around Chat itself, I have included safe area insets inside the library.
