### ISSUE TITLE
PreviewData  not working properly on web.

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#252]
When a message is loaded on the web that doesn't have previewData saved, and the onPreviewDataFetched is called on that link.  The previewData only has "link" and not the description/image/title that the same message receives on mobile.

**Comment by demchenkoalex** [comment]
Because of CORS? Link preview is done on a client side, if you want a real link preview working on web, you need backend side, something like https://www.linkpreview.net, nothing I can do here unfortunately.

**Comment by T-P-F** [comment]
@demchenkoalex thanks for your reply above and for FlyerChat generally. 

In order to use a service like linkpreview... I don't see that it is possible today to pass a 'previewDataProvider' to Chat, is the best practice to treat messages with links as custom and use a custom builder that calls linkpreview?

**Comment by demchenkoalex** [comment]
@T-P-F currently working on a full v2 re-design of the package, will make sure to make it work with 3rd party services in v2. In v1 though I think you will have to either fork it or use custom message to get it to work.

**Comment by T-P-F** [comment]
@demchenkoalex got it, thanks for the reply. Do you have a timeline for the v2? If its weeks away I'll just wait, otherwise I'll probably go the custom message route.

**Comment by demchenkoalex** [comment]
@T-P-F no definitely not weeks away, I am still figuring out the best architecture for the long run
