### ISSUE TITLE
Press Enter does not break that particular line but line break at the end of text.

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [flyerhq/flutter_chat_ui#258]
When I press Enter, that particular line should break but instead of that, the line break is at the end of all text.
This issue occurs in emulator and web.

**Comment by demchenkoalex** [comment]
Wasn't able to reproduce, need exact steps.

**Comment by UmairSaqibBhutta** [comment]
https://user-images.githubusercontent.com/58905159/178664295-966062fe-586a-450b-a61c-b0e61c89ea9f.mp4

please check this

**Comment by demchenkoalex** [comment]
video is broken @UmairSaqibBhutta, can't open

**Comment by UmairSaqibBhutta** [comment]
video is right. Please check again or download it.

**Comment by demchenkoalex** [comment]
Will be included in `v1.6.4`
