### ISSUE TITLE
Go to the back screen if image is opened in chat and back button is pressed.

### ISSUE THREAD

**Issue by UmairSaqibBhutta** [flyerhq/flutter_chat_ui#259]
When I open the image in full view and press the back button then the image should be closed but the screen i.e. chat screen, should be remained in view. But on the back press image is closed and `navigator.pop(context)` is also done.
Please any solution or suggestion?

**Comment by UmairSaqibBhutta** [comment]
Where to add this code?

**Comment by UmairSaqibBhutta** [comment]
@demchenkoalex bro issue closed but not resolved.

**Comment by demchenkoalex** [comment]
You did wrote "this function was already added" - what this means? Also some PR was referencing this.

**Comment by UmairSaqibBhutta** [comment]
Someone said to add function that was already added but the issue is same.

**Comment by demchenkoalex** [comment]
Will be included in `v1.6.4`
