### ISSUE TITLE
Feature Request - Replied to snippet

### ISSUE THREAD

**Issue by jlubeck** [flyerhq/flutter_chat_ui#26]
It is a normal use case to reply directly to a specific message, when this happens, it usually displays a snippet of the old message to give context.

Examples:
Telegram:
![IMG_6649](https://user-images.githubusercontent.com/3067603/118905553-eee7ee00-b8e9-11eb-9c57-6be4efd45986.jpg)

Whatsapp:
![IMG_6651](https://user-images.githubusercontent.com/3067603/118905547-ec859400-b8e9-11eb-9c2a-d436297bf70a.jpg)

**Comment by dariakhimych** [comment]
You're right @jlubeck, this is a nice feature to have in chats. And we already have it listed in our backlog 🤘

**Comment by jlubeck** [comment]
> You're right @jlubeck, this is a nice feature to have in chats. And we already have it listed in our backlog 🤘

Nice!

**Comment by jlubeck** [comment]
> You're right @jlubeck, this is a nice feature to have in chats. And we already have it listed in our backlog 🤘

I think I saw your public backlog somewhere but can't seem to find it... unless I'm thinking about another project. If you DO have it, would you mind adding it to the README.md ? Thanks!

**Comment by demchenkoalex** [comment]
Hey @jlubeck it is here https://click.flyer.chat/board but we are exploring use of GitHub instead of Notion ATM. We are not sure yet what we will pick. We will add this to the README when ready.

**Comment by jlubeck** [comment]
Thank you @demchenkoalex would definitely be awesome for the community to have everything in one place, but of course, it's your project 😄  Thank you for the link!

**Comment by jlubeck** [comment]
Hopefully this issue can be prioritized now that we left 1.1 behind? 😅 🙏 
I think it's the only missing link to have a somewhat full chat experience on a large group

**Comment by demchenkoalex** [comment]
We will see, right now React Native is a priority, it was left behind, so I will resolve small issues here until RN is done. Then we will continue with somewhat "big" features. But again PRs are welcome :) if needed, we can provide designs/UX for this feature here, so maybe somebody can take it.

**Comment by jlubeck** [comment]
> We will see, right now React Native is a priority, it was left behind, so I will resolve small issues here until RN is done. Then we will continue with somewhat "big" features. But again PRs are welcome :) if needed, we can provide designs/UX for this feature here, so maybe somebody can take it.

YES!! If you can provide design, I'm more than happy to try making a PR

**Comment by demchenkoalex** [comment]
@dariakhimych your turn :)

**Comment by jlubeck** [comment]
@dariakhimych we are all counting on your blessings! (plus I can't code without designs :( )

**Comment by dariakhimych** [comment]
Hey @jlubeck 👋 Happy to share the brief where you will find some of Flyer design principles and guidelines as per how to better implement the Reply feature. In case of any questions do not hesitate to text me on Telegram. 

[Flyer Chat - Reply to a Message [Feature Brief].pdf](https://github.com/flyerhq/flutter_chat_ui/files/6726609/Flyer.Chat.-.Reply.to.a.Message.Feature.Brief.pdf)

**Comment by jlubeck** [comment]
Thank you for that @dariakhimych it's looking great! Only concern I have is if the X button on the reply is not too close to the send button of the input text?

**Comment by dariakhimych** [comment]
@jlubeck Please make sure you set a touch area for both at 40 points (required minimum) and they should be fine.
