### ISSUE TITLE
Flutter 3.0 upgrade error from visibility_detector package.

### ISSUE THREAD

**Issue by adar2378** [flyerhq/flutter_chat_ui#266]
# General

## What bug do you experience? 🐞
While building receiving errors from visibility_detector package. Looks like they have fixed and updated the version. This repo should also update the version for visiblity_detector.

`pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visi
bility_detector_layer.dart:193:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding'
which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
 ('../../../../flutter_1.17/flutter_17/packages/flutter/lib/src/scheduler/binding.dart').
    SchedulerBinding.instance!`

## How can it be reproduced? 🤔
Just run `flutter run` to the example after updating to Flutter 3.0

## What behavior is expected? 💡
The warnings should not be shown.

<br />

**Comment by Peterkrol12** [comment]
I got the same errors as mentioned above, but after running `dart fix --apply`, as suggested in [this comment from a Flutter dev](https://github.com/flutter/flutter/issues/103561#issuecomment-1124682721), the errors went away.

**Comment by felixgabler** [comment]
This is only a warning and will be fixed once a new version with Flutter 3 updates is released. You can ignore the warning until then.
