### ISSUE TITLE
Chat screen background image

### ISSUE THREAD

**Issue by sinapsis793** [flyerhq/flutter_chat_ui#270]
How can I add background image for chat ui?

**Comment by DikshaCT27** [comment]
` Container(
          height: double.infinity,
          width: double.infinity,
          decoration: const BoxDecoration(
            image: DecorationImage(
              image: AssetImage(Commons.assetPath + 'chatBg.png'),
              fit: BoxFit.cover,
            ),
          ),
          child: SafeArea(
            child: StreamBuilder<types.Room>(
                initialData: widget.room,
                stream: FirebaseChatCore.instance.room(widget.room.id),
                builder: (context, snapshot) {
                  return StreamBuilder<List<types.Message>>(
                      initialData: const [],
                      stream:
                          FirebaseChatCore.instance.messages(snapshot.data!),
                      builder: (context, snapshot) {
                        return Chat()})}))`
                        
                        
![1657168311442](https://user-images.githubusercontent.com/85980088/177708783-570568b1-9048-4da4-b2e5-fa09550f4a14.JPEG)
### You can add an image background like this to your chat screen.

**Comment by sinapsis793** [comment]
Thank you so much. I will try it.

**Comment by demchenkoalex** [comment]
Thanks guys! I think it might be closed now, feel free to reply if not.

**Comment by whisperrrr** [comment]
Also can try with this:
```
Stack(
  children: [
       const SizedBox.expand(child: ColoredBox(color: Colors.gray)),  // customize background color
       ImageView(...) // config background image widget here,
       Chat(
         theme: const DefaultChatTheme(backgroundColor: Colors.transparent), // [important] set background color for chat to transparent
       ),
  ]
)
```

**Comment by EzizAnnagurbanow** [comment]
> theme: const DefaultChatTheme(backgroundColor: Colors.transparent),

Thank you man!
