### ISSUE TITLE
How to disable default image viewer?

### ISSUE THREAD

**Issue by Yahllil** [flyerhq/flutter_chat_ui#272]
Hello,
I have implemented my own image viewer for `types.ImageMessage`'s tap using `onMessageTap`. But how can I prevent the appearance of the default image viewer of the chat? Because currently I'm presenting my custom image viewer, and then when it gets dismissed the user sees the package's default image viewer.

Thank you :)

**Comment by demchenkoalex** [comment]
`disableImageGallery` :)
