### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by malikdoksoz** [flyerhq/flutter_chat_ui#279]
flutter_chat_ui: ^1.6.1

![Ekran Resmi 2022-06-16 17 44 05](https://user-images.githubusercontent.com/26676061/174096073-a0e067ba-a1ce-4ad8-8e8d-61ce9d5f6c1e.png)

The named parameter **'previewData' isn't defined.**
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'previewData'.

Sample codes should be updated for the new version

**Comment by demchenkoalex** [comment]
Hey! Where did you find it? Cause I remember updating everything

**Comment by malikdoksoz** [comment]
https://github.com/flyerhq/flutter_chat_ui/blob/main/example/lib/main.dart#L149,L157
