### ISSUE TITLE
Set chat's keyboardDismissBehavior

### ISSUE THREAD

**Issue by Yahllil** [flyerhq/flutter_chat_ui#280]
Hello!

Is there an option currently to set the chat's scroll's `keyboardDismissBehavior` to `auto` (like WhatsApp for example)? Or at least for `onDrag` so the keyboard will be dismissible?

**Comment by demchenkoalex** [comment]
Hi!

What is `auto`? I don't see it in the documentation and code completion. I am waiting for so long for Flutter team to add a proper interactive keyboard dismiss on iOS, but no luck. As for the `drag`, you will not be able to scroll history keeping the input open (which I want to keep). `Interactive` would be best, but it is not available on Flutter AFAIK.

**Comment by Yahllil** [comment]
> Hi!
> 
> What is `auto`? I don't see it in the documentation and code completion. I am waiting for so long for Flutter team to add a proper interactive keyboard dismiss on iOS, but no luck. As for the `drag`, you will not be able to scroll history keeping the input open (which I want to keep). `Interactive` would be best, but it is not available on Flutter AFAIK.

@demchenkoalex You are right, Flutter doesn't support `interactive` yet. But you can use [this](https://pub.dev/packages/flutter_interactive_keyboard) package, which works great! I think it'll be a very big and useful addition to the package

**Comment by demchenkoalex** [comment]
Sorry can't add something that is not updated for years. We will need to wait for Flutter team to add it.

**Comment by Yahllil** [comment]
@demchenkoalex Thanks for the answer. I get your point regarding the updates frequency of this package. I guess we'll have to wait for an official `interactive` support from the Flutter team.

In the meantime. I believe adding an option to set `keyboardDismissBehavior` to `onDrag` is appropriate, for chats screens that are not presented inside the navigation stack (in a tab bar for example).
Without the keyboard dismiss on drag, and unless there is a "dismiss" button in the UI, the user has no way to dismiss the keyboard and to access the tab bar.

I've currently implemented this in my app using `GestureDetector`, but think it would be appropriate to add this option to the package itself.

What do you think?

**Comment by demchenkoalex** [comment]
@Yahllil tapping outside the keyboard closing the keyboard, so there is a way. I described `drag` issues before. But I will add a customisation option for people to choose themselves. Will reply here when added and released.

**Comment by demchenkoalex** [comment]
Will be included in `v1.6.4`
