### ISSUE TITLE
How to prevent chat rebuild when adding new messages?

### ISSUE THREAD

**Issue by pinguluk** [flyerhq/flutter_chat_ui#287]
I have a customMessageBuilder, that's used to build video messages. The problem is that when I add a new message, the entire page/chat is being rebuilt, therefore my custom video player messages are being rebuilt as well

![image](https://user-images.githubusercontent.com/16257821/176899687-eb4c0490-82f8-4a06-8a55-7b2c70994dd2.png)

https://user-images.githubusercontent.com/16257821/176899647-c07df75a-8686-4019-81aa-2b35d5cd85ae.mp4

**Comment by demchenkoalex** [comment]
Hi! I don't think this is possible. We didn't yet look at the video messages official support (not through custom builder) but I think this will be a lot of pain. Back in the day when I had just a scroll view and a text, I noticed when I added new messages all visible messages were rebuilt. If you will open this example https://api.flutter.dev/flutter/widgets/AnimatedList-class.html and add `print('BUILD');` on the line 36, you will see BUILD 3 times (3 elements are present by default in the example) and when you add one you will see BUILD 4 times (3 old + 1 new). I googled solutions, but the only thing people were suggesting is to provide some arguments like cache 10000 or something, but it kills virtualisation, meaning all items will be in memory and it would just kill most of the phones. So I am hoping there are some things can be done when working with video to keep it at the same place even after rebuild.

**Comment by pinguluk** [comment]
> Hi! I don't think this is possible. We didn't yet look at the video messages official support (not through custom builder) but I think this will be a lot of pain. Back in the day when I had just a scroll view and a text, I noticed when I added new messages all visible messages were rebuilt. If you will open this example https://api.flutter.dev/flutter/widgets/AnimatedList-class.html and add `print('BUILD');` on the line 36, you will see BUILD 3 times (3 elements are present by default in the example) and when you add one you will see BUILD 4 times (3 old + 1 new). I googled solutions, but the only thing people were suggesting is to provide some arguments like cache 10000 or something, but it kills virtualisation, meaning all items will be in memory and it would just kill most of the phones. So I am hoping there are some things can be done when working with video to keep it at the same place even after rebuild.

Why not use a ListView.builder? The elements outside the view doesn't affect the performance and they aren't rebuilt when adding new items. I think you could paginate the list/messages, so when entering the chat, it will only load the last messages and load other messages, as you scroll back up 🤔

**Comment by demchenkoalex** [comment]
No animations. Chat is looking decent mainly because of animations, and messages will just appear out of nowhere when using usual ListView.

**Comment by Rejomeee** [comment]
use a state management then wrap your Chat() inside a blocBuilder.

**Comment by demchenkoalex** [comment]
Should be working now I guess (on main)

**Comment by demchenkoalex** [comment]
https://user-images.githubusercontent.com/14123304/183243032-91c207a0-2c88-4b14-a165-ed4b48399218.mov

**Comment by demchenkoalex** [comment]
sorry I missed the message. yes, this was broken - fixed in `v2.9.2`. Example:

https://github.com/user-attachments/assets/552d5682-84b0-4506-8b3d-3c9733a9f212
