### ISSUE TITLE
No status onvisibilty change 

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [flyerhq/flutter_chat_ui#300]
Hey i want to show no status of the message onMessageVisibilityChanges  how can i do that
 like 

<img width="378" alt="image" src="https://user-images.githubusercontent.com/88256165/182551140-911047af-9f33-4dab-84e4-a5d8e8d4f2a4.png">

currently  im getting like this and i want something like this 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/88256165/182551340-ed0b2c73-f029-43b0-b6d5-af1c1421d11f.png">

you can clearly see that im getting status in all the messages in the above image whereas in below image status is showing only in the last message sent by the user.

**Comment by demchenkoalex** [comment]
Hey! I don't know why you mention `onMessageVisibilityChanged` it has nothing to do with statuses. Messages have `showStatus` field, you can pass `false` to not render a status.

<img width="421" alt="Screenshot 2022-08-03 at 11 27 02" src="https://user-images.githubusercontent.com/14123304/182574372-02726cd7-4a68-451d-a161-7b3a58dba2d1.png">

**Comment by Yogesh-Dubey-Ayesavi** [comment]
i solved my problem yesterday only 
<img width="395" alt="image" src="https://user-images.githubusercontent.com/88256165/182904068-a56a9de6-435f-48f7-8e78-21e14f71493b.png">
i was saying that i wanted to show status at only the last message when sent in group at a time.
