### ISSUE TITLE
Reply to a particular message 

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [flyerhq/flutter_chat_ui#302]
Well i wanted to implement a feature of replying a particular message onDoubleTap how can i implement that ?

**Comment by demchenkoalex** [comment]
Reply to a message is in the works. It will be swipe to reply though (like every modern chat now), double tap is not planned. Will close as a duplicate for now, you can follow releases, it will be a major one when this lands.

**Comment by Yogesh-Dubey-Ayesavi** [comment]
ok so when it is expected to arrive could you tell please ?

**Comment by demchenkoalex** [comment]
no timelines, this is a free open-source project, working on weekends when I feel like working. [PR](https://github.com/flyerhq/flutter_chat_ui/pull/256) is there I just need to refactor everything and update with the latest chat code.

**Comment by Yogesh-Dubey-Ayesavi** [comment]
ok i have made my own implementation 😀

**Comment by zamirszn** [comment]
> @Yogesh-Dubey-Ayesavi, would you mind sharing your **`Reply to a particular message`** implementation?

Hello, we you able to get it from him?

**Comment by zamirszn** [comment]
> ok i have made my own implementation 😀

hello @Yogesh-Dubey-Ayesavi can you help me with it please ?
