### ISSUE TITLE
Updating Messages.

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [flyerhq/flutter_chat_ui#307]
First of all great library no doubt, actually  I am having a doubt I wanted  to update message status property with respective states of Status 
what is the ideal approach to do that one way I thought was to copy the message older properties then change status just and insert it at the particular index I think that's  why the copyWith method was intended to please help

**Comment by demchenkoalex** [comment]
Exactly as you say. Example we have in the example project, used to update FileMessage's loading state when you load a file:

```dart
final index = _messages.indexWhere((element) => element.id == message.id);
final updatedMessage = (_messages[index] as types.FileMessage).copyWith(
  isLoading: true,
);

setState(() {
  _messages[index] = updatedMessage;
});
```
