### ISSUE TITLE
I can not  get data from user in firebase 

### ISSUE THREAD

**Issue by Vannak1111** [flyerhq/flutter_chat_ui#309]
![Screen Shot 2022-08-24 at 2 47 32 PM](https://user-images.githubusercontent.com/95061289/186363593-2ceb1091-6e72-477d-b408-2806bde3c419.png)

**Comment by demchenkoalex** [comment]
Is it the example project? Did you follow README and did you create the Firebase project? Do you have any data? You know having a screenshot tells nothing :)
