### ISSUE TITLE
hours and minutes time in textMessage

### ISSUE THREAD

**Issue by sebaszap123-dev** [flyerhq/flutter_chat_ui#314]
## Request
make a implement for TextMessage Widget than users can decide if showTime in their textMessage Widget. My Idea is to be similar than other social chats used actuallyke 
## How to implement?
- Maybe add a function that formatted the createdAt property of a message with a     DateTime.fromMillisecondsSinceEpoch(millisecondsSinceEpoch)
- But this feature if the user want to set to true needs to have alway a createdAt value
- User need to be sure for always get the Int for it message

## Code that maybe helps
I'm was implement a class for flutter with somepackages that could help for formatted hours and minutes taking a timezone for avoid have problems with it.
But if your backend gives you the Int stamp correctly maybe you don´t need this

**Code snippets 📝**
If applicable, add code samples to help explain your feature.

```dart
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;
import 'package:timezone/timezone.dart';

const locationMexico = 'America/Mexico_City';
const serverLocation = 'America/Mexico_City';

class TimeStamps {
  TimeStamps({required this.dateTime});
  TZDateTime dateTime;
  factory TimeStamps.fromTimeStamp(int timeStamp) {
    tz.initializeTimeZones();
    // * Implement this with other timezones also
    final pacificTimeZone = tz.getLocation(serverLocation);
    return TimeStamps(
      dateTime:
          TZDateTime.fromMillisecondsSinceEpoch(pacificTimeZone, timeStamp),
    );
  }
  factory TimeStamps.now() {
    tz.initializeTimeZones();
    // * Implement this with other timezones also
    final pacificTimeZone = tz.getLocation(serverLocation);
    return TimeStamps(
      dateTime: TZDateTime.now(pacificTimeZone),
    );
  }
  factory TimeStamps.fromString(String value) {
    final pacificTimeZone = tz.getLocation(serverLocation);
    final time = TZDateTime.parse(pacificTimeZone, value);
    return TimeStamps(dateTime: time);
  }
  String getDate() {
    String day = '';
    String month = '';
    final pacificTimeZone = tz.getLocation(serverLocation);
    final timeNow = TZDateTime.now(pacificTimeZone);
    if (dateTime.day < 9) {
      day = '0${dateTime.day}';
    } else {
      day = "${dateTime.day}";
    }
    if (dateTime.month < 9) {
      month = '0${dateTime.month}';
    } else {
      month = "${dateTime.month}";
    }
    if (timeNow.day <= dateTime.day) {
      return getTimeAmPm();
    } else {
      String dateFormat = day + "/" + month + "/" + dateTime.year.toString();
      return dateFormat;
    }
  }

  String getTime() {
    tz.initializeTimeZones();
    final pacificTimeZone = tz.getLocation(serverLocation);
    final formatted = tz.TZDateTime.from(dateTime, pacificTimeZone);
    String minutes = '';
    if (formatted.minute < 9) {
      minutes = '0$formatted';
    } else {
      minutes = "${formatted.minute}";
    }
    return '${formatted.hour}:$minutes';
  }

  String getTimeAmPm() {
    String meridiano = 'AM';
    tz.initializeTimeZones();
    final pacificTimeZone = tz.getLocation(serverLocation);
    final formatted = tz.TZDateTime.from(dateTime, pacificTimeZone);
    String minutes = '';
    if (formatted.minute < 9) {
      minutes = '0${formatted.minute}';
    } else {
      minutes = "${formatted.minute}";
    }
    if (formatted.hour > 12) {
      meridiano = 'PM';
    }
    return '${formatted.hour}:$minutes $meridiano';
  }

  int getStamp() {
    return dateTime.millisecondsSinceEpoch;
  }
}
```
## Can I try it?
I want to try to implement this feature for the package, it could be very interesting and exciting
## Related issues/PRs
No related

**Comment by demchenkoalex** [comment]
Hello! I had this originally, but was forced to remove it due to the problems with bubble animations. I need to rethink how bubbles are being animated, which will require mega refactor, hence I do no add this feature even though it is highly requested. This will be the first thing I will add when animation problem is gone (currently messages are being animated automatically, after diffs are being calculated for the messages array, but I need to do it manually somehow where I will have complete control over messages).

**Comment by marinkobabic** [comment]
Date and time has anyway to be on top of every message, not only textmessage and like stated here, configurable.

**Comment by aelahmar** [comment]
Hi there, any update on this feature ?

**Comment by demchenkoalex** [comment]
will go to v2 cause I am not working actively on a current implementation - will be in the backlog for v2 (I will open a new issue soon that will track overall progress)

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/96 - will be picking tasks from Discussions.
