### ISSUE TITLE
Chat list padding

### ISSUE THREAD

**Issue by jld3103** [flyerhq/flutter_chat_ui#315]
# General

## What bug do you experience? 🐞
The chat shows a bar at the top which I can not control. See the first picture in https://github.com/flyerhq/flutter_chat_ui/issues/73.

## How can it be reproduced? 🤔
Wrap a `Chat` using a `Scaffold` that also has an `AppBar`. The bar becomes visible directly below the `AppBar`.

## What behavior is expected? 💡
The padding should not be there by default and it should be possible to control it from outside the package.

<br />

# Extras

## Screenshots or videos 📸
See linked issue.

<br />

# Environment info

flutter: 3.3.1
flutter-chat-ui: 1.6.4

<br />

# Platform

This affects all platforms

<br />

# Additional context

https://github.com/flyerhq/flutter_chat_ui/blob/802a41f1b52f38808e8bd9e7d83c40a180c3ea5b/lib/src/widgets/chat_list.dart#L154-L157 is the code that introduces the bar.

The problem was already reported in https://github.com/flyerhq/flutter_chat_ui/issues/73, but never mentioned again in that issue and it got closed. I figured it's best to open a new issue rather than bumping an old closed issue that is mostly about a different problem.

**Comment by demchenkoalex** [comment]
Will close this in favour of #321.

**Comment by jld3103** [comment]
Sorry this is not the same. I mean a padding at the top of the chat list. I'll send a screenshot to show what I mean. Please re-open.

**Comment by demchenkoalex** [comment]
That's what I thought, I don't need a screenshot :) I misunderstood the other one haha

**Comment by jld3103** [comment]
np

**Comment by jld3103** [comment]
Good to see some activity in this repo again!

**Comment by demchenkoalex** [comment]
activity will come and go unfortunately, sometimes I have harder times at work and have zero desire working on weekends, I did not know what I'm getting myself into when I started this 2 years ago :D

**Comment by demchenkoalex** [comment]
Honestly, can't repro given provided steps, but I imagine some situations where top safe area inset will not be wanted, so I just added a param `useTopSafeAreaInset` to the `Chat`. By default enabled on mobile platforms. Will be in a next release live this weekend.

**Comment by jld3103** [comment]
Thx a lot :)
