### ISSUE TITLE
Bubble animation

### ISSUE THREAD

**Issue by mohamoha6200** [flyerhq/flutter_chat_ui#318]
Hello , thank you for this awesome project/package.
If you would allow me to request a feature, I noticed you're already using AnimatedList for the chat, wouldn't it be cool if we could have the possibility to add an animation to the message bubble appearing after adding a message to the chat area ? a fade/slide/scale animation with a certain duration kind of control would be nice to have don't you think ? 
Thank you.

**Comment by henry2man** [comment]
Have you tried to create a custom, animated bubble using `Chat.bubbleBuilder`?

**Comment by mohamoha6200** [comment]
> Have you tried to create a custom, animated bubble using `Chat.bubbleBuilder`?

I haven't at first but I now I just did and managed to achieve the desired behavior, thanks for the eye opener and the awesome package :)

**Comment by demchenkoalex** [comment]
Sorry just got back. Hmm, I thought we do have an animation? That's why I wanted `AnimatedList` in the first place.. 
![Screen Recording 2022-10-03 at 00 02 55](https://user-images.githubusercontent.com/14123304/193478287-bc5a41c7-fca1-462b-be27-52f0d82554e6.gif)

**Comment by mohamoha6200** [comment]
Yeah the out of the box one isnt bad, I just wanted to add a touch to it
and could customize it successfully following the comment above.

**Comment by demchenkoalex** [comment]
well I will gladly accept your "touch" as a PR :) Animation is like this because I did not find anything better than `SizeTransition`.. sometimes I miss native iOS development. If you're master in Flutter animations you can totally improve this and everyone will benefit from it.

**Comment by demchenkoalex** [comment]
full customisation should be possible now with `v2`.
