### ISSUE TITLE
NetworkImage headers support

### ISSUE THREAD

**Issue by marinkobabic** [flyerhq/flutter_chat_ui#326]
ImageGalleryOptions should add a new property headers so that headers for the NetworkImage can be passed in https://api.flutter.dev/flutter/painting/NetworkImage/headers.html so that ImageGallery can use "Authorization" header in order to download images

**Comment by demchenkoalex** [comment]
I went ahead and changed your PR a bit, `imageHeaders` are now on the Chat level (cause `ImageGalleryOptions` are strictly image gallery related, and you used them for the `ImageMessage` as well). Also passed same headers to the avatar's `NetworkImage`.
