### ISSUE TITLE
How to open chat with de default message in the input

### ISSUE THREAD

**Issue by wutsi** [flyerhq/flutter_chat_ui#333]
I would like to open a page with the chat widget, with the input message set with default message
How can I do that?
Thank you

**Comment by demchenkoalex** [comment]
Hello!

```dart
final _textEditingController = InputTextFieldController();

@override
void initState() {
  super.initState();
  _textEditingController.text = 'Default message';
}

Chat(
  // ...
  inputOptions: InputOptions(
    textEditingController: _textEditingController,
  ),
)
```

**Comment by iceycc** [comment]
切换页面：A InputTextFieldController was used after being disposed.

**Comment by demchenkoalex** [comment]
hey @iceycc I guess you passed your own `textEditingController` and then you tried to use it after chat screen was closed? Because I have this code in the input
```dart
@override
void dispose() {
  _textController.dispose();
  super.dispose();
}
```
it might be that I dispose your custom `textEditingController` before you try to use it for some reason. Is this the case you think?

**Comment by yuhan555** [comment]
I have the same problem, is it possible not to dispose the custom textEditingController?
