### ISSUE TITLE
UTC support

### ISSUE THREAD

**Issue by marinkobabic** [flyerhq/flutter_chat_ui#334]
Server returns the MillisecondsSinceEpoch but it uses UTC on the server. So we need a new option to enable utc on the client to display the proper time. Please see therefore DateTime.fromMillisecondsSinceEpoch https://api.dart.dev/be/169657/dart-core/DateTime/DateTime.fromMillisecondsSinceEpoch.html

**Comment by demchenkoalex** [comment]
MR was merged, I will try to make use of DateTime going forward (and replacing old dates)
