### ISSUE TITLE
Endless loop when not being able to connect to url preview

### ISSUE THREAD

**Issue by jlubeck** [flyerhq/flutter_chat_ui#34]
Please have a look at this example:
https://www.loom.com/share/3ef149cb9d77428d8812b827411b4ab6

Looks like if an error prevents the URL preview from connecting, it just tries again forever. 

This is on WEB btw (haven't tried this scenario on other platforms yet)

**Comment by demchenkoalex** [comment]
Hi @jlubeck please create issue in the appropriate repo. Thank you.
