### ISSUE TITLE
`PatternStyle` logic incorrect when parsing text throws BoxConstraints has a negative minimum width.

### ISSUE THREAD

**Issue by Mayb3Nots** [flyerhq/flutter_chat_ui#340]
# General

## What bug do you experience? 🐞
When entering modifiers for text like bolding, italics or strikethrough formats (*bold*, ~strikethrough~,_italic_) without any text in between like (**, __ , ~~) the `TextMessage` will throw invalid boxconstraints because the text returning is empty. As long as special modifier character is more than 2 times without any text then it will throw an error (like `****` or `_____`).

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Step 1. Run example app.
Step 2. Type `**` (or `__` or `~~`) (as long as more than 2 times in a row and more without any other text it will throw), and then press send. 
Step 3 Watch console log.

## What behavior is expected? 💡
The parsing should only match two special modifier charters with _something in the middle_ then only apply the effect.
So
`*bold*` = **bold**
`**bold*` = ***bold**
`**` = **
`__` = __
You can test on whatsapp and see the correct behavior.

I found some regex that might fix it although I'm not sure. 
https://gist.github.com/nathan-cruz77/6e43ac375103de597edf52e07abfcbffa
<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: `3.3.4`
flutter-chat-ui: `^1.6.5`

`flutter doctor -v` output 👇

```sh
[√] Flutter (Channel stable, 3.3.4, on Microsoft Windows [Version 10.0.22000.1098], locale en-MY)
    • Flutter version 3.3.4 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (2 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\samue\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32825.248
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.72.2)
    • VS Code at C:\Users\samue\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (4 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.22000.1098]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 106.0.5249.119
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): Emulator Pixel 4

OS version (e.g. iOS 14.5, Android 11):  Android 13

<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
Hey! Thanks for reporting! I have changed everything to the following pattern `~[^~]+~` basically find `~~` and have at least something between them. Looks like it works, however matching of bold nested with italic it not and I am not sure it worked before. My Regex knowledge is not allowing me to do this kind of magic unfortunately haha :D Will be included in the next release this weekend.
