### ISSUE TITLE
Cannot open URL on my android phone

### ISSUE THREAD

**Issue by Pao7o** [flyerhq/flutter_chat_ui#348]
Hi !
When I send a link in the chat I can't open it on my android phone. But I get there without any problem in the browser. Does anyone know why and how to fix this ?
Thank you so much !

**Comment by ArnoudWellens** [comment]
Same problem here.

**Comment by ArnoudWellens** [comment]
I have just found the solution. You need to ask permission on Android see https://stackoverflow.com/questions/65883844/flutter-url-launcher-is-not-launching-url-in-release-mode
