### ISSUE TITLE
Crashes when adding new messages to the list without an unique id

### ISSUE THREAD

**Issue by MuhammedKpln** [flyerhq/flutter_chat_ui#349]
## What bug do you experience? 🐞
When adding new messages/updating state it crashes which is most probably because of #298. While everything is fine on 1.6.4 upgrading from 1.6.5 to the latest versions all crashes. When  two messages with a similar id has added to list it will not update rather than it will crash. Instead would be better to throw a custom error with an explanation to get rid of this problem.

**Comment by gtalha07** [comment]
Confirmed as this is a known issue after ```PatchedAnimatedList``` implementation in ```ChatList``` widget.

**Comment by demchenkoalex** [comment]
This patch was applied to the Flutter repo as well and eventually will be removed from the project. I don't know what can be done, but I definitely know there is tons of logic relying on unique IDs. I am not sure I can only "warn" cause I can't even imagine how much code will be broken.
