### ISSUE TITLE
Asset folder is moved inside lib folder

### ISSUE THREAD

**Issue by kishan2612** [flyerhq/flutter_chat_ui#35]
Unable to load asset: packages/flutter_chat_ui/assets/3.0x/icon-read.png

pubspec.yaml is not updated

**Comment by demchenkoalex** [comment]
Hi @kishan2612 what is the problem exactly? assets folder was inside the lib folder from the beginning.

**Comment by kishan2612** [comment]
@demchenkoalex  I got this error when Im using chat_ui 
"Unable to load asset: packages/flutter_chat_ui/assets/3.0x/icon-read.png",

The icons are not loaded in the view

**Comment by kishan2612** [comment]
@demchenkoalex  Thanks for the immediate reply

1. flutter_chat_ui: ^1.0.5
2.  Flutter (Channel stable, 2.0.6)
3.  Mac OS 11.0.1
4.  Device - Mi A2 - Android 10 

Haven't tried with other devices. I solved this issue by using custom icons through DefaultChatTheme

**Comment by demchenkoalex** [comment]
According to this section of Flutter docs - https://flutter.dev/docs/development/ui/assets-and-images#bundling-of-package-assets they say that if, for example, the package has assets that look like

```
.../lib/backgrounds/background1.png
.../lib/backgrounds/background2.png
.../lib/backgrounds/background3.png
```

in our case it's

```
.../lib/assets/icon-send.png
```

then we should import them in `pubspec.yaml` as

```
flutter:
  assets:
    - packages/fancy_backgrounds/backgrounds/background1.png
```

in our case

```
flutter:
  assets:
    - packages/flutter_chat_ui/assets/icon-send.png
```

which is 100% according to the documentation.

And the important line is **The lib/ is implied, so it should not be included in the asset path.**, which we do too.

IMO, we did everything according to the documentation and I didn't hear from anyone that assets are not loaded, this must be some machine specific bug which can't be reproduced/fixed.

**Comment by gwbischof** [comment]
I had this same error.  I think restarting the app, instead of doing a hot restart fixed it.
