### ISSUE TITLE
Disable autoscroll 

### ISSUE THREAD

**Issue by dan91** [flyerhq/flutter_chat_ui#354]
Hello! 
Our chatbot sometimes sends multiple messages within a few seconds. To not disrupt the user while reading when a new message comes in, it would be nice if we could disable auto scroll to the bottom. Even if the user is not at the bottom, the view scrolls up by the amount of the space the invisible message at the bottom takes.
I tried to implement the scrollController but I could not find an option to disable the auto scroll.
On a related note: What would be nice to have is a button indicator of how many messages are unread at the bottom of the chat to be able to jump there. I saw that this has been mentioned here: https://github.com/flyerhq/flutter_chat_ui/pull/209#issuecomment-1203011700 +1 for this feature! :)
Thank you
Daniel

**Comment by adityasethipsi** [comment]
@dan91 anything new on this?

**Comment by JHubi1** [comment]
I'd need this as well
