### ISSUE TITLE
Disable Autocorrect in the Input

### ISSUE THREAD

**Issue by TJMusiitwa** [flyerhq/flutter_chat_ui#355]
I want to begin off by saying loving this package and has brought a whole new look to out inbox feature in our app.

That being said, I was just curious if there was a toggle we could use to disable the auto correct of the input field.
It seems a bit agressive and we would just want the field to allow a normal typing experince.
The API docs don't seem to present that option in the `InputOptions` property where i first checked before filing this question.
Thoughts?

Continue on with the great work and looking forward to all the updates you bring 
Thanks

**Comment by demchenkoalex** [comment]
Hello! Will add :)

**Comment by g0dzillaa** [comment]
@demchenkoalex any chance to merge this?
