### ISSUE TITLE
Unable to use the package, due to conflict with Intl package

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [flyerhq/flutter_chat_ui#373]
Please update to enable latest intl package to work

**Comment by aytunch** [comment]
@Ghazanfarrajpoot for now use this:
`intl: ^0.17.0`

**Comment by Ghazanfarrajpoot** [comment]
it's causing issues with latest firebase AUTH package, please add support for 0.18.0

**Comment by demchenkoalex** [comment]
updated.
