### ISSUE TITLE
Is there a way to move screen up with keyboard?

### ISSUE THREAD

**Issue by kubawich** [flyerhq/flutter_chat_ui#379]
Hey! Hen I try to type message, keyboard covers half of the chat screen, but it doesn't move up with keybaord but stay under it. Then I can see messages after unfocusing and hiding keyboard

Here's my code 

`
@override
  Widget build(BuildContext context) {
    chatController.roomModel = room;
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon:
              const Icon(Icons.arrow_back_ios_new_rounded, color: Colors.black),
          onPressed: () => Navigator.of(context).pop(),
        ),
        toolbarHeight: 75.0,
        backgroundColor: Colors.white,
        elevation: 0,
        title: Text(
          "${chatRoomsController.roomModel.name}",
          style: const TextStyle(
              color: Colors.black, fontSize: 30.0, fontWeight: FontWeight.w900),
        ),
      ),
      body: GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTap: () => FocusScope.of(context).unfocus(),
          child: StreamBuilder<types.Room>(
            initialData: chatRoomsController.roomModel,
            stream: FirebaseChatCore.instance
                .room(chatRoomsController.roomModel.id),
            builder: (context, snapshot) {
              return StreamBuilder<List<types.Message>>(
                initialData: const [],
                stream: FirebaseChatCore.instance.messages(snapshot.data!),
                builder: (context, snapshot) {
                  return SafeArea(
                    //bottom: false,
                    child: Chat(
                      l10n: const ChatL10nPl(
                          emptyChatPlaceholder: "Wyślij pierwszą wiadomość"),
                      showUserNames: true,
                      showUserAvatars: true,
                      disableImageGallery: true,
                      emojiEnlargementBehavior: EmojiEnlargementBehavior.multi,
                      hideBackgroundOnEmojiMessages: false,
                      theme: const DefaultChatTheme(
                          deliveredIcon:
                              Icon(Icons.check_circle_outline_rounded),
                          messageInsetsVertical: 12,
                          userAvatarNameColors: [Colors.black],
                          inputBorderRadius:
                              BorderRadius.vertical(top: Radius.circular(6)),
                          inputBackgroundColor:
                              Color.fromARGB(255, 205, 252, 207),
                          inputTextColor: Color.fromARGB(255, 65, 161, 68),
                          primaryColor: Color.fromARGB(255, 205, 252, 207),
                          sentMessageBodyTextStyle: TextStyle(
                              color: Color.fromARGB(255, 95, 95, 95),
                              fontWeight: FontWeight.bold)),
                      messages: snapshot.data ?? [],
                      onMessageTap: chatController.handleMessageTap,
                      onPreviewDataFetched:
                          chatController.handlePreviewDataFetched,
                      onSendPressed: chatController.handleSendPressed,
                      keyboardDismissBehavior:
                          ScrollViewKeyboardDismissBehavior.manual,
                      user: types.User(
                        id: FirebaseChatCore.instance.firebaseUser?.uid ?? '',
                      ),
                    ),
                  );
                },
              );
            },
          ))
`

**Comment by kubawich** [comment]
@SnowyTusk @cristaloleg bump

**Comment by cristaloleg** [comment]
@demchenkoalex

**Comment by AyumiSashitani** [comment]
@demchenkoalex 
I am in the same situation... 
Is there a workaround for this?

**Comment by demchenkoalex** [comment]
Hey, @AyumiSashitani I was not able to repro this and this is only second report of this behaviour, must be some unique set I didn't think of. This package became a bit bloated and hard to maintain, so I am working on `v2` branch currently on a full redesign.

**Comment by kubawich** [comment]
@demchenkoalex Do you need any help with that?

**Comment by demchenkoalex** [comment]
@kubawich with this issue? Yeah why not, will know what not to do in v2 at least haha

**Comment by kubawich** [comment]
@demchenkoalex @AyumiSashitani Fixed, in my case it was not issue with widget itself, but with routing to chat view from lobby. 
Previously it was 
``` Dart
{
  Navigator.of(context).push(
    MaterialPageRoute(
      builder: (context) => ChatsView(room),
    ),
  );
},
```
When changed to Getx's 

``` Dart
() => Get.to(() => ChatsView(room)),
```

It's giving expected result

**Comment by shisp** [comment]
@kubawich @AyumiSashitani

**Comment by shisp** [comment]
> @demchenkoalex @AyumiSashitani Fixed, in my case it was not issue with widget itself, but with routing to chat view from lobby. Previously it was
> 
> ```dart
> {
>   Navigator.of(context).push(
>     MaterialPageRoute(
>       builder: (context) => ChatsView(room),
>     ),
>   );
> },
> ```
> 
> When changed to Getx's
> 
> ```dart
> () => Get.to(() => ChatsView(room)),
> ```
> 
> It's giving expected result

The same problem you had, how did you solve it
