### ISSUE TITLE
Adding delivered and seen Icon

### ISSUE THREAD

**Issue by mkassir95** [flyerhq/flutter_chat_ui#382]
Hello,

How to add delivered and seen Icon , I added the` deliveredIcon` and `seenIcon` paramters, but no thing appeared. Also I checked the github example and there is no example for delivered icon

> const DefaultChatTheme(
                  deliveredIcon: Icon(Icons.receipt_outlined),
                  seenIcon:  Icon(Icons.radio),
                  inputBackgroundColor: Colors.blue,
                  primaryColor: Color(0xff06038D),
                  inputBorderRadius: BorderRadius.all(Radius.circular(20)),
                 messageInsetsVertical: 10,
                 inputMargin: EdgeInsets.all(10),
                  inputPadding: EdgeInsets.all(15),
                  backgroundColor: Colors.transparent,
                ),

**Comment by mkassir95** [comment]
I figured it out. Thank you for nice and easy package

**Comment by kisharora** [comment]
What was the solution bro?
