### ISSUE TITLE
Display name (first name / last name)  instead of id in author

### ISSUE THREAD

**Issue by Zechst** [flyerhq/flutter_chat_ui#383]
Hello FlyerChat,

I would like to seek help regarding the displaying of name (first / last name) instead of showing the id in `types.User.`

```

final sender = types.User(
                id: '7fd87ed1-1bbb-4846-8824-db1475bacd04',
                // Username
                firstName: ''zechst,
                lastName: '',
                // Display picture
                imageUrl:
                    data['profileImage']);
```
            

Under Chat widget, I have already passed in `showUserNames: true,` but the UI still renders as id 7fd87ed1-1bbb-4846-8824-db1475bacd04.

How do I display as Zechst (firstName) rather than 7fd87ed1-1bbb-4846-8824-db1475bacd04 (id)?

Please help

**Comment by demchenkoalex** [comment]
Hi @Zechst ID is not showed anywhere in the UI, it is practically impossible with a normal usage (try to run the example and pass `showUserNames: true` you will not see ID anywhere). Did you change the source code? Are you sure your data does not have IDs inside firstName??

**Comment by Zechst** [comment]
Hi @demchenkoalex , what do you mean by practically impossible with a normal usage?
I did not make changes to any of the source code, I used it right out of the box.
I did a dirty fix by putting my username under id and it displays Zechst, which means that ID is actually being displayed instead of the firstName/lastName parameters. But I believe this is not the solution as ID suppose to be unique and in this case usernames in my use case is not unique

**Comment by demchenkoalex** [comment]
I mean that if you run the example you will see first name and last name, as on the screenshot in the readme. I think I would have noticed if I'd render ID anywhere? I mean what is even a point of rendering ID? :D are you sure you provided a correct data?

**Comment by demchenkoalex** [comment]
I am running the app now in arabic (RTL) and user names are shown. You can see the data in https://github.com/flyerhq/flutter_chat_ui/blob/main/example/assets/messages.json

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-21 at 18 54 12](https://user-images.githubusercontent.com/14123304/213880398-ec147669-f120-486f-ba0b-b1ea23860189.png)

**Comment by Zechst** [comment]
> I am running the app now in arabic (RTL) and user names are shown. You can see the data in https://github.com/flyerhq/flutter_chat_ui/blob/main/example/assets/messages.json
> 
> 
> 
> ![Simulator Screen Shot - iPhone 14 Pro Max - 2023-01-21 at 18 54 12](https://user-images.githubusercontent.com/14123304/213880398-ec147669-f120-486f-ba0b-b1ea23860189.png)
> 
> 

Hi @demchenkoalex,
That is why I'm equally puzzled. I've tried to put data inside firstName and lastName and expect it to display like it's shown in the UI screenshot but it kept showing data from the ID, so honestly unsure what went wrong. I've put data inside firstName and lastName but nothing is showing from those fields

**Comment by demchenkoalex** [comment]
We are running the same code :) it is impossible that IDs would appear unless you put IDs inside first or last name.

See the code for yourself

```dart
if (showName)
          nameBuilder?.call(message.author.id) ??
              UserName(author: message.author),
```

```dart
/// Returns user name as joined firstName and lastName.
String getUserName(types.User user) =>
    '${user.firstName ?? ''} ${user.lastName ?? ''}'.trim();
```

you supplied `nameBuilder` maybe? looks like a custom widget builder for names. 

There are 2 options you can see this according to the code - you give ID inside first or last name, you provided `nameBuilder` and return a custom something with ID, not name.

**Comment by Zechst** [comment]
Hi @demchenkoalex ,
I think nameBuilder might be the cause as I added it in to customise the font style. Any work around that I can use to customise the text style and still return the firstName and lastName?

**Comment by demchenkoalex** [comment]
well you return a widget from there and you supply the text. You just passed ID from arguments to the Text widget I suppose. Instead, find a user with that ID (you should have users array somewhere) and take his first and last name

**Comment by Zechst** [comment]
Hi @demchenkoalex ,
this is my current name builder code

```
nameBuilder: (sender) => Text(
                                sender,
                                style: kUsernameTextStyle,
                              ),
```
I presume this is the wrong way to use this widget right? I used the Text widget to change the text style of the username

**Comment by demchenkoalex** [comment]
`sender` is the ID. You just show ID in the text :) since you don't use provided defaults, you obviously need to get what you show yourself from the user, not just show his ID :)

**Comment by Zechst** [comment]
In this case, how should I access the firstName from the `types.User` object that we've created?

**Comment by Zechst** [comment]
I figured out how to pass in the firstName instead of id. Thanks @demchenkoalex for pointing out about the nameBuilder issue. Appreciate the help :)
