### ISSUE TITLE
image width is not correct

### ISSUE THREAD

**Issue by mkassir95** [flyerhq/flutter_chat_ui#387]
Hello,

Image size some times is not correct, there is white padding
this is my code 

>     Future<void> _addImageToChat(XFile? selectedImage) async {
    final bytes = await selectedImage!.readAsBytes();
    final image = await decodeImageFromList(bytes);
    final imageMessage = types.ImageMessage(
      author: _senderUser,
      createdAt: DateTime
          .now()
          .millisecondsSinceEpoch,
      id: randomString(),
      size:bytes.length,
      name:selectedImage.name,
      uri:selectedImage.path,
        height: image.height.toDouble(),
      width: image.width.toDouble(),
    );
    _messages.insert(0, imageMessage);
    setState(() {
    });
  }

![Screenshot_20230127-071956](https://user-images.githubusercontent.com/72728047/215015457-be96fddd-049c-4e84-a474-ccf67252a0e0.png)

**Comment by demchenkoalex** [comment]
It is by design, to not crop the content. You can use custom image builder to build your own, suitable one.
