### ISSUE TITLE
Custom unread widget

### ISSUE THREAD

**Issue by maurycyw** [flyerhq/flutter_chat_ui#388]
## Is your feature request related to a problem?
The unread message indicator currently is very limited in its styling to theme based properties. I would also like to configure the text since we support multiple languages. 

## What solution would you suggest?
Add a widget override in `ScrollToUnreadOptions` to supply a custom widget. 

## Is there any additional solution to that?
No reasonable one?

```dart
class ScrollToUnreadOptions {
  const ScrollToUnreadOptions({
    this.lastReadMessageId,
    this.scrollDelay = const Duration(milliseconds: 150),
    this.scrollDuration = scrollAnimationDuration,
    this.scrollOnOpen = false,
    this.customBanner,
  });

  /// Will show an unread messages header after this message if there are more
  /// messages to come and will scroll to this header on
  /// [ChatState.scrollToUnreadHeader].
  final String? lastReadMessageId;

  /// Duration to wait after open until the scrolling starts.
  final Duration scrollDelay;

  /// Duration for the animation of the scrolling.
  final Duration scrollDuration;

  /// Whether to scroll to the first unread message on open.
  final bool scrollOnOpen;
  
  /// Returns an optional custom override for presenting the unread banner.
  final Widget? customBanner;
}
```

## Related issues/PRs
N/A that I could find

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/94 - need to re-do this for `v2` and make sure it is customisable as per request
