### ISSUE TITLE
Customizable message margins in chat list

### ISSUE THREAD

**Issue by kentnek** [flyerhq/flutter_chat_ui#395]
## Is your feature request related to a problem?
Horizontal margin is currently hardcoded to at least `20px`:

```dart
 // message.dart
 return Container(
      alignment: bubbleRtlAlignment == BubbleRtlAlignment.left
          ? currentUserIsAuthor
              ? AlignmentDirectional.centerEnd
              : AlignmentDirectional.centerStart
          : currentUserIsAuthor
              ? Alignment.centerRight
              : Alignment.centerLeft,
      margin: bubbleRtlAlignment == BubbleRtlAlignment.left
          ? EdgeInsetsDirectional.only(
              bottom: 4,
              end: isMobile ? query.padding.right : 0,
              start: 20 + (isMobile ? query.padding.left : 0),
            )
          : EdgeInsets.only(
              bottom: 4,
              left: 20 + (isMobile ? query.padding.left : 0),
              right: isMobile ? query.padding.right : 0,
            ),
```

## What solution would you suggest?
Allow this to be configurable via `ChatTheme`.

Thanks!

**Comment by luohao123** [comment]
@kentnek You can using my fork which have all these features, like:

customized padding from left, multiple action buttons in input bar:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/49749220/233781541-69e64191-a1b1-4e2a-9795-572ea191d0b2.png">

https://gitee.com/jinfagang/flutter_chat_ui

**Comment by demchenkoalex** [comment]
full customisation should be possible now with `v2`.
