### ISSUE TITLE
Partial video functionality missing from sendMessage() method.

### ISSUE THREAD

**Issue by hgandhi67** [flyerhq/flutter_chat_ui#398]
# General

## What bug do you experience? 🐞
Can't find PartialVideo functionality in sendMessage() method for video messages.

## What behavior is expected? 💡
PartialVideo functionality should be present in sendMessage() method along with other message types.

<br />

# Extras

## Screenshots or videos 📸
![image](https://user-images.githubusercontent.com/24764076/218011945-11f0695b-de3d-4ce6-84d2-77affc079b17.png)

## Code snippets 📝
If applicable, add code samples to help explain your problem.

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: 3.7.1
flutter_chat_ui: ^1.6.6

<br />

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
First of all, this is a different repo you're sending issue for (this is UI and you are pasting a screenshot from firebase). And video messages are not implemented in the UI, they were added in case someone wanted to use `videoMessageBuilder`, hence they are not present in the Firebase repo.
