### ISSUE TITLE
Feature Request - 'Like' a comment (Reactions)

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#40]
We talked about this previously, but didn't see a feature request for it.  This is one of the most requested chat features I get.  People have become reliant on using 'Like' on iMessage, Slack or twitter/Facebook/social media as a way to acknowledge someones point without having to actually write up a response.

**Comment by 31Carlton7** [comment]
This feature would be excellent. Is it in the works by any chance devs?
