### ISSUE TITLE
messageWidth property in ImageMessage widget doesn't limit its width, but height.

### ISSUE THREAD

**Issue by dinb1242** [flyerhq/flutter_chat_ui#403]
# General

## What bug do you experience? 🐞
I tried to limit ImageMessage's width using `imageMessageBuilder`, which returns `ImageMessage` widget that has custom `messageWidth: 100` argument.

But when I tested that this would work as I wanted, it doesn't limit the width, but height. So I opened flutter inspector whether its height is really applied by `messageWidth`, and I checked it's real.

```dart
// image_message.dart
class ImageMessage extends StatefulWidget {
// skipped...
  else { // line 144
        return Container(
          constraints: BoxConstraints(
            maxHeight: widget.messageWidth.toDouble(), // it constraints only 'maxHeight'
            minWidth: 170, // This is the property that I wanted to limit
          ),
          child: AspectRatio(
            aspectRatio: _size.aspectRatio > 0 ? _size.aspectRatio : 1,
            child: Image(
              fit: BoxFit.contain,
              image: _image!,
            ),
          ),
        );

```

## How can it be reproduced? 🤔
The below code is what I've wrote to limit `maximumWidth` of `ImageMessage`.

```dart
Chat(
  // Skipped properties...
 imageMessageBuilder: (imageMessage, {required messageWidth}) {
                  print(messageWidth); // it shows 306
                  return ImageMessage(message: imageMessage, messageWidth: 100); // I wanted to limit width.
  }, 
)
```

<img width="766" alt="image" src="https://user-images.githubusercontent.com/39480072/220825510-0a62b99f-734c-4979-8bfd-91165c751fa9.png">

## What behavior is expected? 💡
It would be nice to be applied `maxWidth` in `ImageMessage` widget using `messageWidth` argument of `ImageMessage`. 
<br />

<br />

# Platform
flutter_chat_ui: 1.6.6

<br />

Thank you for making such a great and convenient package! :)

**Comment by demchenkoalex** [comment]
should not be an issue in `v2` - however if someone will have such problem feel free to reopen.
