### ISSUE TITLE
Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

### ISSUE THREAD

**Issue by pinktoadette** [flyerhq/flutter_chat_ui#412]
# General

## What bug do you experience? 🐞
Getting 
The following assertion was thrown building ChatList(dependencies: [InheritedUser, MediaQuery], state: _ChatListState#e6922(ticker inactive)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.

## How can it be reproduced? 🤔
Step 1. It doesn't happen when it's `setState` as provided in the example
Step 2. First create many messages. I am not using firebase but still I'm using streambuilder. When you click on the keyboard, there is quite a number of errors related to `renderBox`. 
This is coming from chatlist. Screen is getting janky.

```
The following assertion was thrown building RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ec58a](state: RawGestureDetectorState#6d908(gestures: [vertical drag], behavior: opaque)):
A RenderSliverPadding expected a child of type RenderSliver but received a child of type RenderErrorBox.

RenderObjects expect specific types of children because they coordinate with their children during layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a RenderSliver does not understand the RenderBox layout protocol.
The RenderSliverPadding that expected a RenderSliver child was created by: SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#21e78] ← Semantics ← Listener ← _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ec58a] ← Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#bd229] ← NotificationListener<ScrollMetricsNotification> ← RepaintBoundary ← ⋯
The RenderErrorBox that did not match the expected child type was created by: ErrorWidget-[#1c1b4] ← PatchedSliverAnimatedList-[LabeledGlobalKey<PatchedSliverAnimatedListState>#6607c] ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#21e78] ← Semantics ← Listener ← _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ec58a] ← Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#bd229]

======== Exception caught by widgets library =======================================================
The following assertion was thrown building _ScrollableScope:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
```

## What behavior is expected? 💡

<br />

# Extras

## Screenshots or videos 📸
If applicable, add screenshots or videos to help explain your problem.

## Code snippets 📝

```dart
// Your snippet here...
```

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: 3.7.6
flutter-chat-ui: 1.6.6

`flutter doctor -v` output 👇

```sh
```

<br />

# Platform
Samsung Device

<br />

# Additional context
I've also downgraded to 1.6.4. Same issue.
Screen is getting janky, I think there are too many features in this. 
<!-- Thank you for making us better 🤝--!>

**Comment by yevgeniaronov** [comment]
@pinktoadette if you solved this, could you provide a solution? i have the exact same issue.
everything is ok when i have few messages, once i have more than 4, its starts to throw these errors.

**Comment by pinktoadette** [comment]
@yevgeniaronov  it is essentially this post https://github.com/flyerhq/flutter_chat_ui/issues/345
can't believe i missed the unqiue id!

**Comment by yevgeniaronov** [comment]
@pinktoadette omfg, i added roomid instead of chatmessageid on each message :/
wasted 5 hours on this. oh well.

thanks a lot!
