### ISSUE TITLE
Set initial text in the input field when opening Chat screen

### ISSUE THREAD

**Issue by jpainam** [flyerhq/flutter_chat_ui#413]
Hi all
Is there an interface to to grab the `TextController` of the input field and define an initial text when the user open the page?

**Comment by demchenkoalex** [comment]
Hi! Yes, see https://github.com/flyerhq/flutter_chat_ui/blob/d6693732e93e29804e2f5973bdc1247b235f2764/lib/src/widgets/input/input.dart#L244 comments will guide you :)
