### ISSUE TITLE
Audio Message Example

### ISSUE THREAD

**Issue by frkn-erkl** [flyerhq/flutter_chat_ui#418]
Are there any examples for  creating, sending or listening to audio messages?

**Comment by luohao123** [comment]
same request

**Comment by zamirszn** [comment]
@frkn-erkl @luohao123 that makes three of us , have you guys gotten a solution

**Comment by muonroi** [comment]
same request

**Comment by luohao123** [comment]
Yes. I made it. it works OK.

<img width="669" alt="image" src="https://github.com/flyerhq/flutter_chat_ui/assets/49749220/8f322c05-c79a-4f43-9566-edcba1f21d9d">

it works both on mobile and PC.

add my telegram to request my fork of this feature.

lucifertrump

**Comment by leeyisoft** [comment]
I have a similar solution here, relying on voice_message_package package 2.1.4

https://github.com/imboy-pub/imboy-flutter/blob/main/lib/component/message/message_audio_builder.dart

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/149 - will be picking tasks from Discussions.
