### ISSUE TITLE
Is that possible to use chat ui with a websocket backend ?

### ISSUE THREAD

**Issue by GoodMorrrrning** [flyerhq/flutter_chat_ui#419]
Hello, 
Wanted to make this chat ui plugin work with a websocket backend,
what should i do to achieve this ?

Thanks

**Comment by GoodMorrrrning** [comment]
Update : for person who are interested on same kind of stuff i've made this for websockets : `getMessages(types.User _user) {
    int i = 0;
    List<types.Message> messages = [];
    try {
      channel.stream.listen((msg) async {
        final textMessage = types.TextMessage(
          author: _user,
          createdAt: DateTime.now().millisecondsSinceEpoch,
          id: randomString(),
          text: msg,
        );
        setState(() {
          messages.insert(0, textMessage);
        });
        msg = msg.replaceAll(RegExp("'"), '"');

        var jsondata = json.decode(msg);
        if (jsondata["cmd"] == "message") {
          // Insert message to table
          var msgChat = jsondata["msg"];
          print(msgChat);
        }
      });
    } catch (e) {
      print("Error on connecting to websocket: $e");
    }
    return messages;
  }`

This function get messages async message from the socket and create a `TextMessage` from the socket data.
getting message from this function : `final _user = const types.User(id: '1');
  final _userRecive = const types.User(id: '2');
  List<types.Message> _messages = [];
  _MyHomePageState() {
    _messages = getMessages(_userRecive);
  }`

Note that you can delete the json logic from `getMessages()`

Message sent with ` channel.sink.add('{"message":"$msg"}');` Should now be printed on your chat app ! 

:)

**Comment by iqfareez** [comment]
Yeah, why not? https://github.com/LapanApps/app_chat

**Comment by demchenkoalex** [comment]
this library is backend agnostic, you just supply an array of messages. this array can come from anywhere.
