### ISSUE TITLE
Add GitHub link to pub.dev

### ISSUE THREAD

**Issue by nilsreichardt** [flyerhq/flutter_chat_ui#42]
## Description
Is there a reason why the GitHub Link is not available on the pub.dev sidebar? If I search for a package, many times I want to view the package or clone it to try out the example.

| Sidebar of flutter_chat_ui | Sidebar of another package |
|-|-|
| ![image](https://user-images.githubusercontent.com/24459435/121343186-b2c10f80-c922-11eb-9abb-7d1d196ecd4e.png) | ![image](https://user-images.githubusercontent.com/24459435/121343243-c2d8ef00-c922-11eb-81d4-256a28c6a94a.png) |

**Comment by demchenkoalex** [comment]
Hi @nilsreichardt thanks for bringing this up! We have `homepage` specified, but I see that there is also an optional `repository`. Will add this field with the next release.

**Comment by nilsreichardt** [comment]
Nice, thanks! 🙏

**Comment by demchenkoalex** [comment]
Released in [v1.1](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.0).
