### ISSUE TITLE
messageInsetsVertical and  messageInsetsHorizontal not working for removing bubble margin

### ISSUE THREAD

**Issue by jpainam** [flyerhq/flutter_chat_ui#424]
Hello 👋 

As you can see. There is still room in the `margin` left of the bubble. Any idea how to remove that extra margin?

![imageedit_1_2907764850](https://user-images.githubusercontent.com/1701705/232276596-0f8e3af7-cbe1-41fa-8d74-78ea72be72e8.png)

**Comment by jpainam** [comment]
You can see the big right margin left by the bubble

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-04-16 at 18 23 22](https://user-images.githubusercontent.com/1701705/232346001-b14a061f-4089-452b-997f-6117c5c49750.png)

**Comment by demchenkoalex** [comment]
should be possible with `v2`.
