### ISSUE TITLE
visibility_detector version support

### ISSUE THREAD

**Issue by markglibres** [flyerhq/flutter_chat_ui#425]
Is it possible to upgrade the dependency "visibility_detector" to its latest version?

"Because flutter_chat_ui 1.6.6 depends on visibility_detector ^0.3.3 and no versions of flutter_chat_ui match >1.6.6 <2.0.0, flutter_chat_ui ^1.6.6 requires visibility_detector ^0.3.3"

**Comment by bingao** [comment]
I have the same problem here. I used other packages whose latest versions depend on visibility_detector ^0.4.0+2, which are incompatible with flutter_chat_ui.

So it would great if the dependency of visibility_detector can be upgraded to its latest version. Thank you.

**Comment by markglibres** [comment]
@bingao I created PR to support for latest visibility_detector...  waiting for approval :)

**Comment by bingao** [comment]
Thank you @markglibres Looking forward to it :)

**Comment by demchenkoalex** [comment]
updated.
