### ISSUE TITLE
Unable to load asset: "packages

### ISSUE THREAD

**Issue by shrkh** [flyerhq/flutter_chat_ui#429]
Project startup prompt file error ：
Unable to load asset: "packages/flutter_chat_ui/assets/3.0x/icon-seen.png".
![1682514695520](https://user-images.githubusercontent.com/131459866/234585474-df7e6261-6373-40f2-aea4-9ffc846d33f4.png)

**Comment by demchenkoalex** [comment]
hmm, works ok for me. I wonder if someone else is getting this. Strange that only for that image 🤔

**Comment by NAMEER242** [comment]
> hmm, works ok for me. I wonder if someone else is getting this. Strange that only for that image 🤔

yes me too
