### ISSUE TITLE
Disable the send button while message is sending

### ISSUE THREAD

**Issue by dri94** [flyerhq/flutter_chat_ui#430]
How can I disable the send button, while the current message is still sending?. In my app, the user should not be able to send a new message until their current one is fully sent.

**Comment by dri94** [comment]
@demchenkoalex Thanks. I don't see any inputOptions object on Chat. I am not sure where I set that property

**Comment by demchenkoalex** [comment]
well it is there - https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/chat.dart#L61
