### ISSUE TITLE
Supabase backend support

### ISSUE THREAD

**Issue by naonvl** [flyerhq/flutter_chat_ui#433]
## Is your feature request related to a problem?
Firebase version is cool, but i'm now building a private app so i need to use i want to use supabase as backend. So far i can get the rooms stream, but got a problem on getting the messages stream from backend.

```dart

    messagesList = SupaFlow.client
        .from('messages')
        .stream(primaryKey: ['room_id'])
        .eq('room_id', widget.roomData['id'])
        .asBroadcastStream();

StreamBuilder<dynamic>(
          stream: messagesList,
          builder: (context, snapshot) => Chat(
            onMessageLongPress: (context, p1) {
              setState(() {
                isMessageDetail = true;
                selectedMessage = p1;
              });
            },
            onBackgroundTap: () {
              print('click');
              setState(() {
                isMessageDetail = false;
              });
            },
            customDateHeaderText: (p0) => _customDateHeaderText(p0),
            dateIsUtc: true,
            dateHeaderThreshold: 86400000,
            bubbleBuilder: _bubbleBuilder,
            theme: const DefaultChatTheme(
                primaryColor: const Color(0xFF399938),
                inputTextColor: Colors.black,
                inputBackgroundColor: Colors.white,
                backgroundColor: Colors.white,
                inputContainerDecoration: BoxDecoration(
                    border: Border(
                        top: BorderSide(color: const Color(0xFF399938)))),
                inputTextCursorColor: Colors.black,
                inputBorderRadius: BorderRadius.all(Radius.zero)),
            messages: _messages,
            onSendPressed: _handleSendPressed,
            onAttachmentPressed: _handleAttachmentPressed,
            onPreviewDataFetched: _handlePreviewDataFetched,
            onMessageTap: _handleMessageTap,
            user: peerUserData,
          )
```

how to make it work with supabase? i'm trying to map the query like the firebase demo but no clue what to do.

**Comment by AmirC123** [comment]
I think you would need to rewrite firebase_chat_core (https://github.com/flyerhq/flutter_firebase_chat_core), since this is the ui package
If you can rewrite FirebaseChatCore to a SupabaseChatCore with the same API it would be interchangeable (plus supabase doesn't charge for api calls like firestore, so that would make it better for production)

**Comment by demchenkoalex** [comment]
Firebase repo is just a reference on how the code could look like. As you can see this repo is UI only, it does not have any backend features, you just supply an array of messages. In your case, forget firebase repo, just get an array from supabase somehow (I don't know never worked with it) and put it into the chat ui, done. Make sure types are correct though.

**Comment by rickypid** [comment]
@naonvl look https://pub.dev/packages/flutter_supabase_chat_core (is based on [flutter_chat_ui](https://github.com/flyerhq/flutter_chat_ui))
