### ISSUE TITLE
How to show 'typing..' status?

### ISSUE THREAD

**Issue by casualcoder404** [flyerhq/flutter_chat_ui#437]
Please guide me on how to implement the 'typing status' functionality. 

In my case, I want to show it while the await function executes. Is there any way to add a custom widget between the chats?

**Comment by demchenkoalex** [comment]
> Is there any way to add a custom widget between the chats

what do you mean by this?

In general, you have control over when the await function executes, so use state or something to activate typing indicator. There is `typingIndicatorOptions` on chat class, pass user IDs that type in `typingUsers` array. This is not released on pub.dev so you have to use latest version from the main branch.
