### ISSUE TITLE
Require voice message's features

### ISSUE THREAD

**Issue by Nring-Cham-Aung** [flyerhq/flutter_chat_ui#438]
Let me know in which time does become?
It is better to having voice message's features.

**Comment by azazadev** [comment]
any plan for this features please ?

**Comment by demchenkoalex** [comment]
it was mentioned lots of times, so I will close this one as a duplicate. I was not generally updating the library much recently, and after returning I realised it became too complicated and too slow. My first priority will be re-writing this from scratch in a monorepo style, with performance and extensibility in mind. I will create an issue to track later.
