### ISSUE TITLE
More extensive Markdown support

### ISSUE THREAD

**Issue by clotodex** [flyerhq/flutter_chat_ui#440]
## Is your feature request related to a problem?
Certain obvious markdown features, like aligned lists, bullet points, etc are not working with the limited implementation from #157 #206 

## What solution would you suggest?
Depending on a package like flutter_markdown which you can maybe control by a boolean flag.

## Is there any additional solution to that?
Making it easier to style the message by yourself. In theory it is possible but essentially with the message_builder attribute you end up rewriting the whole internal implementation anyways. Maybe exposing the internal message builder with an "build text widget" builder where one could plug-in their own purely text-focused adjustments.

## Related issues/PRs
#157 #206 #154

**Comment by TimoNewton** [comment]
Just confirming:  Current pattern styles (since version 1.6.6) do not appear to match [markdown standards](https://www.markdownguide.org/basic-syntax/#emphasis) .  

- Bold is explicilty single asterisk, where markdown expects double asterisk or double underscore
- italic is explicitly single underscore, where markdown expects single asterisk or single underscore

was this an intended change?  If not, it appears that 1.6.6 reversed out the fixes provided by merge 206 linked in this ticket.

**Comment by mrkmrtns** [comment]
Same question 🙏  I tried to understand where my `*` are lost and eventually found this thread.
Is it possible to disable this broken markup somehow?

**Comment by demchenkoalex** [comment]
I am about to merge v2 to the main branch and continue from there - but before v2 will be useful, it would be nice to disable this if it causes issues - anyone care to open an MR? I will merge and release it. More extensive support will land in v2 - will use some package for it.

**Comment by mrkmrtns** [comment]
Not sure what was logic selecting those but most trouble makes for me `*` and `_`. First ruins any math equations when multiplications are involved. `_` is commonly used in names as snake-case. 

Nevertheless imo it should be configurable if markdown etc is used, also in case of markdown escaping should work by preceding `\`.

Nevertheless should I try to remove totally matching `bold|italic|lineTrough|code` or I can use there double characters for now to not collide so easily with regular text.
Meaning for `bold` it must be then between `**`, for italic between `__`, for code between ```` and for lineTrough between `~~`. Nevertheless either way is breaking change 🤷 but maybe it's not so important.

**Comment by demchenkoalex** [comment]
I updated markdown as per your suggestions @mrkmrtns. Released in `v1.6.15`.

**Comment by demchenkoalex** [comment]
Keeping as reopened to use more extensive markdown package in v2

**Comment by demchenkoalex** [comment]
`v2` uses https://pub.dev/packages/flutter_markdown
