### ISSUE TITLE
Flutter upgrade breaks version 1.6.6 because it depends on intl ^0.17.0 and the sdk depends on intl ^0.18.0

### ISSUE THREAD

**Issue by dickverweij** [flyerhq/flutter_chat_ui#442]
# General

## What bug do you experience? 🐞
after flutter upgrade to version 3.10.0 we get dependency errors on flutter pub get
packages flutter_localizations from the sdk uses another version 

**Because flutter_chat_ui 1.6.6 depends on intl ^0.17.0 and no versions of flutter_chat_ui match >1.6.6 <2.0.0, flutter_chat_ui ^1.6.6 requires intl ^0.17.0.
And because every version of flutter_localizations from sdk depends on intl 0.18.0, flutter_chat_ui ^1.6.6 is incompatible with flutter_localizations from sdk.**

## How can it be reproduced? 🤔
on channel stabel run flutter upgrade (to 3.10.0)
add depency to your flutter_chat_ui
run flutter pub get
## What behavior is expected? 💡
All dependencies should be resolved

# Extras

## Code snippets 📝

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: 3.10.0.
flutter-chat-ui: 1,6,6 

`flutter doctor -v` output 👇

```[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1555], locale nl-NL)
    • Flutter version 3.10.0 on channel stable at C:\Development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (2 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc5)
    • Android SDK at C:\Users\dvy\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 31.0.0-rc5
    • ANDROID_HOME = C:\Users\dvy\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.10.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.10.31410.357
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code, 64-bit edition (version 1.77.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.62.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.1555]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 113.0.5672.92
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 112.0.1722.34

[√] Network resources
    • All expected network resources are available.
```

<br />

# Platform

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by tomquas** [comment]
here's a simple workaround until this package has been updated; edit pubspec.yaml:
```
dependency_overrides:
  intl: any
```

**Comment by MonkeyDrone** [comment]
intl: any doesn't work for me. Other plugins require different versions.
Please update this plugin so we can update to the latest version.

**Comment by giorgio79** [comment]
Yep, looks like Futter core upgraded to the latest intl...

**Comment by Yahllil** [comment]
Any update?

**Comment by dickverweij** [comment]
i've created a quick fork https://github.com/dickverweij/flutter_chat_ui for now, only to be used if you're stuck 

![image](https://github.com/flyerhq/flutter_chat_ui/assets/8133838/e62039e9-9091-4394-85e1-59e1f2d470a2)

**Comment by demchenkoalex** [comment]
Updated.
