### ISSUE TITLE
Just want to bring to light an issue with the latest release regarding intl version.

### ISSUE THREAD

**Issue by MonkeyDrone** [flyerhq/flutter_chat_ui#447]
The latest release of flutter_chat_ui uses intl 0.18.1 whereas the Flutter SDK 3.10 was upgraded to stable 0.18.0.
I ran into conflict issues with other plugins that require intl 0.18.0 from Flutter SDK but flutter_chat_ui requires 0.18.1.

I forked myself a copy and manually modified the intl to 0.18.0 in the pubspec and everything is working great. You might want to bump the intl version down to the version Flutter SDK 3.10 is using so not to run into compatibility issues. 

Thank you.

**Comment by demchenkoalex** [comment]
Will do

**Comment by demchenkoalex** [comment]
Updated.
