### ISSUE TITLE
Can I increase the chat bubble width so it's more than 440?

### ISSUE THREAD

**Issue by rutaba1** [flyerhq/flutter_chat_ui#450]
Hi, I am using this plugin on flutter web and I want to extend the chat bubble to full width of the screen if text message is long. However I noticed that chat container width never gets passed 440. Is there a way I can achieve full width for long messages?

**Comment by demchenkoalex** [comment]
I think it is hardcoded somewhere, you can open a PR with a parameter to change that

**Comment by KingUgochukwu** [comment]
@rutaba1 were you able to find where this is hard coded?

**Comment by demchenkoalex** [comment]
possible in `v2`.
