### ISSUE TITLE
Example of how to use ChatList component

### ISSUE THREAD

**Issue by guikfe** [flyerhq/flutter_chat_ui#454]
I am writing to seek assistance regarding the usage of the `ChatList` component. I have been exploring this library and found the ChatList component would help me to list the current user's chats. However, I am encountering some difficulties in understanding its implementation and would greatly appreciate your guidance through an example.

**Comment by demchenkoalex** [comment]
It was never designed to use outside, and the code is pretty outdated there, so will not be able to help here

**Comment by guikfe** [comment]
Ok, so I presume the only widget intended to use is `Chat`, correct?

**Comment by demchenkoalex** [comment]
yes
