### ISSUE TITLE
Make parse rules to empty on default

### ISSUE THREAD

**Issue by PonyPC** [flyerhq/flutter_chat_ui#455]
## Is your feature request related to a problem?
No

## What solution would you suggest?
Disable default match rules

## Is there any additional solution to that?
No

## Extras

**Code snippets 📝**
in widget/message/text_message.dart

maybe change
```dart
parse: [
          ...options.matchers,
```
to
```dart
parse: options.matchers ?? [
```
and make matchers to List?

**Comment by demchenkoalex** [comment]
not a feature anymore in `v2`.
