### ISSUE TITLE
Image Provider - Full Screen Image in chat onClick

### ISSUE THREAD

**Issue by typexy** [flyerhq/flutter_chat_ui#459]

**Comment by typexy** [comment]
Hi,

just tried out the new imageBuilderProvider - very nice so far. Is it possible to have it fullscreen by default, if you click on a messageImage? 
Currently it is shown only across the message area, not the profile header.

Thanks

**Comment by thanhnn-bap-jp** [comment]
![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-06 at 15 56 37](https://github.com/flyerhq/flutter_chat_ui/assets/103561101/47c54bf0-7bc2-42e6-9e15-6dbd58ca073c)
Same! ImageGallery can not fullscreen.

**Comment by demchenkoalex** [comment]
Not sure, this is 3rd party, but there is also a custom builder for this, you can disable default gallery and make your own

**Comment by leeyisoft** [comment]
You are required to click the image after the second screenshot effect？

If so, you can refer to my code https://github.com/imboy-pub/imboy-flutter/blob/main/lib/page/chat/chat/chat_view.dart
```
line 615  _onMessageDoubleTap

line 906             onMessageTap: (BuildContext c1, types.Message message) async {

```

![image](https://github.com/flyerhq/flutter_chat_ui/assets/6138668/2b50ff91-be91-496b-8276-fdc2968d6186)

![image](https://github.com/flyerhq/flutter_chat_ui/assets/6138668/95650f23-9c87-48fa-8442-d04324854e99)

**Comment by demchenkoalex** [comment]
image preview will not be included in `v2` - package user will be able to write their own preview if needed.
