### ISSUE TITLE
Can I use a local database like isar?

### ISSUE THREAD

**Issue by chavu** [flyerhq/flutter_chat_ui#463]
Can I use flutter_chat_ui with databases like Isar or ObjectBox to save all sent and received messages locally on the device. Then have a data synch mechanism with my prefere backend which could be firebase or appwrite or any REST api.

**Comment by demchenkoalex** [comment]
Yes why not, you just supply array of messages to the lib, where they come from is none of libs business

**Comment by chavu** [comment]
Thanks. I will give it a spin
