### ISSUE TITLE
Alignment on Avatars

### ISSUE THREAD

**Issue by cinjon** [flyerhq/flutter_chat_ui#464]
I have `showUserAvatars: true`. I also have a custom Bubble class with:

```
        alignment:
            message.author.id != "you" ? Alignment.topLeft : Alignment.topRight,
```

This means that the user's avatar will be on the left but its messages on the right. Is there a way to move the user's avatar to the right side?

**Comment by demchenkoalex** [comment]
Hi @cinjon you can also do a custom user avatar then?

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/106 - will be picking tasks from Discussions.
