### ISSUE TITLE
Incompatibility issue in flutter_test package between Flutter SDK and Flutter_chat_ui

### ISSUE THREAD

**Issue by halhwadi** [flyerhq/flutter_chat_ui#467]
Hello
i cant install flutter_chat_ui due to incompatibility in flutter_test between flutter_SDK and Flutter_chat_ui, please see the error message below:

**Error msg:**
**_"Because every version of flutter_test from sdk depends on meta 1.8.0 and flutter_chat_ui >=1.6.7 depends on meta ^1.9.1, flutter_test from sdk is incompatible with flutter_chat_ui >=1.6.7."_**

note: upgrading flutter version is not recommended because I have a lot of packages which may be broken and will require fixing .

**Futter_chat_ui version 1.6.8**

**Flutter Doctor:**
_Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-AE)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.4)
[√] Android Studio (version 2022.1)_

**Dart version: Dart SDK version: 2.19.0** 

_**Temporary solution: downgrade flutter_chat_ui version to 1.6.6**_

**Comment by demchenkoalex** [comment]
Should be fixed in a new version, 1.6.9
