### ISSUE TITLE
I want to add a Widget to the top of the Flutter chat page.

### ISSUE THREAD

**Issue by wakka0014** [flyerhq/flutter_chat_ui#472]
Thank you for creating flutter_chat_ui And create easy a chat UI!!

<img width="182" alt="スクリーンショット 2023-07-07 15 40 27" src="https://github.com/flyerhq/flutter_chat_ui/assets/19570256/d9b61302-8cb6-4d7f-b96d-0eba0b0d6298">

I would like to implement it as shown in the image.

I want to insert the Widge at the red line and make the scrolling area of the message only inside the blue frame.

How should I implement this?

I have looked at many issues on Github, but I can't find an effective way to implement it.

**Comment by demchenkoalex** [comment]
Hi! Placing a widget on top of the `Chat` in a `Column` or something will not work? something like

```
Column([
  YourWidget()
  Chat()
])
```

**Comment by wakka0014** [comment]
@demchenkoalex 

Columns could be used to implement this.
Thanks!
