### ISSUE TITLE
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 259 pos 16: 'child == null || indexOf(child) > index': is not true.

### ISSUE THREAD

**Issue by zzxap** [flyerhq/flutter_chat_ui#474]
when I send message

it show error 

'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 259 pos 16: 'child == null || indexOf(child) > index': is not true.

how to fix it?

**Comment by demchenkoalex** [comment]
I can't help without seeing what you're sending. But the most common error is when message ids are the same, are you sure your messages have different ids?

**Comment by elihaialgoaitech** [comment]
You may add a check of duplicate id. and give more clear exception

**Comment by demchenkoalex** [comment]
I will in a new version

**Comment by tafsin** [comment]
I am also facing the same issue. Please help anyone.

**Comment by demchenkoalex** [comment]
make sure you don't have duplicate ids in your messages, `id` is a unique identifier and stable work is not guaranteed if they repeat

**Comment by tafsin** [comment]
Thank You. The error is resolved now.

**Comment by mohitleo03** [comment]
I am also facing this issue, according to me my ids are different. this is my message list - 


_TextMessage(_User(null, , 634b2f0b-2486-4bfe-b36d-1c7d6313c7b3, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702915115924, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, message, null)
 _TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702915115839, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 7, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702915055419, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 6, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702914990999, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 5, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702914794703, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 4, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702914540783, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 3, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702914140669, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 2, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913958711, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 2, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913889690, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 2, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913601272, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, 1, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913576988, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913576813, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
 _TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913576657, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913576484, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913575941, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913556640, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913547823, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913487073, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913450805, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null)
_TextMessage(_User(null, , e52552f4-835d-4dbe-ba77-b076e659774d, http://upload.staging.pieinfosystems.com/images/1699515728795cb441fd5-0980-4802-8436-a123246d06a98097362849258344151.jpg, , null, null, null, null), 1702913379495, e52552f4-835d-4dbe-ba77-b076e659774d, null, null, null, null, null, null, Status.delivered, hi, null).

if someone can help me out please...
