### ISSUE TITLE
Japanese input is wrong in Flutter web.

### ISSUE THREAD

**Issue by fugumap** [flyerhq/flutter_chat_ui#476]
### Japanese input is wrong.
I use it in Flutter web.
(It's working fine on android.)

This is typing "こんにちわ(ko,nn,ni,ti,wa)".
![こんにちは](https://github.com/flyerhq/flutter_chat_ui/assets/121592556/e1154b4f-5aa5-41ee-b020-bff5f3bcd10d)

**Comment by demchenkoalex** [comment]
So if it is working fine on Android, but does not work in web, means Flutter issue?

**Comment by fugumap** [comment]
I see that it works fine on the web with other libraries.
So I don't think it is a Flutter issue.

**Comment by demchenkoalex** [comment]
You can always check the code as well, here is the input https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/input/input.dart#L161 I don't see anything that will jeopardise any particular language. Maybe text controller that tries to format the input? you can supply your own controller via `inputOptions` class https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/input/input.dart#L248 see if this helps?
