### ISSUE TITLE
Implement localisation support for the typing indicator

### ISSUE THREAD

**Issue by kryptamine** [flyerhq/flutter_chat_ui#480]
## Problem description
Currently, there is an issue where the typing indicator text is hardcoded, making it impossible to translate into different languages.

## Proposed solution
To address this issue, I suggest introducing translation keys into the [ChatL10n](https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/chat_l10n.dart) class

**Code snippets 📝**
https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/typing_indicator.dart#L224

```dart
/// Handler for multi user typing text.
  String _multiUserTextBuilder(List<types.User> author) {
    if (author.isEmpty) {
      return '';
    } else if (author.length == 1) {
      return '${author.first.firstName} is typing';
    } else if (author.length == 2) {
      return '${author.first.firstName} and ${author[1].firstName}';
    } else {
      return '${author.first.firstName} and ${author.length - 1} others';
    }
  }
```

**Comment by demchenkoalex** [comment]
Thanks for the report! To be implemented

**Comment by demchenkoalex** [comment]
to be re-implemented from scratch with `v2` with localisation added. closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/191 - will pick from Discussions.
