### ISSUE TITLE
How to send SystemMessage?

### ISSUE THREAD

**Issue by superaldo** [flyerhq/flutter_chat_ui#485]
Hello 👋 
I have searched in all the questions and I did not find anything that helps me, my questions is simple.
someone know how to send system message into the chat, I try do it with this code but its no work

//////////////////////////
void _sendSystemMessage(String idx) async {
    final systemMessage = types.SystemMessage(
        text: 'mensaje de sistema', id: idx, type: types.MessageType.system);

    FirebaseChatCore.instance.updateMessage(
      systemMessage,
      widget.room.id,
    );
  }
////////////////////////

I know that changing the "type" field on my firestore to "text" to "system" changes the appearance of the message, and I suppose there must be a method to send system messages.

thanks in advance

**Comment by demchenkoalex** [comment]
Hi! Is this related to the chat UI or firebase? Can you just add `SystemMessage` to the `messages` array of chat UI? I think this should work. If it is firebase related, issue should be there

**Comment by superaldo** [comment]
Hi, I using firebase, I can change the message to a system one if I manually change the "type" field to "system" 
![Captura de pantalla 2023-08-09 232452](https://github.com/flyerhq/flutter_chat_ui/assets/5176137/a7dcb947-8d77-4241-b874-1df90eb24c8c)
![Captura de pantalla 2023-08-10 042744](https://github.com/flyerhq/flutter_chat_ui/assets/5176137/c7db219b-a530-442e-b865-1a19d2e1ec09)
