### ISSUE TITLE
RenderBox was not laid out: _RenderEditableCustomPaint#42f4b NEEDS-LAYOUT NEEDS-PAINT 'package:flutter/src/rendering/box.dart': Failed assertion: line 1966 pos 12: 'hasSize'

### ISSUE THREAD

**Issue by tafsin** [flyerhq/flutter_chat_ui#487]
Please help me, anyone, to solve this issue. I am getting this related to Chat widget of this package.

**Comment by muthuremo** [comment]
yes i got this but  while sending image or file message empty bubble displayed but actually from the API i have received the data but not rendering on UI

**Comment by gada-raj** [comment]
Did you find any solution regarding this?

**Comment by demchenkoalex** [comment]
`v2` is a complete redesign so hopefully this issue does not exist there
