### ISSUE TITLE
When will it be possible to support graphic and text mixed messages, automatically identify the picture links contained in the content and display them as pictures plus text

### ISSUE THREAD

**Issue by dary123** [flyerhq/flutter_chat_ui#489]
When will it be possible to support graphic and text mixed messages, automatically identify the picture links contained in the content and display them as pictures plus text

**Comment by demchenkoalex** [comment]
> automatically identify the picture links contained in the content and display them as pictures plus text

what do you mean by `automatically identify the picture links contained in the content`?

**Comment by renzhenxuexi0** [comment]
It might be possible to display the image directly if the user’s message contains an image link or an image. In general, it is to put the image and text information in a chat bubble.

**Comment by demchenkoalex** [comment]
I think it should work like this already with the link preview, I am currently on a heavily modified v2 branch so can't try, but I am pretty sure it will work. Can try later when I will commit some work.

**Comment by demchenkoalex** [comment]
pointing to https://github.com/flyerhq/flutter_chat_ui/discussions/651 - will be picking tasks from Discussions.
