### ISSUE TITLE
How do I get to change the status of a message to seen or delivered

### ISSUE THREAD

**Issue by infinite-dev22** [flyerhq/flutter_chat_ui#490]
How do I get to change the status of a message to seen or delivered and also how do I set the unread banner and How do I get the scroll to first unread message.
I fully understand that this 👇️ is how a message status is updated
```
final updatedMessage = p0.copyWith(status: Status.delivered || Status.seen);
FirebaseChatCore.instance.updateMessage(updatedMessage, widget.room.id);
setState(() {});
```
Where do I add the above so that a message's status is updated accordingly.

I also understand that to scroll to first unread message I use this 👇️
```
const ScrollToUnreadOptions(
  lastReadMessageId: 'lastReadMessageId',
  scrollOnOpen: true,
)
```
What do I place at ```lastReadMessageId```, i get it's the message id but how do i get this.

**Comment by demchenkoalex** [comment]
Hello!

I see you paste code from firebase lib as well, please note that firebase lib is just an example that the UI can work with different backends, and not a fully featured chat backend library.

Given that, yes, your code to update message's status is correct, but where do you place it - up to your business logic. Possibly utilising `onMessageVisibilityChanged` to change the latest seen message status and then having some cloud function in firebase to update all prior messages as well, or maybe updating all prior messages from frontend call as well.

`lastReadMessageId` you should probably store somewhere in your app, and you can get that by using `onMessageVisibilityChanged` chat function.

**Comment by infinite-dev22** [comment]
Thank you for the reply, for changing the message visibility am using your second suggestion > updating all prior messages from frontend call as well.
this is working well for setting ```status``` to ```delivered``` though not updating this message's status to ```seen``` on another device or when the recipient sees the message.

**Comment by demchenkoalex** [comment]
yes for this you will need backend :) or cloud functions if you use firebase. It is impossible to do through the client.
