### ISSUE TITLE
How to change overall chat padding?

### ISSUE THREAD

**Issue by SanginiG** [flyerhq/flutter_chat_ui#496]
<img width="129" alt="Screenshot 2023-09-10 at 6 53 43 PM" src="https://github.com/flyerhq/flutter_chat_ui/assets/121866209/91eecda5-45e9-4d3e-8908-03bf4ae7ae40">
I am unable to change the default padding on the left side of my avatars

**Comment by demchenkoalex** [comment]
I don't think this was added, you can open a PR though

**Comment by demchenkoalex** [comment]
yeah as I replied above, I think it is hardcoded - you can open a PR though 👌
