### ISSUE TITLE
Flutter Chat UI with supabase 

### ISSUE THREAD

**Issue by G4l4p4g0** [flyerhq/flutter_chat_ui#497]
There is the possibility of implementing with supabase

**Comment by G4l4p4g0** [comment]
There is the possibility of implementing with supabase

**Comment by demchenkoalex** [comment]
Yes, chat UI is backend agnostic. Just use the same types chat UI is using and everything will work. This is an example of backend in Firebase https://github.com/flyerhq/flutter_firebase_chat_core you can do similar for Supabase.
