### ISSUE TITLE
Confused on how to add messages from both a sender and a receiver 

### ISSUE THREAD

**Issue by Princewil** [flyerhq/flutter_chat_ui#499]
Hi, Please I am confuse right now. When I insert a message that is to be sent by a user with `_messages.insert(0, message);` it works well, but the order get distorted when I use this same method to update a message was sent to this same user. The messages are going upside down. 

Please I'm pretty confuse on how or what I am doing wrong

**Comment by Princewil** [comment]
Never mind, I figured it out. 
If anyone ever have this issue do let me know I will explain.

**Comment by COLOUREDGLAZES** [comment]
Hello! I have the same problem now. How did you solve it?
