### ISSUE TITLE
How to use my own Meesage in the flutter_chat_ui

### ISSUE THREAD

**Issue by zengchanghuan** [flyerhq/flutter_chat_ui#502]
My Message json format is as follows:
{
"type":"PICTURE",
"version":"v1",
"messageId":"1707264469811331073",
"sessionId":"1706599556126343169",
"sequence":"34",
"uniqueId":"79d1072ff4274a189149ea254b5188b1",
"fromUid":"8",
"fromClientUid":"10010001008",
"createTime":"1695878543000",
"fileUrl":"https://d3ewlkolgx1g00.cloudfront.net/202309/0e3353cd9cdf4bdeb425f4b943bcf547.jpeg",
"fileName":"3235236457568769876978945image.jpg",
"contentType":"image/jpeg"
},
{
"type":"TEXT",
"version":"v1",
"messageId":"1707264290534195202",
"sessionId":"1706599556126343169",
"sequence":"33",
"uniqueId":"e0da115a20df4189b4f52baa1d5248db",
"fromUid":"8",
"fromClientUid":"10010001008",
"createTime":"1695878500000",
"text":"What are you😧"
},

**Comment by demchenkoalex** [comment]
Just map your fields to the fields that this library uses, you can run some transformation function when you fetch your messages. From a quick glance it should easily map to the message types here.

**Comment by zengchanghuan** [comment]
I'm a little confused about the transformation function. Do I need to implement the transformation function myself or is there already a related transformation function?Thank you so much.

**Comment by demchenkoalex** [comment]
Yes you need to implement it yourself, I have no way of knowing what types you have. Pretty much any UI library will require some specific values from you, unless you write your own that suits your values - but then if you open source it, someone will ask how to map your types to theirs :) this is because when you do UI you need some properties to build widgets, like texts, urls, ids etc. and those can't be dynamic.

The most basic way of doing this is when you fetch your messages and receive JSONs, you can create messages using types from this library and values from your JSONs. Something like get, then response json, then map by type; if type is PICTURE, create types.ImageMessage(id: uniqueId, etc), if type is TEXT create types.TextMessage etc.

**Comment by zengchanghuan** [comment]
Thank you so much. I added a transformJsonToMessage function. I take some data put into metadata.I am not sure this is ok.
 void _loadMessages() {
    //This is my JSON data
    final jsonData = <Map<String, dynamic>>[
      /*
      {
        "type":"PICTURE",
        "version":"v1",
        "messageId":"1707266373824020481",
        "sessionId":"1706599556126343169",
        "sequence":"36",
        "uniqueId":"01ad3a890e01452b8072876f102a531e",
        "fromUid":"8",
        "fromClientUid":"10010001008",
        "createTime":"1695878997000",
        "fileUrl":"https://d3ewlkolgx1g00.cloudfront.net/202309/f01684a40e774085b984d5a52ef6cde3.jpeg",
        "fileName":"3235236457568769876978945image.jpg",
        "contentType":"image/jpeg"
      },
      {
        "type":"TIP",
        "version":"v1",
        "messageId":"1706600701695623170",
        "sessionId":"1706599556126343169",
        "sequence":"3",
        "uniqueId":"62da286e15d6bd1b479c4d80ad1a3b15",
        "fromUid":"24",
        "fromClientUid":"10010001026",
        "createTime":"1695720289000",
        "fromTip":"5oKo5bey5bCG6K6i5Y2V5qCH6K6w5Li64oCc5bey5LuY5qy+4oCd77yM6K+3562J5b6F5a+55pa556Gu6K6k5pS25qy+5bm25pS+6KGM44CC",
        "toTip":"5a+55pa55bey5bCG6K6i5Y2V5qCH6K6w5Li64oCc5bey5LuY5qy+4oCd77yM6K+35Y+K5pe25p+l5pS25bm25bC95b+r5ZCR5Lmw5pa55pS+6KGM44CC5rOo5oSP77yM6K+35Yqh5b+F55m75b2V5oKo55qE6LSm5oi356Gu6K6k5pS25qy+5ZCO5YaN5pON5L2c5pS+6KGM77yM5ZCm5YiZ5Y+v6IO96YCg5oiQ5oKo55qE6LSi5Lqn5o2f5aSx44CC"
      },
      */
      {
        'type':'TEXT',
        'version':'v1',
        'messageId':'1707203203315007489',
        'sessionId':'1706599556126343169',
        'sequence':'22',
        'uniqueId':'722cd9ba2e3b4697b9f5ae9f3e35d24a',
        'fromUid':'8',
        'fromClientUid':'10010001008',
        'createTime':'1695863936000',
        'text':'1111',
      },
      {
        'type':'TEXT',
        'version':'v1',
        'messageId':'1707203203315007489',
        'sessionId':'1706599556126343169',
        'sequence':'22',
        'uniqueId':'722cd9ba2e3b4697b9f5ae9f3e35d24a',
        'fromUid':'8',
        'fromClientUid':'10010001009',
        'createTime':'1695863936000',
        'text':'33333',
      },
    ];

    final messages = <types.Message>[];

    for (var json in jsonData) {
      final message = transformJsonToMessage(json);
      if (kDebugMode) {
        print(message);
      }
      messages.add(message);
    }

    setState(() {
      _messages = messages;
    });
  }

  types.Message transformJsonToMessage(Map<String, dynamic> json) {
    final metadata = {
      'version': json['version'],
      'sessionId': json['sessionId'],
      'sequence': json['sequence'],
    };

    final createdAt = json['createTime'] != null ? int.tryParse(json['createTime']) : null;

    switch (json['type']) {
      case 'TEXT':
        return types.TextMessage(
          author: types.User(id: json['fromClientUid']),
          createdAt: createdAt,
          id: json['uniqueId'],
          remoteId: json['fromClientUid'],
          status: types.Status.seen,
          text: json['text'],
          metadata: metadata,
        );
        /*
      case 'PICTURE':
        return types.ImageMessage(
          author: types.User(id: json['fromUid']),
          createdAt: createdAt.millisecondsSinceEpoch,
          id: json['uniqueId'],
          remoteId: json['fromClientUid'],
          status: types.Status.seen,
          uri: json['fileUrl'],
          name: json['fileName'],
          size: 0, // eg: 0
          metadata: metadata,
        );
      case 'TIP':
        return types.CustomMessage(
          author: types.User(id: json['fromUid']),
          createdAt: createdAt.millisecondsSinceEpoch,
          id: json['uniqueId'],
          remoteId: json['fromClientUid'],
          status: types.Status.seen,
          metadata: metadata,
        );

         */
      default:
        throw Exception('Unsupported message type');
    }
  }

**Comment by demchenkoalex** [comment]
yes, looks good! for the default don't throw `Exception('Unsupported message type');` but return a types.UnsupportedMessage with some generated unique id - this way when you update your app with a new message type and start sending it from backend, users on old app versions will not get crashes, but `UnsupportedMessage` for which you could build like a text saying please update to the newer version to see this message.

**Comment by zengchanghuan** [comment]
Thank you so much.You are so nice.

**Comment by zengchanghuan** [comment]
Thank you so much.You are so nice.

**Comment by zengchanghuan** [comment]
Thank you so much.You are so nice.

**Comment by zengchanghuan** [comment]
I want to give you a Sponsors,but I don't no how to do it.

**Comment by zengchanghuan** [comment]
I want to give you a Sponsors,but I don't no how to do it.

**Comment by demchenkoalex** [comment]
I'm good thanks! Good words are enough :)
