### ISSUE TITLE
Changing message status to seen , distorts the UI, in release mode

### ISSUE THREAD

**Issue by hitashaRajesh** [flyerhq/flutter_chat_ui#504]
# General

## What bug do you experience? 🐞
When a message a marked read via socket event , the chat ui shows a grey box at the top . It works fine in debug mode, but the issue occurs in release mode after upgrading to flutter 3.13.5

## How can it be reproduced? 🤔
Below is the code snippet that causes the issue.

for (int i = 0; i < chatList.length; i++) {
            chatList[i] = chatList[i].copyWith(status: chat_type.Status.seen);
          }

## What behavior is expected? 💡
The UI should not distort when chat list is modified.

<br />

# Extras

## Screenshots or videos 📸
![Screenshot 2023-10-06 at 3 38 41 PM](https://github.com/flyerhq/flutter_chat_ui/assets/147150338/b58d7a26-fc0e-45e8-8ad7-ee80ac8980b6)

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
for (int i = 0; i < chatList.length; i++) {
            chatList[i] = chatList[i].copyWith(status: chat_type.Status.seen);
          }

```

<br />

# Environment info
flutter: 3.13.5
flutter_chat_ui: ^1.6.6

<br />

# Platform

Device : Chrome,Safari

<br />

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
Oof this looks bad. I am currently re-designing the whole library from scratch cause it became so bloated I hardly can even fix anything. Hopefully you can find a solution by forking or using other libraries, because I am finally focused on doing a nice thing and chasing this in the spaghetti code I have now here will kill me :/

**Comment by demchenkoalex** [comment]
first alpha of `v2` is released so hopefully not an issue anymore, but I still need to bring back statuses :)
