### ISSUE TITLE
How to use nextMessageInGroup without previous message?

### ISSUE THREAD

**Issue by kornha** [flyerhq/flutter_chat_ui#505]
Hello 👋 

I am trying to use `nextMessageInGroup` to make the bubbles cleaner when grouped. However, in order to render appropriately I need the previous message in group status too, (as I don't know if the previous message is in a group when rendering the following message. I could try and calculate this based on the previous item's `nextMessageInGroup` but this is not possible as `nextMessageInGroup` is precalculated in reverse order. Any thoughts? Maybe add an optional previousMessageInGroup flag?

Example: 
<img width="382" alt="image" src="https://github.com/flyerhq/flutter_chat_ui/assets/5386694/25568df2-238d-4afe-81f6-686244c15d49">

**Comment by demchenkoalex** [comment]
Hey! 

I am not sure why it was done that way, but I remember that logic there is quite complicated and is pretty bad. I am currently working on a complete re-design of the library from the ground up having all the knowledge I gathered maintaining this - and handling of this type of effect should be much simpler there.

As of right now I will not be able to do anything unfortunately, cause that logic is a core part of v1 solution and any changes there will result in more bugs I guess.

**Comment by demchenkoalex** [comment]
all this spaghetti is removed in `v2`. Currently there is no grouping, but I will see if I could add it back in a simpler way.
