### ISSUE TITLE
some Feature request

### ISSUE THREAD

**Issue by cxcel** [flyerhq/flutter_chat_ui#506]
The functions that need to be added are as follows:
1. Add chat list function, such as messagelist in aurora-imui
2. Add video call function and corresponding UI
3. Add voice chat function and UI

Some similar projects:
https://github.com/jpush/aurora-imui.git
https://github.com/hatemragab/v_chat_sdk.git
https://github.com/TencentCloud/chat-uikit-flutter
https://github.com/Tauseef-Hilal/WhatsUp

**Comment by demchenkoalex** [comment]
Hey!

Can you elaborate on this one please "Add chat list function, such as messagelist in aurora-imui"? what is a chat list? like a list of all of your available conversations?

**Comment by demchenkoalex** [comment]
all this features are in backlog except first one which was not elaborated on
