### ISSUE TITLE
There is hard coded margin added for Message widget which should be configurable 

### ISSUE THREAD

**Issue by ajaykachhawa** [flyerhq/flutter_chat_ui#507]
# There is hard coded margin added for Message widget which should be configurable.

## What bug do you experience? 🐞
Getting much left right padding/margin for Chat messages, specially in small mobile device. After checking in code I found, there is some hard coded margin added. We should make it configurable.

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Step 1. Open the Chat widget in some small size device.
Step 2. Send some message in Chat widget
Step 3. Notice the left/right margin

## What behavior is expected? 💡
Left/Right margin should be configurable 

<br />

# Extras

## Screenshots or videos 📸
![File (2)](https://github.com/flyerhq/flutter_chat_ui/assets/20455140/3288ceb0-e2d0-422a-99b2-2fcd4429a8cf)

## Code snippets 📝
![Capture112](https://github.com/flyerhq/flutter_chat_ui/assets/20455140/5b9ca123-7028-404a-bbed-f7251f4e1be9)

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: 3.7.12
flutter-chat-ui: 1.6.6

<br />

# Platform

Device - Small size Android/iOS device

<br />

<!-- Thank you for making us better 🤝--!>

**Comment by demchenkoalex** [comment]
Hey!

I know this is bad so I am currently working on a v2 complete re-design of the library, that will be more performant and customisable. For now, if you still want to use this, can you please fork and change there. Thanks!

**Comment by nikorehnback** [comment]
@demchenkoalex any idea when the v2 will be available?

**Comment by demchenkoalex** [comment]
I am currently very actively working on it (you could see on a `v2` branch) currently testing new architecture against examples with api, firebase and chatGPT, need to make sure it works for everything. Taking my time there cause I don't want to re-write it again in the future. I still see cases when I am pretty much stuck and don't know what to do (I would love some experienced Flutter engineer helping me, but don't know anyone personally) so many times I said I finally have it and then I would be stuck another month cause I could not do updating message like chat gpt or whatever. Hence hard to tell the exact date. That being said, as soon as I have working example for all 3 cases I will open an issue with exact features implemented and progress will be more public. Will probably release an alpha as well then.

**Comment by user425846** [comment]
> I am currently very actively working on it (you could see on a `v2` branch) currently testing new architecture against examples with api, firebase and chatGPT, need to make sure it works for everything. Taking my time there cause I don't want to re-write it again in the future. I still see cases when I am pretty much stuck and don't know what to do (I would love some experienced Flutter engineer helping me, but don't know anyone personally) so many times I said I finally have it and then I would be stuck another month cause I could not do updating message like chat gpt or whatever. Hence hard to tell the exact date. That being said, as soon as I have working example for all 3 cases I will open an issue with exact features implemented and progress will be more public. Will probably release an alpha as well then.

Hi, is there any update on this?

**Comment by demchenkoalex** [comment]
still solving issue with images being re-loaded and jumping all the time after id change, but found out I could do custom image provider to work around the issue, so doing it now. Then I wanted to try to introduce cubits to manage messages state to make UI stateless and a bit more clean. And then back to testing against api, firebase and chat GPT and if done I will open an announcement issue and close all these where people ask for updates.

**Comment by user425846** [comment]
Thanks for the update. Is it possible to keep it state management agnostic?
I and many others use riverpod or full bloc for state management and it
would be great if it doesnt directly depend on cubits.

Alex ***@***.***> schrieb am Fr. 22. März 2024 um 07:10:

**Comment by demchenkoalex** [comment]
but it would be for internal state only, is this a problem? if you use bloc then it is the same package, you see a problem if someone uses riverpod and they don't want bloc as a dependency?

**Comment by demchenkoalex** [comment]
no hardcodes in `v2` anymore
