### ISSUE TITLE
Header to images.

### ISSUE THREAD

**Issue by BijSven** [flyerhq/flutter_chat_ui#510]
Hey! I want to show images in the chat, but i have a system that the image url is protected and only can be accessed by the right user with a UserID... Is there a way to change that?

**Comment by demchenkoalex** [comment]
Hey! This is a unique use case, I think you will have to provide your own image message implementation (I believe I have `imageMessageBuilder`) where you can access image message data and check if current user is able to see it, and if not, build empty widget or some placeholder

**Comment by BijSvenNL** [comment]
Ty
