### ISSUE TITLE
How to disable markdown in text message?

### ISSUE THREAD

**Issue by godzilla35** [flyerhq/flutter_chat_ui#513]
Hi

I want to disable markdown in messages.
For example, I write a message `~hello~` but it's shown like ~hello~ .
I don't want to get rid of tilde.

I'd greatly appreciate it if you could tell me how.

**Comment by demchenkoalex** [comment]
Hey!

I think passing `TextEditingController` that does nothing to the `inputOptions` will do the trick. According to the code

```dart
  /// Custom [TextEditingController]. If not provided, defaults to the
  /// [InputTextFieldController], which extends [TextEditingController] and has
  /// additional fatures like markdown support. If you want to keep additional
  /// features but still need some methods from the default [TextEditingController],
  /// you can create your own [InputTextFieldController] (imported from this lib)
  /// and pass it here.
  final TextEditingController? textEditingController;
  ```
  
  so if you pass `inputOptions: InputOptions(textEditingController: TextEditingController())` it should kill markdown transformation

**Comment by godzilla35** [comment]
As you say, the text input window works as intended. But markdowns still apply to message bubbles. 

Perhaps the pattern below applies.
```
static PatternStyle get lineThrough => PatternStyle(
        '~',
        RegExp('~[^~]+~'),
        '',
        const TextStyle(decoration: TextDecoration.lineThrough),
      );
```

I used TextMessage class as below. 
```
import 'package:flutter_chat_types/flutter_chat_types.dart' as types;

types.TextMessage(
          author: types.User(id: sender.toString()),
          createdAt: DateTime.now().millisecondsSinceEpoch,
          id: const Uuid().v4(),
          text: data,
        );
```
Is there something wrong?

**Comment by godzilla35** [comment]
I solve the problem by passing custom `textMessageBuilder : `
