### ISSUE TITLE
Changing time Formats

### ISSUE THREAD

**Issue by kwamerex101** [flyerhq/flutter_chat_ui#52]
Please is it possible to change the time formate on the header from 24 to 12 hour clock?

**Comment by AndreHaueisen** [comment]
#51 Covers that I think

**Comment by demchenkoalex** [comment]
Yes, thanks @AndreHaueisen :) also, added additional `customDateHeaderText` which can return an arbitrary string for the date header, allowing returning texts like "Today", "Yesterday" if needed.

@kwamerex101 please check new `customDateHeaderText`, `dateFormat` and `timeFormat`. Documentation comments are in the code. Released in [v1.1.5](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.5).

**Comment by kwamerex101** [comment]
thank you for the response would check it and feedback.

**Comment by AndreHaueisen** [comment]
Awesome! Thank you 🍻
