### ISSUE TITLE
pumpAndSettle times out when testing chat feature using Patrol library

### ISSUE THREAD

**Issue by k00na** [flyerhq/flutter_chat_ui#522]
### Issue

We are using Patrol library for testing our chat feature built with the `flutter_chat_ui` library. We are experiencing a `pumpAndSettle` timeout in our automated tests after the Chat widget gets rendered.

### Environment

- Flutter Chat UI version: flutter_chat_ui: ^1.6.9
- Flutter version: 3.13.1
- Testing on: [Android]
- Patrol library version: patrol: ^2.3.1

### Steps to Reproduce

1. Set up a bottom navigation bar with multiple tabs, including a chat feature tab.
2. Use the Patrol library to automate UI testing.
3. Attempt to navigate to the chat tab during testing.

### Expected Behavior

The test should navigate to the chat tab and continue to perform subsequent actions without any timeouts or freezes.

### Actual Behavior

Once the test navigates to the chat feature tab, it stops responding, and any subsequent action results in a `pumpAndSettle timed out` error.

### Error log 

```
The following assertion was thrown running a test:
	pumpAndSettle timed out
	
	When the exception was thrown, this was the stack:
	#0      WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:702:11)
	<asynchronous suspension>
	#1      TestAsyncUtils.guard.<anonymous closure> (package:flutter_test/src/test_async_utils.dart:114:7)
	<asynchronous suspension>
```

### Additional information
- This issue does not occur when the Chat widget is replaced with any other widget.
- The Chat widget was stripped of all our custom widgets to make sure that our custom widgets aren't causing the freeze,
- The AppBar presence in the chat feature cannot be detected post-navigation.
- Various workarounds have been attempted, including using different pumpAndSettle() configurations, introducing Future.delayed(), and tapping different UI elements, but the issue persists.

### Chat widget code 
```
 return Scaffold(
      appBar: AppBar(),
      body: SafeArea(
        child: BlocBuilder(
          bloc: context.watch<OurChatCubit>(),
          builder: (context, OurChatState state) {


            return Chat(
              messages: state.chatLibMessages,
              user: humanUser,
              dateHeaderBuilder: (time) => Text("timestamp"),
              bubbleBuilder: (child, {required message, required nextMessageInGroup}) {
                return Text("our text widget);
              },
              customBottomWidget: Text("dummy widget for input"),
              onSendPressed: (_) {}, // this line is required by the lib
            );
          },
        ),
      ),
    );
```

### The test code: 

Tries to switch between the tabs. Whole tests break once we render Chat widget. 

```
void main() {
  patrolTest(
    config: const PatrolTesterConfig(settleTimeout: Duration(seconds: 18)),
    'Switches to chat tab and then try to go back',
    nativeAutomation: true,
    ($) async {
      mainStaging.main();
      await $.pumpWidgetAndSettle(const OurApp());
      await $(K.someCustomScrollView).waitUntilExists();
      await $(K.chatBottomNavItem).tap();
      await $.pump();
      await $(K.homeBottomNavItem).tap();
    },
  );
}

```

### Request for Assistance

Could you please assist us in identifying the cause of this timeout? We suspect it could be related to the Chat widget's interaction with the testing framework but have been unable to pinpoint the exact problem or a solution.

### Flutter doctor -v output 
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F770820d darwin-x64, locale en-GB)
    • Flutter version 3.13.1 on channel stable at /Users/igor/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (3 months ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/igor/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/igor/Library/Android/sdk/platform-tools
    • Java binary at: /Applications/Android Studio 3.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.13.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 2022.3)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.76.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.1.0 (API 27) (emulator)
    • macOS (desktop)                    • macos         • darwin-x64     • macOS 13.4.1 22F770820d darwin-x64
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 119.0.6045.123

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by demchenkoalex** [comment]
Hey, can you try main branch? just latest from GitHub?

**Comment by k00na** [comment]
@demchenkoalex , good news: I can confirm that the Patrol tests do NOT break after importing the `flutter_chat_ui` dependency as suggest:


```
  flutter_chat_ui:
    git:
      url: https://github.com/flyerhq/flutter_chat_ui
      ref: main
  #flutter_chat_ui: ^1.6.9
```

**Comment by demchenkoalex** [comment]
I will release a new version today

**Comment by k00na** [comment]
Awesome! Thanks for the help and kudos for creating and maintaining this awesome lib 🙌

**Comment by demchenkoalex** [comment]
Released! lib is not so awesome anymore, my hopes that `v2` will be miles better :)
