### ISSUE TITLE
Should I use inputOptions or customBottomWidget to achieve the effect I need?

### ISSUE THREAD

**Issue by zengchanghuan** [flyerhq/flutter_chat_ui#525]
Our app has custome textTool like this

<img width="203" alt="截屏2023-11-15 23 47 52" src="https://github.com/flyerhq/flutter_chat_ui/assets/2323551/6b091e4b-17c8-4d9e-8abb-27d9ba03ac5f">
Should I use inputOptions or customBottomWidget to achieve the effect I need?

**Comment by demchenkoalex** [comment]
what do you mean by text tool?

**Comment by zengchanghuan** [comment]
<img width="455" alt="截屏2023-11-16 09 23 25" src="https://github.com/flyerhq/flutter_chat_ui/assets/2323551/1fbcf6e0-4ffc-47e3-94b0-ebdc6fce08f5">

I want to modify this UI

<img width="436" alt="截屏2023-11-16 09 23 46" src="https://github.com/flyerhq/flutter_chat_ui/assets/2323551/2dfe618a-ec64-48f5-9ff2-ab3209e67ce4">

to this

**Comment by zengchanghuan** [comment]
I want to modify this UI
<img width="470" alt="截屏2023-11-16 09 26 35" src="https://github.com/flyerhq/flutter_chat_ui/assets/2323551/a77b805a-644a-4041-bf89-a5b57414f015">
to like this
<img width="265" alt="截屏2023-11-16 09 26 55" src="https://github.com/flyerhq/flutter_chat_ui/assets/2323551/d75e88dc-aa81-413c-bb60-0a2c7e21b521">

**Comment by demchenkoalex** [comment]
Well as you mentioned in a question - there are input options and there is theme param for the Chat widget as well, you can easily see what is customisable going to the source code and checking input. 

That being said, if this is absolutely necessary to have buttons layout like you have on a screenshot - then yes, custom bottom widget will allow you to build the whole thing yourself. You can follow the code in the input for any logic you'd like to include.
