### ISSUE TITLE
Japanease character fixed before conversion

### ISSUE THREAD

**Issue by tacsotai** [flyerhq/flutter_chat_ui#533]
I am loving to use this flutter_chat_types.
But I got a trouble.
I am Japanese, and type Japanese with Roma-ji by keybord.
It goes "ｋおんにちは" at trying to type "こんにちは" which means "hello".

<img width="357" alt="Japanease character fixed before conversion" src="https://github.com/flyerhq/flutter_chat_types/assets/80247372/d1222201-7e02-4f1c-a2bb-fbbb82b7ae33">

Do you have any solutions?

**Comment by demchenkoalex** [comment]
Hello! So the problem is that this `ｋ` appears out of nowhere?

**Comment by tacsotai** [comment]
Thank you for your reply.
I will explain the detail.
 
Japanese language have many characters over 3,000 not only 26 like alphabed.
The device of keybord can input directory only ASCII code.
So, it needs some keys to represent one charactor.

For example, if you want to "Hello" in Japanese "こんにちは",
We have to type "konnnichiwa" with [Japanese mode with a conversion program](https://en.wikipedia.org/wiki/Japanese_input_method).
"ko" -> "こ", "nn" -> "ん", "ni" -> "に", "chi" -> "ち", "chi" -> "は".

But, your program seems to fix "k" before typing "o" in typing "ko" before typing Enter key.
I am using Macbook air and test it with "flutter run -d chrome".

Enter key is used to fix the sequence of conversion.
If the sequence is not fixed, we can change the conversion like;
"konnnichiwa" -> "こんにちは" -> "コンニチハ" -> "今日は" 
using space key.
Becase we use not only Hiragana but also Katakana(Easy way of Hiragana) and Kanji(Chinese character).

**Comment by demchenkoalex** [comment]
hey, sorry I lost this reply, had lots of stuff going on at the end of the year. I understand this does not happen in a simple flutter `TextField` right? then it has to do with either `focusNode` (keyboard events) or `InputTextFieldController` that applies formatting like **bold**, _italic_, ~line through~ or `code`. `InputTextFieldController` can be disabled by providing `inputOptions` class with `textEditingController` set to empty `TextEditingController()`. `focusNode` can't be disabled in the code currently. I will make sure to test this in `v2` and probably disable those by default to not ship broken product, with an option to enable it. I understand that with languages like Japanese there might be problems with parsing, like it is done now.

**Comment by tacsotai** [comment]
Thank you for your consideration.
Yes, your undersanding is correct.
> this does not happen in a simple flutter TextField

I am happy to hear good news of "v2".
Thank you for your support in advance.

Anyway I think it is Christmas Holiday isn't it ?
Please take enough rest.

**Comment by tacsotai** [comment]
How is the status ?

**Comment by demchenkoalex** [comment]
I was working on v2 on and off since then, I am finally happy with the foundation and soon will be moving current code to some other branch and merging `v2` to `main`. I will also open an issue to track everything that needs to be done/fixed and will be releasing updates in batches as pre-releases until something usable

**Comment by tacsotai** [comment]
Thank you for your contribution. I am happy the fix will be main soon.

**Comment by demchenkoalex** [comment]
I removed all focus nodes and matches in `v2` is is now plan input without any magic. Hopefully bug is fixed.
