### ISSUE TITLE
BoxConstraints has a negative minimum width.

### ISSUE THREAD

**Issue by kwamerex101** [flyerhq/flutter_chat_ui#54]
Anytime I send only one space as the message, I receive the following error below;

BoxConstraints has a negative minimum width.

flutter_chat_ui: ^1.1.5
Flutter 2.2.2 • channel stable

**Comment by demchenkoalex** [comment]
Sorry for the late reply, was on vacation. Fixed in [v1.1.6](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.6). Can't send spaces anymore.
