### ISSUE TITLE
Why work on this whole code, and in the end not enable users to seemlessly change colors, but force them to create entire themes? This is very unpractical. I also have an issue with the send Icon an dhow the keyboard has to be invisible before it shows up.

### ISSUE THREAD

**Issue by atchoglogilbert** [flyerhq/flutter_chat_ui#540]
## Is your feature request related to a problem?
A clear and concise description of what the problem is or why we should process it.

## What solution would you suggest?
A clear and concise description of what you want to happen. How would it solve the problem of yours?

## Extras
**Screenshots or videos 📸**
If applicable, add screenshots or videos to help explain your feature.

**Code snippets 📝**
If applicable, add code samples to help explain your feature.

```dart
// Your snippet here...
```

## Related issues/PRs
Let us know if this is related to any issue/pull request.

**Comment by nvjoshi2** [comment]
Cmon man, gotta be a little more courteous when your complaining about the FREE software these guys have put a ton of effort into.

**Comment by atchoglogilbert** [comment]
It's just that every developer has their own themes and colors for their apps and being able to set the color should come to mind when releasing the package, but I do apologize, if my words were harsh or hurtful. Coding is stressful sometimes, you know. Thanks, developers, for sharing and have a great rest of your day, Gs.

**Comment by nvjoshi2** [comment]
I do agree with your sentiment, I would prefer if it consumed the app's material theme by default or something like. It sure can be haha. For sure, you have a great rest of your day as well.

**Comment by demchenkoalex** [comment]
> send icon issue

you mean when it is not visible until you write something? There is `sendButtonVisibilityMode` in the `inputOptions` class.

> create entire themes

this is stupid, I agree. I already created a brand new theming mechanism on `v2` branch where you will be able to override full themes or single values, also supporting light and dark themes. If you're interesting how I did that, you could check out that branch. I am working to deliver `v2` as soon as possible, but I want it to be perfect, taking into account 3+ years of feedback, so taking my time there.

**Comment by demchenkoalex** [comment]
send icon is now visible all the time and theming allows to `copyWith` specific values - everything is customisable as well.
