### ISSUE TITLE
Image Loading

### ISSUE THREAD

**Issue by mohitleo03** [flyerhq/flutter_chat_ui#541]
I want to create a Image Loader in chats, can you help me out with some code snippet please

**Comment by demchenkoalex** [comment]
Hey, `v1` does not have this feature and unless someone replies with some custom solution, image loading/caching will be part of `v2` implementation that I am currently working on

**Comment by mohitleo03** [comment]
thanks for the reply @demchenkoalex i also have another doubt, we are creating a social media kind of application, and used this chatting package. i was confused how i can share a post via this package, so basically if a tap on a post it should open the post. shall i use types.CustomMessage?

**Comment by mohitleo03** [comment]
thanks for the reply @demchenkoalex i also have another doubt, we are creating a social media kind of application, and used this chatting package. i was confused how i can share a post via this package, so basically if a tap on a post it should open the post. shall i use types.CustomMessage?

**Comment by demchenkoalex** [comment]
what do you mean by `post`? is it like a message? then yes, custom message is your friend, you can have any data there and you can build anything inside

**Comment by demchenkoalex** [comment]
image loading is part of images in `v2`
