### ISSUE TITLE
Unable to load asset ( icon-send.png). Whenever i try to write something for every letter the new letter goes to newline 

### ISSUE THREAD

**Issue by Prasiddha777** [flyerhq/flutter_chat_ui#545]
# General

## What bug do you experience? 🐞
Provide a clear and concise description of what the bug is.

## How can it be reproduced? 🤔
A few steps to define where does the bug occur.
Step 1. ...
Step 2. ... etc.

## What behavior is expected? 💡

<br />

# Extras

## Screenshots or videos 📸
If applicable, add screenshots or videos to help explain your problem.

## Code snippets 📝
If applicable, add code samples to help explain your problem.

```dart
// Your snippet here...
```

<br />

# Environment info

Please specify the flutter, flutter-chat-ui versions.

flutter: ...
flutter-chat-ui: ...

`flutter doctor -v` output 👇

```sh
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): ...

OS version (e.g. iOS 14.5, Android 11): ...

<br />

# Additional context

<!-- Thank you for making us better 🤝--!>

**Comment by Prasiddha777** [comment]
![image](https://github.com/flyerhq/flutter_chat_ui/assets/53443661/de027afa-fcc8-485e-990b-a4102b4c5ca3)

**Comment by demchenkoalex** [comment]
please provide some code, because I just recently ran the example project and I didn't see any issues there

**Comment by thiagosalvatore** [comment]
I'm facing the exact same error. I copied and pasted the example from the tutorial, nothing different

**Comment by YashMakan** [comment]
it's not necessarily a bug. To resolve it, try stopping and rebuilding the app. In my experience, using the package after hot reloading triggered this issue. Make sure to rebuild the app without hot reloading, and that should fix the problem.

**Comment by demchenkoalex** [comment]
`v2` does not use assets anymore and input is just a flutter input without any magic like in `v1` - so hopefully not an issue anymore.
