### ISSUE TITLE
Make it possible to customize the chat bubbles width

### ISSUE THREAD

**Issue by GioMand** [flyerhq/flutter_chat_ui#549]
It would be nice to allow the developer to manually set the width of chat bubbles in cases such as the component being used for web instead of mobile and a width of 440 could be limiting.

**Comment by ikaushalmartin** [comment]
I guess developer can directly change the width from the code according to his need. Isn't it?

**Comment by ikaushalmartin** [comment]
I guess developer can directly change the width from the code according to his need. Isn't it?

File - chat_theme.dart
![image](https://github.com/flyerhq/flutter_chat_ui/assets/72342211/585e6915-de34-4ee9-a455-0bd881870531)

**Comment by demchenkoalex** [comment]
I think maybe it wasn't released? need to do a release then

**Comment by GioMand** [comment]
Yeah, it actually wasn't released yet, I checked for it on the "chat_theme" file of my 1.6.10 version imported by simply adding the library name on pubspec. Guess I could solve this by specifying the git ref tho?

**Comment by GioMand** [comment]
As you prefer :) In the meanwhile I fixed it importing the specific commit, but of course a proper release would be hugely appreciated :pray: Thank you a lot for the availability.
