### ISSUE TITLE
Undefined Chat argument `isLeftStatus` is used in the example project

### ISSUE THREAD

**Issue by noaonoszko** [flyerhq/flutter_chat_ui#550]
# General

## What bug do you experience? 🐞
In https://github.com/flyerhq/flutter_chat_ui/commit/0b2db7ba2f96c24b23585c2ab8bb41413d2f6f8f, the `isLeftStatus` argument seems to be both added to the example project and the source code. Hence, when I use the release version of flutter_chat_ui and copy `example/lib/main.dart` I get an error in the editor saying the parameter `isLeftStatus` is undefined. 

I guess it would be good to not use this argument in the example until it exists in a release version of the package?

## How can it be reproduced? 🤔
Create a new flutter project and use the `example/lib/main.dart` file.

## What behavior is expected? 💡
No error in the editor.

<br />

# Environment info
flutter: 3.16.8
flutter-chat-ui: 1.6.10

`flutter doctor -v` output 👇

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.8, on macOS 14.2.1 23C71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.72.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

<br />

# Platform

Device (e.g. Android emulator, iOS simulator, Samsung Galaxy S21): iPhone 12 Mini

OS version (e.g. iOS 14.5, Android 11): iOS 16.5.1

<br />

**Comment by demchenkoalex** [comment]
Hey, probably some PR I merged and didn't see that this was used in the example, I should remove that. I will check if I have enough features to do a release.
