### ISSUE TITLE
Is it possible to scroll to the first message but without `ScrollToUnreadOptions`

### ISSUE THREAD

**Issue by demchenkoalex** [flyerhq/flutter_chat_ui#557]
### Discussed in https://github.com/flyerhq/flutter_chat_ui/discussions/555

<div type='discussions-op-text'>

<sup>Originally posted by **TJMusiitwa** February  5, 2024</sup>
We already have the amazing scroll to unread feature in the library which is amazing. 
However, for the implementation I am trying to get, I would like to open a text chain transcript to the first message without showing the **"Unread Messages"** widget i.e. Instead of `ScrollToUnreadOptions` there is like `scrollToFirstMessage:true`

Is there any way possible within the confines of v1 of this library to do so. 

`ScrollToUnreadOptions` is very, very close to what I would need but if there was a way to remove the unread messages widget and open/scroll to the very first message.

Thanks</div>

**Comment by TJMusiitwa** [comment]
Thank you for adding this small feature. Looking forward to v2

**Comment by demchenkoalex** [comment]
reverting this - I will pick this from discussions, not issues. Closing here.
