### ISSUE TITLE
Get to know the height of the input widget depending device

### ISSUE THREAD

**Issue by SwiftyFlow** [flyerhq/flutter_chat_ui#561]
The title is pretty self-explanatory but here is why...

I want the user to be able to write something along picking an image.

I have to offset the image preview with its clear button above the input widget but using stack + padding makes it hard as I don't know the height of the input widget. It looks good on iP14 Pro but overlapped on iP8.

Now writing that and as I already don't like the fact that it's covering the last message(s), I'm going to try to pretend it's a custom message and come back to advise if this approach solves it.

I'd still be curious to know if I can get the right input widget height...

**Comment by demchenkoalex** [comment]
yeah this was not originally planned so no solution available.. will be looking into this with `v2` as well

**Comment by demchenkoalex** [comment]
height of the input widget is being calculated in `v2` by default.
