### ISSUE TITLE
Image sending  Empty Bubble displayed (BUG)

### ISSUE THREAD

**Issue by muthuremo** [flyerhq/flutter_chat_ui#563]
Hello 👋 

**While sending the Image empty Bubble is displayed but on the API i have received the Image uri but on the UI  not displayed go back and come again to the chatpage  image displayed can u guys help this**  

  Another exception was thrown: BoxConstraints has a negative minimum width.
  Another exception was thrown: RenderBox was not laid out: _RenderEditableCustomPaint#f0c26 NEEDS-LAYOUT NEEDS-PAINT
![chatimage](https://github.com/flyerhq/flutter_chat_ui/assets/135421559/35af4a73-462f-44ec-a4a1-f7c6c4e708fc)

**Comment by demchenkoalex** [comment]
Hey! How do you send your image exactly?

**Comment by muthuremo** [comment]
Hi @demchenkoalex 
I used the Bubble Builder  and in the condition i use the imagemessage
else if (message is types.ImageMessage) 
      {
        return Bubble
        (
          child: Stack
          (
            alignment: AlignmentDirectional.topEnd,
            children: 
            [
              Column
              (
                children: 
                [
                  Image.network
                  (
                    message.uri,
                    fit: BoxFit.cover,
                  ),
                ],
              ),
              Positioned
              (
                bottom: 0,
                right: 8,
                child: Text
                (
                  formattedDateTime,
                  style: const TextStyle
                  (
                    fontSize: 10,
                    color: Colors.grey,
                  ),
                ),
              )
            ],
          ),
        );
      }

**Comment by muthuremo** [comment]
> Hey! How do you send your image exactly?

Hi @demchenkoalex
I used the Bubble Builder and in the condition i use the imagemessage
else if (message is types.ImageMessage)
{
return Bubble
(
child: Stack
(
alignment: AlignmentDirectional.topEnd,
children:
[
Column
(
children:
[
Image.network
(
message.uri,
fit: BoxFit.cover,
),
],
),
Positioned
(
bottom: 0,
right: 8,
child: Text
(
formattedDateTime,
style: const TextStyle
(
fontSize: 10,
color: Colors.grey,
),
),
)
],
),
);
}

**Comment by muthuremo** [comment]
> Hey! How do you send your image exactly?

 using the send_media(path,mediatype )  function has my API so that url is used on the Bubblebuilder to display the ImageMessage()

**Comment by muthuremo** [comment]
Without Using the BubbleBuilder  also it gets the empty bubble on the screen image is not rendering why it happening and is there any issue 
gets ERROR like this

Another exception was thrown: BoxConstraints has a negative minimum width.
Another exception was thrown: RenderBox was not laid out: _RenderEditableCustomPaint#7c30b NEEDS-LAYOUT NEEDS-PAINT

**Comment by demchenkoalex** [comment]
does `example` work for you? I have predefined messages json that contains some network images - https://github.com/flyerhq/flutter_chat_ui/blob/main/example/assets/messages.json

I understand that you just use `Image.network` with some URL that your backend returns? maybe you have an example URL I could use to pass it to the network image, see if it works?

**Comment by muthuremo** [comment]
it comes crtly but in the UI gets empty bubble gets go back and return  gets image rendering from the result.path is not crty doing ? on photo

**Comment by demchenkoalex** [comment]
you also said that without bubble builder image is not rendering.. can you give me an example URL for the image and I will see?

**Comment by muthuremo** [comment]
http://localhost/demo/public/uploads/media//2024/3/4/1709553397.jpg

this is the message.uri  url

**Comment by muthuremo** [comment]
Hi Alex im sorry to say that i made the mistake on i have also used the
Socket in the flutterchatUI that variable name is not matched so that was
the mistake Thanks
