### ISSUE TITLE
Attach emojis to a message?

### ISSUE THREAD

**Issue by YesThatGy** [flyerhq/flutter_chat_ui#568]
## Is your feature request related to a problem?
A clear and concise description of what the problem is or why we should process it.

RCS chat allows end users to attach reactions to a message. EG: Mary can "like" a post, or attach a heart to it, etc. Similar capability exists in social media like Facebook. Does this chat app allow for comparable functionality? 

## What solution would you suggest?
A clear and concise description of what you want to happen. How would it solve the problem of yours?

I might envision a message in a format that includes a reference to another message. EG: ref_message_id or similar. This would allow for adding two features: 1) attaching an emoji as in this request, and 2) quoting another message - another feature this data format would enable that's also common in RCS communications. 

## Extras
**Screenshots or videos 📸**
If applicable, add screenshots or videos to help explain your feature.

Here's a link to a screenshot posted of an RCS conversation with my daughter. Notice the "heart" icon on "My favorite genre is alternative rock". 
http://test.effortlessis.com/Screenshot_20240310-103317.png

**Code snippets 📝**
If applicable, add code samples to help explain your feature.

```dart
// Your snippet here...
```

## Related issues/PRs
Let us know if this is related to any issue/pull request.

**Comment by demchenkoalex** [comment]
this is planned with `v2`. I will open a feature tracking ticket for `v2` when base architecture is done.
