### ISSUE TITLE
Changing "inputPlaceholder" doesn't work.

### ISSUE THREAD

**Issue by walidlasseg** [flyerhq/flutter_chat_ui#569]
### Issue Description

I am encountering an issue while trying to override the input placeholder in the `flutter_chat_ui` package within my Flutter project. Despite following the documentation's instructions, the input hint remains unchanged.

However, the input placeholder remains the default value, and my custom placeholder is not displayed.

Here's a simplified version of my code:

```dart
class MyChatScreen extends State<ChatWidget> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Chat(
        l10n: ChatL10nEn(inputPlaceholder: 'Type a message'),
        // Other parameters...
      ),
    );
  }
}

**Comment by demchenkoalex** [comment]
Hmm I literally took your code and pasted to the example and everything worked, logically it should work as well, according to the code. Maybe code reload broke or something?

![Simulator Screenshot - iPhone 15 Pro Max - 2024-03-16 at 23 32 31](https://github.com/flyerhq/flutter_chat_ui/assets/14123304/a35ea4bd-b889-46b2-ae67-d52d6d4652ff)

**Comment by demchenkoalex** [comment]
`l10n: const ChatL10nEn(inputPlaceholder: 'Type a message'),`
