### ISSUE TITLE
typing indicator in chat with no messages

### ISSUE THREAD

**Issue by abichinger** [flyerhq/flutter_chat_ui#571]
# General

## What bug do you experience? 🐞
The typing indicator is not visible if the `Chat` widget does not contain any messages.

## How can it be reproduced? 🤔
```dart
final _user = const types.User(
  id: '82091008-a484-4a89-ae75-a22bf8d6f3ac',
  firstName: 'Alice',
);

@override
Widget build(BuildContext context) => Scaffold(
      body: Chat(
        messages: [],
        onSendPressed: (_) {},
        user: _user,
        typingIndicatorOptions: TypingIndicatorOptions(
          typingUsers: [_user],
        ),
      ),
    );
```

## What behavior is expected? 💡
The typing indicator should show up.

<br />

# Environment info

flutter: 3.19.3
flutter-chat-ui: 1.6.12

`flutter doctor -v` output 👇

```sh
[✓] Flutter (Channel stable, 3.19.3, on Manjaro Linux 6.6.19-1-MANJARO, locale en_US.utf8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] Connected device (3 available)
[✓] Network resources
```

<br />

# Platform

Device: Desktop
OS version: 6.6.19-1-MANJARO

**Comment by demchenkoalex** [comment]
Hey, probably will wait until `v2`, sorry about that.

**Comment by abichinger** [comment]
No worries, I just reported it because I noticed it while using this awesome package.

**Comment by KoustuvGanguly** [comment]
use typingMode: TypingIndicatorMode.name, it will show.

**Comment by abichinger** [comment]
@KoustuvGanguly  I don't think setting `typingMode` to `TypingIndicatorMode.name` will change anything, because the [default value of `typingMode`](https://github.com/flyerhq/flutter_chat_ui/blob/ad165ec7f727bb327e3ff0a51d1b8b11110194e8/lib/src/widgets/typing_indicator.dart#L467) is already `TypingIndicatorMode.name`

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/191 - I will have to re-do typing indicator for `v2` and I will make sure to test it without messages.
