### ISSUE TITLE
About customDateHeaderText

### ISSUE THREAD

**Issue by muthuremo** [flyerhq/flutter_chat_ui#573]
Hi here is my Question if  i dont't want to display the date on the header insted they need to display their  text from API  like on the middle  

 how to display it like this insted of customDateHeaderText?

 This image is a  example whatsapp security message bubble at the middle  
 ![aid8204378-v4-728px-Chat-Securely-on-WhatsApp-Step-3](https://github.com/flyerhq/flutter_chat_ui/assets/135421559/c8f5c252-53ea-4151-8835-c94452bc0b92)

how to display it like this insted of customDateHeaderText

**Comment by demchenkoalex** [comment]
Hey, I think might not be supported in `v1` - will definitely add in `v2`.

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/98 - will bi picking tasks from Discussions.
