### ISSUE TITLE
Is there any way to display message start from top?

### ISSUE THREAD

**Issue by mx-dever** [flyerhq/flutter_chat_ui#575]
Hello 👋 
I want to display a new chat message starting from the top,  but now the message starts from the bottom, and  I can not find any API to configure this feature.

Except like this:
![WX20240320-094612@2x](https://github.com/flyerhq/flutter_chat_ui/assets/12857857/bafee79c-df7b-490a-b41d-4534e1e7cba0)

now:
![WX20240320-094938](https://github.com/flyerhq/flutter_chat_ui/assets/12857857/2aeddbf5-3e5d-48b4-8233-2c41723964b8)

**Comment by demchenkoalex** [comment]
Hey! It is impossible to do in `v1` and in `v2` it will be a default behaviour.

**Comment by rahulevs** [comment]
How we can do that can you please help me in the same?

**Comment by iceycc** [comment]
Is there a way to do that in v1 。

**Comment by demchenkoalex** [comment]
no, it would break the whole code at its core unfortunately :/

**Comment by demchenkoalex** [comment]
default in `v2`
