### ISSUE TITLE
How to change the word "is typing" in TypingIndicatorOptions

### ISSUE THREAD

**Issue by longnh2k1** [flyerhq/flutter_chat_ui#576]
Because my application has many different languages, the word "is typing" in TypingIndicatorOptions can be replaced. Please update the package for me.

Thank you very much.

**Comment by Ggre55** [comment]
i think this solves it [v1.6.11](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.6.11)

**Comment by demchenkoalex** [comment]
added translations for all languages in `v1.6.13`
