### ISSUE TITLE
Padding of text

### ISSUE THREAD

**Issue by ngocnguyenbk** [flyerhq/flutter_chat_ui#581]
Hello everyone, I want to reduce the text padding compared to Bubble.
I've researched a lot and haven't found a way. There doesn't seem to be any option for this.
If anyone knows please show me how to do it.
Thank you.
![image](https://github.com/flyerhq/flutter_chat_ui/assets/22522452/d71c7253-6020-4d11-a205-ddac30dbd7be)

My code
![image](https://github.com/flyerhq/flutter_chat_ui/assets/22522452/bbe5f785-66a0-48bb-8509-0eada42f574c)

**Comment by demchenkoalex** [comment]
`messageInsetsVertical` in theme?

**Comment by ngocnguyenbk** [comment]
> `messageInsetsVertical` in theme?

Oh, I did it. Thank you very much.
