### ISSUE TITLE
Janky scroll on chat list

### ISSUE THREAD

**Issue by RockStone** [flyerhq/flutter_chat_ui#591]
I'm having a number of janky issues tested on my android with Impeller enabled when scrolling on the chat list. A performance analysis seems to point to the overhead of loading `Message` and `TextMessage`. I'm curious if there's any chance we may optimize both classes?

![image](https://github.com/flyerhq/flutter_chat_ui/assets/1649569/162c4a94-bf33-430f-95d8-8a9eb35e9aea)
![image](https://github.com/flyerhq/flutter_chat_ui/assets/1649569/1d3f77b4-d754-4421-a439-f48c9c5c09e7)

**Comment by demchenkoalex** [comment]
yeah, `v1` is quite bad performance wise. When I started it I had little Flutter knowledge, and the code is just not good, so it is hard to fix it. I started `v2` from scratch to focus on extendability and performance, currently working on a new cache package I need to finish `v2` (available packages don't meet my needs).

**Comment by RockStone** [comment]
Thanks Alex. Do look forward to the updates!

**Comment by demchenkoalex** [comment]
Thank you! Me too, want to clear those open issues haha. I will close this since performance is core part of `v2` release and this issue will be n/a there.
