### ISSUE TITLE
Using ChatList Component as a Standalone Widget

### ISSUE THREAD

**Issue by axornam** [flyerhq/flutter_chat_ui#594]
Hello, is it possible to use the ChatList Widget as a standalone replacement for a typical ListView or ListView.Builder. I'm currently retrieving data from firestore using StreamBuilder and returning a ListView. I'm currently not able to Customize the default Chat Widget to meet a requirement. I Get an Error When I try to do this.

**Comment by demchenkoalex** [comment]
Hey! I did not plan `ChatList` to be used as standalone. I would suggest to copy it to your project and customise to meet your requirements then.

**Comment by demchenkoalex** [comment]
possible write your own chat list in `v2`, if needed.
