### ISSUE TITLE
the send button doesnt appear on my phone till i press symbols or space also in my emulator but it works perfectly with the pc keyboard on the emulator

### ISSUE THREAD

**Issue by joeymeb** [flyerhq/flutter_chat_ui#601]
the send button doesnt appear on my phone till i press symbols or space also in my emulator but it works perfectly with the pc keyboard on the emulator

**Comment by mulderpf** [comment]
I have noticed the same.  I assume it was the emulator as it seems fine on my phone.

**Comment by joeymeb** [comment]
it doesnt work on my phone correctly?

**Comment by demchenkoalex** [comment]
I suggest using `inputOptions: InputOptions()` with `sendButtonVisibilityMode` set to `always`. I don't understand why this simple logic `_sendButtonVisible = _textController.text.trim() != '';` would not work on some devices..

**Comment by SnowyTusk** [comment]
![image](https://github.com/flyerhq/flutter_chat_ui/assets/6566940/1e518e82-c54f-40d6-8070-db30aab97dde)
That's the only way it works properly. Is checking "isComposingRangeValid" really necessary?

**Comment by demchenkoalex** [comment]
no idea where it came from lol, seems like a bug to me, it shouldn't be there.

**Comment by SnowyTusk** [comment]
> no idea where it came from lol, seems like a bug to me, it shouldn't be there.

Then we are waiting for a fix from you in the update.

**Comment by demchenkoalex** [comment]
was introduced with this PR, I tested Japanese characters as well, did not observe the behaviour mentioned in the PR. Maybe the issue was fixed within the Flutter itself. Anyway, removed this return cause it probably does more harm than good.

**Comment by demchenkoalex** [comment]
published [v1.6.14](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.6.14)
