### ISSUE TITLE
Need to add CupertinoContextMenu to the chat bubble for the function of copying chat content.

### ISSUE THREAD

**Issue by longnh2k1** [flyerhq/flutter_chat_ui#604]
How do I add CupertinoContextMenu to the chat bubble to copy the chat content.
Thanks for creating this great package, if possible, I hope you can add the CupertinoContextMenu feature!
Link: https://api.flutter.dev/flutter/cupertino/CupertinoContextMenu-class.html
![cupertino-context-menu](https://github.com/flyerhq/flutter_chat_ui/assets/153590374/723dcd3d-127f-45f4-a3e1-b56d5a67eb47)

**Comment by demchenkoalex** [comment]
hey, yeah I am up to adding this, but with the new version already

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/93 - will be picking tasks from Discussions.
