### ISSUE TITLE
How to include edit message feature?

### ISSUE THREAD

**Issue by bs-vinay-parmar** [flyerhq/flutter_chat_ui#605]
onMessageLongPress I am opening a menu with 'edit message' view, on click of that view I have to set message to textinput and let user to edit the message and, then onSend I have to call according socket with check of messageId.
If messageId is there hit 'editMessage' else hit 'sendMessage'

Please help me, how can I achieve that?

**Comment by demchenkoalex** [comment]
Hey! Menu on long press will have to be custom made, there is no support for that atm. To set the message you can use `textEditingController` that is available in the `inputOptions`. I guess you can save some state that you're in the editing mode as well, so when you do `onSend` you would update the existing message and not send a new one. If you would want some indicator about what message is being editing with an option to exit editing mode, check out [this answer](https://github.com/flyerhq/flutter_chat_ui/issues/597#issuecomment-2116979783) that should give you and idea how to implement some kind of a placeholder on top of the input.
