### ISSUE TITLE
Removing margin from the input field

### ISSUE THREAD

**Issue by muezz** [flyerhq/flutter_chat_ui#607]
How can I remove the following margin/padding from this input field? I have tried both input margin and padding.

<img width="1108" alt="image" src="https://github.com/flyerhq/flutter_chat_ui/assets/100420605/b7a220cb-5d4e-49b4-9278-7292c03eeb55">

**Comment by demchenkoalex** [comment]
I think these are `safeAreaInsets`, cause input was supposed to be on the bottom of the phone, so safe area is built in. Would `customBottomWidget` work for you? (you can basically copy code from the `Input`) and adjust to your needs, since it is not "standardly" placed. Or you would prefer for me to add an option to remove safe area?

**Comment by demchenkoalex** [comment]
added `usesSafeArea` to the `inputOptions`. Pass it as `false` and these should be gone

**Comment by muezz** [comment]
@demchenkoalex Not sure what you did in the latest update but I dont get the bottom padding at all with my current setup. I only get it on the left and right. 

AND adding `usesSafeArea` as `false` has no effect.

Also, to answer your question, I would prefer it if I did not have to use the builder for something so simple. Padding should not be hardcoded. But if I have to do it, then I will.

<img width="1133" alt="image" src="https://github.com/flyerhq/flutter_chat_ui/assets/100420605/41299da9-5189-4825-a2dc-0b235b186130">

**Comment by demchenkoalex** [comment]
do you have `onAttachmentPressed`? what if you pass `null` there? I don't see any more paddings in the code except from buttons, but they should look inside probably.. you can just open source code for the [Input](https://github.com/flyerhq/flutter_chat_ui/blob/main/lib/src/widgets/input/input.dart#L115) widget to see what looks suspicious to you

**Comment by muezz** [comment]
@demchenkoalex 
I tried passing `null` for `onAttachmentPressed` but that did not help. I took your advice, cloned the repo and ran the example app. I used my own configurations for the chat widget and found the piece of code that "hardcodes" the padding. See the video below. It is a bit blurry as I couldn't upload above 10mb. I hope you can see what I am doing in it.

From what I understand, if `onAttachmentPressed` is not provided and the send icon is not visible, there is a hardcoded padding of 24. I have no need for the attachment callback and the button. And the send icon only becomes visible when I type. I dont see why this should be hardcoded like this. 

https://github.com/flyerhq/flutter_chat_ui/assets/100420605/56efd86e-0d45-4740-8171-16230514e936

**Comment by demchenkoalex** [comment]
yep, got it. I will add an option to change that
