### ISSUE TITLE
Add support of a context to all `*Builder`s

### ISSUE THREAD

**Issue by vasilich6107** [flyerhq/flutter_chat_ui#608]
## Is your feature request related to a problem?
Flutter canonical implemetation of a builder patter includes passing a context through

## What solution would you suggest?
add build context param

## Is there any additional solution to that?
no

**Comment by demchenkoalex** [comment]
> Flutter canonical implementation of a builder pattern

Thanks for letting me know! The code in this repository is not canonical in any way, cause when I wrote it I used react native/ios patterns, since it was the only thing I knew. I will make sure to follow more best practices on a `v2` branch!

**Comment by demchenkoalex** [comment]
if it is a non breaking one, you can :)

**Comment by demchenkoalex** [comment]
default in `v2`
