### ISSUE TITLE
Possible bug report: ScrollController not attached while dismissing chat screen.

### ISSUE THREAD

**Issue by fikretsengul** [flyerhq/flutter_chat_ui#61]
## What bug do you experience? 🐞
I have an issue when I dismiss the chat screen with some messages or when I send a new one (ex. returning back to the chat list screen), flutter throws an error saying that:

"E/flutter (25401): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 152 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views."

## How can it be reproduced? 🤔
Step 1: I first make the related chat API calls then set the messages before the app run.
Step 2: After that when I navigate to the related chat screen, I get the messages from bloc and set them to the messages array in the class with some computations.
Step 3: Send a message. (I don't insert the new message into the array, I just set the listener result to the messages array with the same computations in step 2.)
Step 4: Dismiss the chat screen. Then in the console of vscode this error appears.
Step 5: After that without sending a new message, every time when I open and then dismiss the chat screen this message comes again.

## What behavior is expected? 💡
This error message shouldn't exist.

## Screenshots or videos 📸
Chat list screen: https://i.imgur.com/ZdY0VBU.jpeg
Chat screen: https://i.imgur.com/0KQkI47.jpeg

## Code snippets 📝

The error message and the source code of the error:

`E/flutter (25401): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 152 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (25401): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (25401): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (25401): #2      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:152:12)
E/flutter (25401): #3      _ChatListState._scrollToBottomIfNeeded.<anonymous closure> (package:flutter_chat_ui/src/widgets/chat_list.dart:137:31)
E/flutter (25401): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:315:39)
E/flutter (25401): #5      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (25401): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (25401): #7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (25401): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (25401): #9      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (25401): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (25401): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter (25401): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (25401): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (25401): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (25401): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (25401): 
E/flutter (25401): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 152 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (25401): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
E/flutter (25401): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (25401): #2      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:152:12)
E/flutter (25401): #3      _ChatListState._scrollToBottomIfNeeded.<anonymous closure> (package:flutter_chat_ui/src/widgets/chat_list.dart:137:31)
E/flutter (25401): #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:315:39)
E/flutter (25401): #5      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (25401): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (25401): #7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (25401): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (25401): #9      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (25401): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (25401): #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter (25401): #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (25401): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (25401): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (25401): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)`

```dart
        // Run only for sent message
        if (message.author.id == InheritedUser.of(context).user.id) {
          // Delay to give some time for Flutter to calculate new
          // size after new message was added
          Future.delayed(const Duration(milliseconds: 100), () {
            _scrollController.animateTo(
              0,
              duration: const Duration(milliseconds: 200),
              curve: Curves.easeInQuad,
            );
          });
        }
```

My logic of the chat screen:

```dart
  List<types.Message> _messages = [];
  late types.User _user;

  @override
  Widget build(BuildContext context) {
    return BlocListener<ProfileBloc, ProfileState>(
      listenWhen: (p, c) => p.conversations != c.conversations,
      listener: (context, state) {
        _loadMessages(state.conversations
            .firstWhere((element) =>
                element.conversationId == widget.conversation.conversationId)
            .messages);
      },
      child: Scaffold(
        appBar: PreferredSize(
            preferredSize: AppBar().preferredSize,
            child: ChatAppBarWidget(match: widget.match)),
        body: Chat(
          theme: DefaultChatTheme(
            backgroundColor: Theme.of(context).colorScheme.primary,
            primaryColor: Theme.of(context).accentColor,
          ),
          showUserAvatars: true,
          messages: _messages,
          onAttachmentPressed: _handleAtachmentPressed,
          onMessageTap: _handleMessageTap,
          onPreviewDataFetched: _handlePreviewDataFetched,
          onSendPressed: _handleSendPressed,
          user: _user,
        ),
      ),
    );
  }
  
  Future<void> _loadMessages(List<MessageModel> messages) async {
    final List<types.Message> msgs = [];

    for (final msg in messages) {
      User user;
      if (msg.author == widget.match.partnerId) {
        user = User(
          id: widget.match.user!.userId,
          firstName: widget.match.user!.fullName,
          imageUrl: widget.match.user!.photos[0],
        );
      } else {
        user = User(
            id: _profileBloc.state.user.userId,
            firstName: _profileBloc.state.user.fullName,
            imageUrl: _profileBloc.state.user.photos[0]);
      }

      final message = types.TextMessage(
          author: user,
          id: msg.messageId,
          createdAt: DateTime.parse(msg.creationDate).millisecondsSinceEpoch,
          text: msg.text);

      msgs.add(message);
    }

    msgs.sort((a, b) => b.createdAt!.compareTo(a.createdAt!));

    setState(() {
      _messages = msgs;
    });
  }
```

# Environment info

Flutter with null safety: 2.2.3
Sdk: ">=2.12.2 <3.0.0"
flutter_chat_ui: ^1.1.7

# Platform
Real device Xiaomi Mi 9T Pro with Stock AOSP ROM (Android 11-R)

# Additional context
When I research the issue on StackOverflow I found that:

"Delaying it is not the right solution. Better to use this"
if(pageController.hasClients){
              ....
}

**Comment by demchenkoalex** [comment]
Hi @fikretsengul thanks for the detailed bug description! We will look at it ASAP

**Comment by fikretsengul** [comment]
> Hi @fikretsengul thanks for the detailed bug description! We will look at it ASAP

Thank you for your quick reply and for offering such a beautiful library for free. By the way, I would like to point out that this error does not cause any extra errors or glitches in animations or user interfaces, except for the warning in the VSCode console. Good luck with it.

**Comment by demchenkoalex** [comment]
Released a small fix in [v1.1.8](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.1.8). Didn't test though, but hopefully does the job. If @fikretsengul you can please verify and let me know

**Comment by fikretsengul** [comment]
Sorry for the late response, I'm going to test it now. I'll update this comment.

**Comment by cristaloleg** [comment]
@fikretsengul better to create a new comment, so everyone will get a notification 😉

**Comment by fikretsengul** [comment]
I can confirm that it is now fixed. Thank you again for the effort and quick fix. Have a great day.
