### ISSUE TITLE
How to create new ImageMessage from remote URL

### ISSUE THREAD

**Issue by thomers** [flyerhq/flutter_chat_ui#612]
Hello, what's the best way to create a new ImageMessage from a known remote URL (and the "author" attributes of course)?

Both ImageMessage and PartialImage have "size" as required, so should I do a HTTP "head" first and get the content-length from the response headers? Or is there a better / easier way?

**Comment by thomers** [comment]
Also: How do I refer to an image from the assets bundle for a ImageMessage?

**Comment by demchenkoalex** [comment]
Hey!

`size` property is used only to show the size of the image if image is presented as a file message (when image is too large to be presented inline). You can safely pass 0 there. I will make this optional in `v2`.

As for referring image from local storage, is `FileImage` good enough? See [this code](https://github.com/flyerhq/flutter_chat_ui/blob/63e3c148efcd98922f28a871a2edcef4863d485e/lib/src/conditional/io_conditional.dart#L17) - if `uri` of the image message does not start with the http it will try to use `FileImage` to show it. I use it to show images picked from the phone gallery.

**Comment by thomers** [comment]
Thanks @demchenkoalex , here's a PR to add support for URIs referencing images from the app's "assets" resources.  https://github.com/flyerhq/flutter_chat_ui/pull/619
