### ISSUE TITLE
Low performance 

### ISSUE THREAD

**Issue by Maherov963** [flyerhq/flutter_chat_ui#613]
The chat page too glitchy when there's too messages and the keyboard appears or disappear 

I believe it's because of the resizing of the ui when the keyboard appears or dis...

 I am using the latest version of flutter and the package by the way

**Comment by demchenkoalex** [comment]
yes, performance is a big problem with `v1` that's why I am re-writing everything from scratch on `v2` branch, to make it as performant as possible. Unfortunately there is no easy fix for `v1`, cause overall architecture is not ideal.

**Comment by Maherov963** [comment]
Looking forward to v2 😄

**Comment by demchenkoalex** [comment]
`v2` dev build is live - I focused on performance and as little rebuilds as possible. Hopefully not an issue anymore.
