### ISSUE TITLE
How can I make send button always visible?

### ISSUE THREAD

**Issue by rmControls** [flyerhq/flutter_chat_ui#62]
1) How can I make send button always visible?
2) How to give background color and border radius for input text field like below? (Text field decoration)
![image](https://user-images.githubusercontent.com/27656141/126024365-9378fdf3-9135-46df-bccf-64483158cdc3.png)

**Comment by demchenkoalex** [comment]
Hi, both are not available by design. PRs are open though :)

**Comment by demchenkoalex** [comment]
Closed by #76

**Comment by rmControls** [comment]
I believe the second point is still open.... (Input TextField Decoration)..

**Comment by demchenkoalex** [comment]
Yeah, sorry

**Comment by demchenkoalex** [comment]
Released in [v1.3.2](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.3.2).
