### ISSUE TITLE
"System" messages appearing between chat messages 

### ISSUE THREAD

**Issue by thomers** [flyerhq/flutter_chat_ui#620]
Hello, is there something that I can use to add "system"-messages , like "userXY has joined / left the chat"? 

They should appear between the other messages, scrolling with them etc. 

Thank you!

**Comment by thomers** [comment]
Just realised that there's already a "SystemMessage" type in flutter_chat_types. https://pub.dev/documentation/flutter_chat_types/latest/flutter_chat_types/SystemMessage-class.html

Just for v2, it would be nice to be able to add an icon to it (to be able to signal what kind of system message it is).

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/98 - will be picking tasks from Discussions.
