### ISSUE TITLE
Utilize SDK as ticket support

### ISSUE THREAD

**Issue by ahmadkq** [flyerhq/flutter_chat_ui#622]
How to utilize this SDK as a ticket support and live chat with the admin?

**Comment by demchenkoalex** [comment]
whatever provider you use for the live chat/admin panel must return you messages in some way. Map those messages to the format this package uses and you will see them in the chat. Use your provider sdk/api to send messages. Check the example for the super simple implementation and just add your provider. If you want an async example, you can take a look at example here https://github.com/flyerhq/flutter_firebase_chat_core
