### ISSUE TITLE
Translating the 'Message' in the chat input. Need help.

### ISSUE THREAD

**Issue by MonkeyDrone** [flyerhq/flutter_chat_ui#624]
Hi guys,

I have been trying to find where I can replace the default 'Message' hint text in the chatroom where we type our message.
I've gone through the DefaultChatTheme and went through all the options in inputTextDecoration, none of them replace the 'Message' text which disappears as soon as you start typing. 
How do I change that?

**Comment by demchenkoalex** [comment]
Hey!

It is in the localisation files, you can pass l10n parameter with ChatL10nEn (or language of your chose) class, and then modify text of inputPlaceholder in the localisation class
