### ISSUE TITLE
Ability to disable auto scroll

### ISSUE THREAD

**Issue by JHubi1** [flyerhq/flutter_chat_ui#629]
## Is your feature request related to a problem?
At the moment, the chat view always scrolls to the bottom of the latest message if one is updated. In general, that is great, but there might be a situation in which a different behavior is needed.

## What solution would you suggest?
I'd like to see a property value like `autoscroll` which is set to `true` by default and that toggles the scrolling to the bottom.

**Code snippets 📝**

```dart
Chat(
  messages: messages,
  key: chatKey,
  autoscroll: false
)
```

## Is there any additional solution to that?
The function that scrolls to the bottom is made to an argument, so it can be overwritten with an empty function and the scroll would be disabled as well.

**Code snippets 📝**

```dart
Chat(
  messages: messages,
  key: chatKey,
  onNewMessage: (id) {}
)
```

## Related issues/PRs
Issue #354 mentions the issue, but doesn't go into detail.

**Comment by chechoora** [comment]
Hello, can you give us basic idea on how you gonna do it in v2? We are using v1.6 and we need to emulate ChatGPT and OpenAI bot SSE responses. I am not sure it possible to do it, without forking your package since the issue is not with scrolling, but rather with CustomScrollView. Maybe you can give us an idea. Thanks!

**Comment by demchenkoalex** [comment]
Hey, there is no simple answer, I removed all code and started from scratch :) I already have working SSE responses on `v2` branch. What is left for me is to add some basic customisation for text messages and I will release an alpha version. I hope to do finish it next week. If you can't wait you can try to grab `v2` branch as an example, it will be miles better than what you see on `main`

**Comment by andrew-mezzi** [comment]
Hey @demchenkoalex , thanks for all your work you do on this package, we rely on it heavily. Looking forward to v2, is there any estimate for when you think a PR will be ready?

**Comment by demchenkoalex** [comment]
hey @andrew-mezzi it's live already:) just need to sort out docs/github

**Comment by demchenkoalex** [comment]
example of this is live in v2 https://github.com/flyerhq/flutter_chat_ui/issues/646

**Comment by qasim90** [comment]
@demchenkoalex Is this feature available in V2? If yes, could you share a code snippet? Thanks a lot for this great package btw. Now implementing chat is way easier than ever.
