### ISSUE TITLE
Making TextMessage and other subclasses of class Message extendable by providing a generative constructor

### ISSUE THREAD

**Issue by PenguinBIUBIUBIU** [flyerhq/flutter_chat_ui#631]
##  problem:
I want to add fields to TextMessage by introducing a subclass of TextMessage but failed, because TextMessage provide no generative constructor, only factory constructor , which can't be invoked by its subclass in dart language.

## solution suggestion:
providing a generative constructor for TextMessage and other subclasses of class Message.

Or there is other way of add fields to TextMessage?

**Comment by demchenkoalex** [comment]
for additional fields there is a `metadata` map, so you can put anything there. I will see if extending classes is an option on `v2` branch, not sure.

**Comment by PenguinBIUBIUBIU** [comment]
> for additional fields there is a `metadata` map, so you can put anything there. I will see if extending classes is an option on `v2` branch, not sure.

thanks, looking forward to v2!

**Comment by UsamaKarim** [comment]
Hi, I have a design proposal for customisable and extendable message types. There are pros and cons to this design. At first glance it seems to me that it might not be a breaking change.

Origin: It have been derived form the Stackoverflow post when `Enum` was not available in dart language, but there was a workaround available. https://stackoverflow.com/a/15854550/14028477

## Pros
1. It can be `extends`
2. It has similarity to `Enum`
3. It can be used in serialization/deserialization for use in custom model classes and custom name to any type can be given.

## Cons
1. The previous types has to reimplemented in the extended class as static types of parent class are not accessible from subclass instance
2. It seems verbose

## Code Design

```dart

void main() {
  const messageType = MessageType.video;

  switch (messageType) {
    case MessageType.text:
      print('This is a text message type');
    case MessageType.audio:
      print('This is a audio message type');
    case MessageType.video:
      print('This is a video message type');
  }

  const myMessageType = MyMessageTypes.text;

  switch (myMessageType) {
    case MyMessageTypes.text:
      print('This is a text message type');
    case MyMessageTypes.audio:
      print('This is a audio message type');
    case MyMessageTypes.video:
      print('This is a video message type');
    case MyMessageTypes.image:
      print('This is a image message type');
    case MyMessageTypes.poll:
      print('This is a poll message type');
    case MyMessageTypes.location:
      print('This is a location message type');
  }
}

class MessageType {
  const MessageType._internal(this._value);
  final String _value;

  @override
  String toString() => 'Enum.$_value';

  static const text = MessageType._internal('text');
  static const audio = MessageType._internal('audio');
  static const video = MessageType._internal('video');
}

/// Custom Defined Message Types
class MyMessageTypes extends MessageType {
  const MyMessageTypes._internal(super.value) : super._internal();

// Reimplement original types
  static const text = MyMessageTypes._internal('text');
  static const audio = MyMessageTypes._internal('audio');
  static const video = MyMessageTypes._internal('video');

  // More customisable message types
  static const location = MyMessageTypes._internal('location');
  static const image = MyMessageTypes._internal('image');
  static const poll = MyMessageTypes._internal('poll');
}
```

**Comment by demchenkoalex** [comment]
<img width="480" alt="Screenshot 2024-10-29 at 22 09 46" src="https://github.com/user-attachments/assets/4cc25b5a-00e6-4d3a-b1d0-fbe003b62f5c">

I am now using sealed, freezed classes for `v2` and it is works the best for the package. I don't think extends are possible, so `metadata` map is still something to store additional values in
