### ISSUE TITLE
Is there any way to make messages support something like SSE?

### ISSUE THREAD

**Issue by KylinShinlyLin** [flyerhq/flutter_chat_ui#634]
I need to use this UI framework to create an effect similar to GPT's SSE, but I found that the current API provided by the framework doesn't seem to meet my needs. I'm wondering if there's a way to allow a specific message in the conversation to support SSE modification.

**Comment by demchenkoalex** [comment]
Hey! I am not familiar with this, could you give me some examples? like what a specific message should do?

**Comment by danielwinkler** [comment]
SSE will probably be abstracted into a `Stream<String>` in your code.
I also thought it would be nice to plug in a stream to the text message, but as a workaround you can wrap the Chat widget in a StreamBuilder.
From there you keep all messages the same, and the GPT message will be a text message that gets the stream snapshot data, this way it will build with the GPT effect.

The likely more efficient solution is to use a custom message, and pass in the stream as metadata. Using the `customMessageBuilder` you are able to build a widget that updates whenever there is an update from the stream.

**Comment by demchenkoalex** [comment]
Ah if this is just stream then I already have working example on `v2` branch. Initial release is very soon, I am satisfied with new version quality

**Comment by demchenkoalex** [comment]
`v2` has Gemini example - streaming chunks of text into text message.
