### ISSUE TITLE
Message input box modifications

### ISSUE THREAD

**Issue by rjcalifornia** [flyerhq/flutter_chat_ui#635]
Hi!

Two things:

1. Is there a way to prevent messages to be sent until the other person has responded?
2. Is there a way to send messages only if you tap the button?

**Comment by demchenkoalex** [comment]
Hello!

1. Messages are sent when you are sending them :) so just don't send until you know some message appeared? there is no logic in this package, just UI.
2. It is being send when you tap the send button. Or you mean image/file messages? for this I plan to add an option in v2
