### ISSUE TITLE
When will the v2 version be released?

### ISSUE THREAD

**Issue by zhangheng2022** [flyerhq/flutter_chat_ui#636]

**Comment by demchenkoalex** [comment]
matter of weeks I suppose, almost done now. Keep in mind that v2 will be an alpha release and will not contain every feature of v1, but will be lots faster and easier to contribute to. I hope to pick up all features pretty quickly and then build on top features like replies, reactions, audio messages etc.

**Comment by godilite** [comment]
hope version 2 will allow theming of text color? it seems only main app theme overrides text and no way to for either sender or receiver text to have a color different from global theme text color

**Comment by demchenkoalex** [comment]
update: I was on vacation and already back doing latest touches. I think only theming is left for what I already have and I will be releasing alpha version of `v2` to gather feedback and continue improving it.

**Comment by JJRCSoft** [comment]
@demchenkoalex Thank you for the incredible work and the wonderful project you’re working on. I was wondering if you might be able to share an approximate timeline for v2. Do you expect it to take a few days, weeks, or months? I would greatly appreciate any insight you can provide.

Thank you so much!

**Comment by demchenkoalex** [comment]
like I said above, only some theming left which I try to perfect while the package is still small, if we talk pure work I think I need like 8 hours more. But you know I don't work every day and sometimes normal job takes so much energy, doing open source is the last thing I want in life. I hoped to finish last week, but I worked like 2 hours. Will do some work tomorrow and then, _hopefully_, finish next week. 

Keep in mind that `v2` release is smaller than what you have now, with less features. It is though much more performant, real-life ready and easier to understand/contribute to. Works with AI agents as well. I will expect some community help to quickly return all existing features and finally add something new.

**Comment by demchenkoalex** [comment]
update is here https://github.com/flyerhq/flutter_chat_ui/issues/646
