### ISSUE TITLE
Date has disappeared

### ISSUE THREAD

**Issue by realvee** [flyerhq/flutter_chat_ui#640]
Not sure why but just notice that the date header was disappeared. Or I need to enable that with some attribute? Please help.

**Comment by demchenkoalex** [comment]
did it disappear after package update? can you revert to older version see if it is still there?

**Comment by realvee** [comment]
Hi, sorry for the false report. my bad. Probably regarding my bad data. The date header was there : )

Btw, is there any option to include time on each bubble message?

**Comment by demchenkoalex** [comment]
as of right now no, but it is planned for `v2`. I will soon merge `v2` branch into `main` and do some kind of a public backlog (hopefully with the voting system) and we will be able to prioritise features like that

**Comment by realvee** [comment]
I think this is quite essential for nowadays chat ux. No worries, I managed to modify some little in the lib and with the help of customStatusBuilder, the outcome is quite decent. 

![chattime](https://github.com/user-attachments/assets/8ab6db22-9bff-4527-82cc-829f752e3a87)

Thanks again for your very hard effort and dedication. Really appreciated!
