### ISSUE TITLE
The current user can also display the avatar, and the position can be controlled

### ISSUE THREAD

**Issue by Lazydd** [flyerhq/flutter_chat_ui#643]
![image](https://github.com/user-attachments/assets/eb8a6ef4-7809-4913-a7f5-087fa1dca320)
1. Hope the current user also has an avatar
2. The alignment of the avatar and the bubble can be controlled
![image](https://github.com/user-attachments/assets/89be887f-6a87-4ad8-a05f-1d21efeb32c9)
![image](https://github.com/user-attachments/assets/acb328be-0bc5-4278-a3c4-89d863a42baa)

**Comment by demchenkoalex** [comment]
something to add in `v2`

**Comment by KoustuvGanguly** [comment]
> something to add in `v2`
@demchenkoalex 
same requirement. Hope to get it soon. 

Tried in this way but message bubble height is different based on content so avatar place also changing based on that so not so successful!!

avatarBuilder: (user) {
  return Container(
    child: Transform.translate(
      offset: Offset(-10.0, -90.0), // Adjust the offset as needed
      child: CircleAvatar(
        child: Icon(Icons.person),
      ),
    ),
  );
},

tried  this approch also but all I see blank UI

avatarBuilder: (user) {
  return Stack(
    children: [
      Positioned(
        top: -10.0, // Adjust the offset as needed
        left: 0.0,
        child: CircleAvatar(
          child: Icon(Icons.person),
        ),
      ),
    ],
  );
},

**Comment by demchenkoalex** [comment]
closing in favour of https://github.com/flyerhq/flutter_chat_ui/discussions/658 - will be picking tasks from Discussions.
