### ISSUE TITLE
AvatarImage doesn't always cover userAvatarNameColor circle

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#65]
This is probably much more noticeable on dark themes with bright userAvatarNameColors, but a lot of images, even ones that are perfect squares, aren't covering 100% of the avatar color circle behind it.  This leads to an extremely thin line of color that isn't smooth and kinda makes it look bad.  Attached a picture.  I have the avatar color set to a green in this one.

![IMG_624B5B46A0B2-1](https://user-images.githubusercontent.com/10711395/128252401-acba6513-3848-4d76-b656-efa52cc8dee0.jpeg)

**Comment by demchenkoalex** [comment]
Hi, thanks for reporting, will take a look

**Comment by demchenkoalex** [comment]
Released in [v1.2.0](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.2.0).
