### ISSUE TITLE
Old issue still can happen:  BoxConstraints has a negative minimum width

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#66]
https://github.com/flyerhq/flutter_chat_ui/issues/54

You can still send spaces from the web by pressing 'Enter' on an empty box.  I found the old ticket when I discovered this same error in my logs.

Also, unrelated, can't figure out steps or anyway to consistently do it, but pressing Enter on web sometimes will create a new line instead of send.

**Comment by demchenkoalex** [comment]
Hi, thanks for reporting. Forgot about the keyboard input, will add another check for an empty message.

Regarding the unrelated, I am using APIs provided by Flutter, you can see the code, so don't know if this is something on our side.

**Comment by demchenkoalex** [comment]
Released in [v1.2.0](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.2.0).
