### ISSUE TITLE
Doesn't it support voice messages yet?

### ISSUE THREAD

**Issue by TangGongWen1991** [flyerhq/flutter_chat_ui#667]
hey，i'm glad use this module in my project.
but i can not find voice message ui in branch master.
maybe not support yet?

**Comment by demchenkoalex** [comment]
no, progress will be tracked here - https://github.com/flyerhq/flutter_chat_ui/discussions/149. I separated implementation though, so if you don't want to wait - feel free to create your own implementation. You can submit a PR to add audio message type to core (similar to image message) and then the implementation itself can be your own widget. I will try to add all message types to core myself to unblock custom implementations if I do it before some PR.
