### ISSUE TITLE
FlyerChatImageMessage constraints

### ISSUE THREAD

**Issue by nbonamy** [flyerhq/flutter_chat_ui#668]
Default constraints for FlyerChatImageMessage are:

`this.constraints = const BoxConstraints(maxHeight: 300, minWidth: 170),`

Should it not be:

`this.constraints = const BoxConstraints(maxHeight: 300, **maxWidth**: 170),`

?

**Comment by demchenkoalex** [comment]
I think should be just `const BoxConstraints(maxHeight: 300)`, changing to this.
