### ISSUE TITLE
Inquiry About the Transition from Firebase Database to REST API in V2 Version

### ISSUE THREAD

**Issue by callmerj03** [flyerhq/flutter_chat_ui#669]
Hello,

Thanks for creating such a helpful project. I am currently using the V1 version for my application and am eagerly waiting for the V2 version. I’ve noticed that in V1, Firebase Database and operations were used for all interactions, but in V2, I see REST APIs are being utilized instead.

Could you please explain more about this change? It would be very useful for my future plans.

Thanks again!

**Comment by demchenkoalex** [comment]
Hey,

This package is designed to be backend-agnostic, so it can integrate with any backend. In v1, Firebase was not included; it was a separate package. In v2, I’ll be deprecating the Firebase package because it was challenging to maintain. Instead, I’ll provide a Firebase example to help users get started. In the long run, with community support, I’d like to offer examples for various technologies—like REST, Firebase, and GraphQL—to demonstrate that this chat UI can seamlessly work in any project.

**Comment by callmerj03** [comment]
Hello Demchenkoalex,

I have been using separate packages in my project, such as flutter_firebase_chat_core, flutter_chat_types, etc. These packages rely on Firebase functions. However, after installing your V2 code and reviewing it, I noticed that it utilizes multiple APIs.

I would like to know which technologies and databases are used for these APIs so that I can make a proper plan for my project accordingly.

Thank you for your prompt response!

Best regards,

**Comment by demchenkoalex** [comment]
Hey!

I want to clarify that this is a UI package only. It doesn't include any technologies, databases, APIs, or similar components, and it never will. The `flutter_firebase_chat_core` package you mentioned is a separate package that will be discontinued. **There will be no packages that connect to APIs, Firebase, or other services**. Instead, I will provide examples to help people get started. People can use these examples as a foundation or create their own logic. Currently I have only API example.

> I would like to know which technologies and databases are used for these APIs so that I can make a proper plan for my project accordingly.

There are no specific technologies or databases included. You can choose your own technology and database. This package is UI-only. You will use your chosen technology and database to fetch and store messages, while this package will simply display them on the screen.

**Comment by callmerj03** [comment]
Hello,

Thank you again for your quick response.

I noticed that in your GitHub project, you are using the flutter_chat_core package and APIs for chat functionality. I want to know if those APIs are publicly available for use in my project.

Looking forward to your response!

**Comment by demchenkoalex** [comment]
Hello,

No, APIs are not publicly available, I am just showcasing that chat can work with the REST API.
