### ISSUE TITLE
Pagination when you are the user who has sent the most recent message - scrolls to bottom

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#67]
Attached a video to try to make things more clear.
- At the beginning of the video the current user has sent the most recent message: "52"
- When scrolling up and paginating. The new messages load and then it shoots back to the bottom.
- The user "Monkey" then sends a message "test"
- Current user is no longer the user that has sent the most recent message
- When scrolling up and paginating everything works perfectly.  Doesn't shoot back down to the bottom.
- Current user sends another message "Test2" and is now the user that has sent the most recent message again.
- When scrolling up and paginating it shows new messages load and shoots back down to the bottom again. 

https://user-images.githubusercontent.com/10711395/128265310-3a23d325-cb55-41cf-a939-67026aad3093.mov

**Comment by demchenkoalex** [comment]
HI! Thanks for reporting this, something to look at. But honestly, I'm thinking to remove this scroll to bottom whatsoever, because there are a lot of issues with it and tons of ifs in the code already, can't find a way for Flutter to handle it smoothly

**Comment by zahidshaikh08** [comment]
> HI! Thanks for reporting this, something to look at. But honestly, I'm thinking to remove this scroll to bottom whatsoever, because there are a lot of issues with it and tons of ifs in the code already, can't find a way for Flutter to handle it smoothly

Agree with you, IMO we already have a many packages containing whether scrollview reached to bottom state or not so why not remove and make things simpler for developers as this lib is doing so much work under the hood, which makes code unreadable sometimes.

**Comment by m-j-g** [comment]
> > HI! Thanks for reporting this, something to look at. But honestly, I'm thinking to remove this scroll to bottom whatsoever, because there are a lot of issues with it and tons of ifs in the code already, can't find a way for Flutter to handle it smoothly
> 
> Agree with you, IMO we already have a many packages containing whether scrollview reached to bottom state or not so why not remove and make things simpler for developers as this lib is doing so much work under the hood, which makes code unreadable sometimes, which affects the actual purpose and aim of this awesome library.

Hmm, I'm not sure.  This isn't about knowing when the scrollview reached the bottom state.  I would think 

> HI! Thanks for reporting this, something to look at. But honestly, I'm thinking to remove this scroll to bottom whatsoever, because there are a lot of issues with it and tons of ifs in the code already, can't find a way for Flutter to handle it smoothly

Interesting.  What are the cases when it should scroll to the bottom?  I'm assuming it would still scroll to the bottom when new messages come in.

**Comment by m-j-g** [comment]
> HI! Thanks for reporting this, something to look at. But honestly, I'm thinking to remove this scroll to bottom whatsoever, because there are a lot of issues with it and tons of ifs in the code already, can't find a way for Flutter to handle it smoothly

Interesting, when are the cases that it should scroll to the bottom?  I assume it would still scroll to the bottom when new messages come in.

**Comment by demchenkoalex** [comment]
It should only scroll when you send a message

**Comment by m-j-g** [comment]
> It should only scroll when you send a message

So you're thinking of making it to where if I'm texting back and forth with someone, each time the other person replies, I have to manually scroll down to see it?

**Comment by demchenkoalex** [comment]
Yes. Otherwise you won't be able to read history at your own pace. I have a friend who sends messages using 1 word instead of sentences, imaging reading his replies when chat scrolls to bottom with every message. Plus, eventually, there will be a floating scroll to bottom button, which in one tap will bring you to recent messages.

**Comment by m-j-g** [comment]
Gotcha, but if I'm already at the bottom and having a current conversation, which is going to be most the time, you don't want the user having to scroll down on each reply, right?

**Comment by demchenkoalex** [comment]
It is a different case and animation takes care of that, it will appear as you'd expect

**Comment by demchenkoalex** [comment]
Fixed in [v1.3.0](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.3.0).
