### ISSUE TITLE
How to send video messages

### ISSUE THREAD

**Issue by xiaoli55979** [flyerhq/flutter_chat_ui#672]
I am currently using version v1. I sent a video message in the "click" style, but after sending it, there is only a loading circle in the lower right corner, nothing else. I did not find any examples of sending videos. Is this the right way to write it?
  
void _handleVideoSelection() async {
    final result = await ImagePicker().pickVideo(
      source: ImageSource.gallery,
    );

    if (result != null) {
      final videoBytes = await result.readAsBytes();
      final videoController = VideoPlayerController.file(File(result.path));

      await videoController.initialize();

      final message = types.VideoMessage(
        author: _user,
        createdAt: DateTime.now().millisecondsSinceEpoch,
        height: videoController.value.size.height,
        id: const Uuid().v4(),
        name: result.name,
        size: videoBytes.length,
        uri: result.path,
        width: videoController.value.size.width,
        status: Status.sending,
        // duration: videoController.value.duration.inMilliseconds,
      );

      _addMessage(message);
      videoController.dispose();
    }
  }

**Comment by demchenkoalex** [comment]
Hey! `v1` has types yes, but there is no implementation of video messages. You will need to write your own. I don't remember the api now, but if you search for `builder` something functions I think some will allow you to build it.

`v2` does not have implementation either, but it is the version where I will add it.

**Comment by xiaoli55979** [comment]
Okay, I understand, thank you for your reply
