### ISSUE TITLE
Feature request: multiple (or expandable) attachment button

### ISSUE THREAD

**Issue by tonypottera24** [flyerhq/flutter_chat_ui#681]
Thanks for building this great tool. Very appreciate.

I've some suggestions. As we have seen in many chatting apps, after pressing the attachment button, user can chose one of many kinds of attachments such as "open camera", "pick image from gallery" and "pick an audio file", ...
It would be great if there was a way to add multiple buttons.
`showModalBottomSheet` works but not that fashionable...

examples:
Facebook Messanger
![IMG_64694AB890BE-1](https://github.com/user-attachments/assets/f6c79f39-6a70-41e1-a5ee-a591c32cbd37)

**Comment by demchenkoalex** [comment]
Hey!

I think making this customizable will be challenging. For example, what if someone wants the audio button on the left of the image or on the right of the input? What if someone doesn't want the animation but prefers a bottom sheet instead?

Maybe it's better to allow package users to override these elements completely using `inputBuilder`?

What do you think?

**Comment by tonypottera24** [comment]
`inputBuilder` sounds like a good idea.

**Comment by demchenkoalex** [comment]
it is already available then :) I will just need to export height notifier, will do in the next release, probably this weekend

**Comment by tonypottera24** [comment]
Thank you @demchenkoalex, appreciate. 
I'm wondering if there are any sample codes or documentation of how to use it.

**Comment by demchenkoalex** [comment]
yes just check example, for example `local.dart`

```dart
Chat(
  builders: Builders(
    textMessageBuilder: (context, message) => FlyerChatTextMessage(message: message),
    imageMessageBuilder: (context, message) => FlyerChatImageMessage(message: message),
  ),
  chatController: _chatController,
  user: widget.author,
  onMessageSend: _addItem,
  onMessageTap: _removeItem,
  onAttachmentTap: _handleAttachmentTap,
)
```

just pass `inputBuilder` in `Builders` and return your Widget

**Comment by demchenkoalex** [comment]
once again, using `inputBuilder` you overwrite the whole widget, you don't even enter that file.  `onAttachmentPressed` will not work either, you will have your own buttons with press handlers.

https://github.com/flyerhq/flutter_chat_ui/blob/66ec619b1b5f7100dce25e59cc7232bdf91891d8/packages/flutter_chat_ui/lib/src/chat.dart#L124

**Comment by tonypottera24** [comment]
Thank you for the explanation. 
I did visit that file. I understand this can be achieved by `inputBuilder`. 

I love your text input box and the send button. I'm just considering a way to only override the attachment button, and this change can be sustained over time (so I don't need to check if you have any fashion updates on the `ChatInput`).

**Comment by demchenkoalex** [comment]
yes I get that, but like we agreed above, it will be hard to make attachment button customisable so much so it works for everybody. So sometimes people will have to override the whole file. I am not sure I will be able to support animation inside, but I had plans to make buttons rearrangement available somehow, will have to think about that.

**Comment by tonypottera24** [comment]
I tried to create a PR https://github.com/flyerhq/flutter_chat_ui/pull/682.
This might be a way to allow users to only override the attachment button.

**Comment by demchenkoalex** [comment]
it removes default implementation though, I will have to think about that
