### ISSUE TITLE
How to remove input field?

### ISSUE THREAD

**Issue by AdrKacz** [flyerhq/flutter_chat_ui#685]
Hello,

First, thank you for the fantastic work on this package!

I'm trying to use only the animated chat view (the widget displaying messages) without the input bar. Is there a way to hide the input bar and avoid passing "onSendPressed," as another component handles message sending?

Thank you!

**Comment by demchenkoalex** [comment]
Hey! If you're using `v2` I think you can just return empty SizedBox in

```dart
builders: Builders(inputBuilder: const SizedBox.shrink()),
```

**Comment by AdrKacz** [comment]
Thank you, that works! 😁
