### ISSUE TITLE
ChatAnimatedList will get stuck when there is a large amount of chat content, it seems that the animation is not completed.

### ISSUE THREAD

**Issue by zhangheng2022** [flyerhq/flutter_chat_ui#693]
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
ChatAnimatedListState#ca8ba(ticker active) was disposed with an active Ticker.
ChatAnimatedListState created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was: Ticker(created by ChatAnimatedListState#ca8ba)
The stack trace when the Ticker was actually created was:

**Comment by demchenkoalex** [comment]
I think my dispose method is wrong, I dispose super before cancelling tickers and disposing of other resources. I will move `super.dispose()` at the end of the method.

```dart
  @override
  void dispose() {
    super.dispose();
    _scrollToBottomShowTimer?.cancel();
    _scrollToBottomController.dispose();
    _operationsSubscription.cancel();
  }
 ```

**Comment by demchenkoalex** [comment]
commit: https://github.com/flyerhq/flutter_chat_ui/commit/f81143759c79ff6a222ee516be8e0bc1d785df95
