### ISSUE TITLE
Chat container layout constraints seem fixed 

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#73]
So, two different scenarios here where it  doesn't seem I have any control over this outside of the package.
There are cases when I put the chat in a container for portion of the screen.  The first scenario on the phone, I get this space at the top of the container which I'm assuming is some sort of fixed top padding.  Attached a screen shot.

The second would be on a tablet or web where it only takes up a certain width of the screen.  This one is actually the bigger issue because it cuts off words and you can't read them.  I played with this a bit, and if you put the Chat object in a SizedBox under a certain width, lets say you set it to 300, the bubbles don't become less wide, they just start cutting off like the 2nd screen shot.  You can see the whole word "the" is missing in the 2nd screen shot.

![top margin](https://user-images.githubusercontent.com/10711395/129934420-6363a84e-0a57-4542-ab48-2b9a84e019a8.jpeg)

<img width="441" alt="Screen Shot 2021-08-18 at 11 22 01 AM" src="https://user-images.githubusercontent.com/10711395/129935088-6309e0bd-10e7-426c-a8dc-62a2ab6c063f.png">

**Comment by demchenkoalex** [comment]
Hmm.. I don't think we have manpower to play with embedded chat at this point. But if anyone wants to take a look feel free to take it. I assume that we are calculating width based on a whole screen width, not a parent widget, so this can be addressed I guess.

**Comment by m-j-g** [comment]
yeah, maybe its using like a Mediaquery width and not using a layout builder width?

**Comment by demchenkoalex** [comment]
I'd assume so :)

**Comment by m-j-g** [comment]
I'm pretty sure its just this change at line 252 in chat.dart

`return LayoutBuilder(builder: (BuildContext context, BoxConstraints constraints) {
      final _messageWidth = widget.showUserAvatars && message.author.id != widget.user.id
          ? min(constraints.maxWidth * 0.72, 440).floor()
          : min(constraints.maxWidth * 0.78, 440).floor();
      return Message(
        key: ValueKey(message.id),
        buildCustomMessage: widget.buildCustomMessage,
        message: message,
        messageWidth: _messageWidth,
        onMessageLongPress: widget.onMessageLongPress,
        onMessageTap: (tappedMessage) {
          if (tappedMessage is types.ImageMessage && widget.disableImageGallery != true) {
            _onImagePressed(tappedMessage);
          }

          widget.onMessageTap?.call(tappedMessage);
        },
        onPreviewDataFetched: _onPreviewDataFetched,
        roundBorder: map['nextMessageInGroup'] == true,
        showAvatar: map['nextMessageInGroup'] == false,
        showName: map['showName'] == true,
        showStatus: map['showStatus'] == true,
        showUserAvatars: widget.showUserAvatars,
        usePreviewData: widget.usePreviewData,
      );
    });`

**Comment by demchenkoalex** [comment]
Fixed in [v1.3.0](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.3.0).
