### ISSUE TITLE
Crash on deserializing previewData

### ISSUE THREAD

**Issue by m-j-g** [flyerhq/flutter_chat_ui#78]
error: type 'int' is not a subtype of type 'double' in type cast
which would cause the deserialization to fail and not show the message

After debugging this for a while I located the cause.

on preview_data.dart
            : height = json['height'] as double,
        url = json['url'] as String,
        width = json['width'] as double;

I believe this should be:
       height = json['height'].toDouble(),
        url = json['url'] as String,
        width = json['width'].toDouble();

Which would fix the issue.

Here was the link that was sent
https://www.azcardinals.com/news/colt-mccoy-makes-cameo-at-kyler-murray-birthday-celebration

leads to previewData with  a height: 720, width: 1280

**Comment by demchenkoalex** [comment]
Should be fixed in [v1.3.0](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.3.0).

**Comment by m-j-g** [comment]
@demchenkoalex doesn't look like this was fixed.

**Comment by demchenkoalex** [comment]
@m-j-g you sure? your link works for me. There was a major change in `chat_types` where I replaced manual `fromJson`, `toJson` to `json_serializable` and it automatically applied a fix, where instead of `as double` it does `as num` then `toDouble`.

**Comment by m-j-g** [comment]
I’m sorry. Not the same issue. It looks like type isn’t being set in 1.3.0 causing a different deserialization issue.

**Comment by demchenkoalex** [comment]
Yes, we are aware of it now, json_serializable ignored properties from superclass and I missed that. It will be fixed today, cause nothing works now basically.

**Comment by demchenkoalex** [comment]
Should be fixed in [v1.3.1](https://github.com/flyerhq/flutter_chat_ui/releases/tag/v1.3.1).
