### ISSUE TITLE
🚧 Fix documentation website

### ISSUE THREAD

**Issue by demchenkoalex** [flyerhq/flutter_chat_ui#80]
Hello everyone,

We are experiencing problems with documentation website and our DevOps engineer is on leave now, expected website return is mid September, meanwhile you can use this cached version https://flyer-flutter-docs.pages.dev/chat-ui/

Sorry for the inconvenience.

**Comment by cristaloleg** [comment]
Right now https://flyer-flutter-docs.pages.dev/chat-ui/ contains the latest release and will be updated automatically. There is a small question regarding Docusaurus config (https://github.com/facebook/docusaurus/issues/5497) when it will be resolved all Flyer documentation will be available at https://docs.flyer.chat/flutter as before

**Comment by cristaloleg** [comment]
https://docs.flyer.chat/flutter/chat-ui/ works fine, but not https://flyer-flutter-docs.pages.dev/chat-ui

Probably it's ok for us, because official docs are at docs.flyer.chat, closing.
