### ISSUE TITLE
Msg Author details proplem

### ISSUE THREAD

**Issue by abohamza8k** [flyerhq/flutter_chat_ui#9]
first of all, your work is fantastic.
but you make only author id as required and when we add the remain User data like Avatar Url, first name and last name nothing changed.
how we can preview msg sender details beside msg?
thank you very much

**Comment by abohamza8k** [comment]
> first of all, your work is fantastic.
> but you make only author id as required and when we add the remain User data like Avatar Url, first name and last name nothing changed,
> how we can previw msg sender details?
> thank you very much

**Comment by demchenkoalex** [comment]
Hi @abohamza8k. Thanks for the kind words :) To clarify, you would like to have a profile view when you tap on a message or optional details like avatar or name somewhere around the message in the UI?

**Comment by jangruenwaldt** [comment]
An avatar would be great, yes, for group chats

**Comment by demchenkoalex** [comment]
this is in the works :)

**Comment by Ajay1901** [comment]
Hey, your library is awesome and helping in a great way for our app. But we feel you are lacking a very vital feature... i.e, in groupRooms the message author's name is not there (who sent what). Are you looking forward to implement anytime soon? If yes any sort of ETA you have in mind?

**Comment by dariakhimych** [comment]
🚫 **The issue is closed.** In order to track the progress please see issue #24.
